window.ARTICLE_DE = {
  slug: "dis-teli",
  title: "Zahnspange (Metall / Keramik)",
  category: "Kieferorthopädie",
  metaDescription: "Metall- und Keramikbrackets: wie sie wirken, wie viele Monate die Behandlung dauert, Schmerz und Hygiene im Alltag — und warum die Retention zählt.",
  lead: "Die festsitzende Spangenbehandlung bewegt Zähne kontrolliert über kleine, auf jeden Zahn geklebte Brackets, die ein Bogendraht verbindet. Bei der Smile Group wird die Wahl zwischen Metall- und Keramikbrackets erst geplant, wenn Biss und Zahnstellung beurteilt sind. Auf dieser Seite finden Sie, wie die Behandlung wirkt, wie lange sie dauert, was sie für den Alltag bedeutet und was in der Retentionsphase passiert.",
  faqs: [
    { q: "Was ist die Spangenbehandlung und wie wirken festsitzende Brackets?", a: "Ein Bracket ist ein kleines, mit Spezialkleber auf die Zahnoberfläche geklebtes Element, das den Bogendraht hält. Jedes Bracket wird in festgelegtem Winkel und festgelegter Höhe mittig auf dem Zahn positioniert; liegt der Draht im Slot, will er in seine ursprüngliche Form zurückfedern und überträgt dabei eine sanfte, kontinuierliche Kraft auf den Zahn. Diese Kraft setzt den Umbau des Knochens um die Wurzel in Gang, und der Zahn wird allmählich in seine neue Position getragen. Eingesetzt wird das System bei einer Reihe von Bildern, darunter <a href=\"/de/hizmet/dislerim-yamuk/\">Engstand</a>, Lücken zwischen den Zähnen und ein tiefer Biss." },
    { q: "Was unterscheidet Metallbrackets von Keramikbrackets (zahnfarben)?", a: "Metallbrackets bestehen aus einer Edelstahllegierung, haben ein schlankes Profil und verhalten sich beim Drahtwechsel in Sachen Reibung vorhersehbar. Keramikbrackets sind zahnfarben und halbtransparent, also deutlich unauffälliger, aber etwas voluminöser und mit anderem Bruchprofil. Erwachsene mit besonderem Blick aufs Erscheinungsbild greifen oft zu Keramik, während Metallbrackets in längeren, mehrstufigen Plänen ein Vorteil sein können. Wer die Sichtbarkeit noch weiter senken möchte, kann sich auch die <a href=\"/de/hizmet/seffaf-plakla-ortodonti/\">Aligner-Therapie</a> und <a href=\"/de/hizmet/invisalign/\">Invisalign</a> ansehen." },
    { q: "Wer ist ein geeigneter Kandidat für die festsitzende Spange?", a: "Festsitzende Spangen lassen sich einsetzen, sobald die meisten bleibenden Zähne durchgebrochen sind — im Allgemeinen ab etwa zwölf Jahren, ohne obere Altersgrenze. Bei Erwachsenen mit gesundem Zahnfleisch und gutem Knochenhalt lässt sich die Behandlung problemlos planen. Mittlerer bis schwerer Engstand, <a href=\"/de/hizmet/dislerim-ayrik/\">Lücken zwischen den Zähnen</a>, rotierte Zähne und das Einordnen eines retinierten Zahns in den Bogen sind typische Indikationen. Bei jüngeren, noch wachsenden Kindern werden meist zuerst die Ansätze der <a href=\"/de/hizmet/cocuk-ortodontisi/\">Kieferorthopädie für Kinder</a> erwogen." },
    { q: "Was passiert beim ersten Termin und welche Phasen durchläuft die Behandlung?", a: "Zuerst werden die kieferorthopädischen Unterlagen erhoben — Panorama- und Fernröntgenseitenbild, intraorale Fotos und ein digitaler Scan zur Bissanalyse. Steht der Plan, werden Zahnstein entfernt und Karies gefüllt; braucht es zusätzlichen Platz, werden Extraktion oder minimale approximale Schmelzreduktion eingeplant. Beim Klebetermin wird die Zahnoberfläche mit Säuregel angeätzt, ein Haftvermittler aufgetragen und jedes Bracket einzeln mit lichthärtendem Kunststoff befestigt. In der aktiven Phase wird der Draht alle vier bis acht Wochen gewechselt und geprüft, wie konsequent Sie Ihre Gummizüge tragen." },
    { q: "Wie lange dauert die Behandlung?", a: "In den meisten Fällen dauert die aktive Behandlung 18 bis 24 Monate; bei begrenztem Engstand kann sie auf rund 12 Monate sinken und bei skelettaler Abweichung oder einem retinierten Zahn über 30 Monate hinausgehen. Den Zeitplan formen die biologische Geschwindigkeit der Zahnbewegung, Ihre Termintreue und das konsequente Tragen der Gummizüge. Sich lösende Brackets sind ein häufiger Grund für Verlängerungen. Zu Beginn bekommen Sie eine Spanne genannt, die mit den Kontrollen präziser wird." },
    { q: "Mit welchem Schmerz- und Empfindlichkeitsniveau sollte ich rechnen — und was hilft?", a: "Das Aufkleben der Brackets verursacht meist kein Unbehagen — es wird nichts geschnitten oder gebohrt. Die Empfindlichkeit beginnt typischerweise wenige Stunden nach dem Einsetzen des ersten Drahts, ist am zweiten und dritten Tag am deutlichsten und legt sich bei den meisten binnen einer Woche. Eine mildere Version davon kann sich nach jedem Drahtwechsel für zwei bis drei Tage wiederholen. Weiche Kost, kaltes Wasser und ein empfohlenes Schmerzmittel machen diese Tage angenehmer." },
    { q: "Wozu dienen die farbigen Gummis — und beeinflusst die Farbwahl die Behandlung?", a: "Elastomerligaturen sind kleine farbige Ringe, die den Bogendraht im Bracketslot halten; sie werden bei jeder Kontrolle erneuert. Die gewählte Farbe hat keinerlei Wirkung auf die Behandlung und ist reine Geschmackssache — hellere Töne können sich durch Kaffee, Tee und stark gewürztes Essen allerdings verfärben. Bei Keramikbrackets fällt diese Verfärbung mit durchsichtiger Ligatur stärker auf. Intermaxilläre Gummizüge sind ein ganz eigenes Thema: Sie korrigieren die Bissrelation und müssen über lange Strecken des Tages getragen werden." },
    { q: "Welche Lebensmittel können die Spange beschädigen?", a: "Hartes und Klebriges kann ein Bracket von der Zahnoberfläche reißen oder den Bogendraht verbiegen. Walnüsse, Haselnüsse, Eis, Karamellbonbons, Kaugummi und Lokum stehen ganz oben auf der Risikoliste. Bei Äpfeln, Karotten und Maiskolben ist Kleinschneiden und Kauen mit den Backenzähnen leichter als das direkte Abbeißen. Säurehaltige und zuckrige Getränke beschleunigen den Schmelzverlust rund um die Brackets — es lohnt sich, sie zu reduzieren." },
    { q: "Welche Hilfsmittel gehören zur täglichen Reinigung?", a: "Nach jeder Hauptmahlzeit putzen ist mit festsitzender Spange die goldene Regel, denn Bracketkörper und Draht schaffen geschützte Nischen für Plaque. Eine Orthodontie-Bürste mit V-förmigem Schnitt nimmt den Draht in die Mitte der Borsten; die zahnfleischseitige und die obere Bracketkante werden separat im 45-Grad-Winkel geputzt. Die Interdentalbürste reinigt die kleinen Dreiecke zwischen Draht und Zahnfleisch, und mit einer Einfädelhilfe kommt die Zahnseide unter den Draht. Eine Munddusche ist eine sinnvolle Ergänzung, ersetzt das alles aber nicht — Zusatz, kein Ersatz. Beginnendes <a href=\"/de/hizmet/dis-etim-kaniyor/\">Zahnfleischbluten</a> ist oft das früheste Zeichen, dass die Reinigung nicht ganz reicht." },
    { q: "Was ist eine White-Spot-Läsion und wie beugt man ihr vor?", a: "Eine White-Spot-Läsion ist ein matter, kreidiger Fleck, der entsteht, wenn Säure aus der um ein Bracket angesammelten Plaque dem Schmelz Mineralien entzieht. Sie ist bei festsitzender Behandlung häufig und kann unbehandelt zur Karies fortschreiten. Diese Flecken können nach dem Entfernen der Brackets auf der Fläche zurückbleiben; manche verblassen mit der Zeit, verschwinden aber womöglich nicht ganz — fortgeschrittene Fälle brauchen eine restaurative Behandlung. Zur Risikosenkung: fluoridhaltige Zahnpasta, eine empfohlene Mundspülung und regelmäßige Termine zur <a href=\"/de/hizmet/dis-tasi-temizligi/\">professionellen Zahnreinigung</a>." },
    { q: "Welche Risiken und möglichen Komplikationen gibt es?", a: "Zu den häufigeren unerwünschten Effekten festsitzender Behandlung zählen White-Spot-Bildung am Schmelz, Zahnfleischentzündung und -wucherung, gereizte Wangen- und Lippenschleimhaut und sich lösende Brackets. Wurzelresorption — die Verkürzung an der Wurzelspitze — zeigt sich in einem Teil der Fälle im Röntgenbild; meist bleibt sie begrenzt, doch schreitet sie weiter fort, lässt sie sich nicht rückgängig machen. In längeren Behandlungen können Zahnfleischrückgang und ein dünner werdender Knochenhalt an den unteren Schneidezähnen auftreten. Das Entfernen von Keramikbrackets trägt fürs Schmelzrelief ein eigenes Risikoprofil — die Abnahmetechnik wird deshalb zum Brackettyp passend gewählt. Bestehende Kiefergelenkbeschwerden können sich während der Behandlung verändern, in beide Richtungen. Das Sprechen passt sich binnen weniger Tage an; wer ein Blasinstrument spielt oder Kontaktsport treibt, bekommt einen Schutz (Mundschutz) empfohlen. Regelmäßige Kontrollen und gründliche Hygiene halten die meisten dieser Risiken klein." },
    { q: "Wann wird nicht behandelt oder verschoben?", a: "Bei aktiver Zahnfleischerkrankung, unbehandelter Karies oder unkontrollierter Plaque werden keine Brackets geklebt; die Kieferorthopädie wartet, bis das gelöst ist. Bei fortgeschrittenem parodontalem Knochenabbau könnte Zahnbewegung den verbliebenen Halt weiter verringern — dann wird der Plan geändert oder auf begrenztere Ziele ausgerichtet. Unkontrollierter Diabetes, eine Strahlentherapie im Kopf-Hals-Bereich in der Vorgeschichte und bestimmte Medikamente mit Wirkung auf den Knochenstoffwechsel verlangen zuerst die Abstimmung der Fachrichtungen. Bei Menschen ohne gefestigte Hygieneroutine wird das Timing wegen des White-Spot-Risikos neu überdacht. Bei ausgeprägter skelettaler Abweichung reichen Brackets allein nicht — geplant wird zusammen mit der <a href=\"/de/hizmet/ortognatik-cerrahi/\">Umstellungsosteotomie (Kiefer-OP)</a>." },
    { q: "Warum ist die Retentionsphase unverzichtbar?", a: "Die Retention ist ein fester Bestandteil der Behandlung — sie soll die Zähne in ihrer neuen Position halten, sobald die Brackets abkommen. Die parodontalen Fasern um jeden Zahn ziehen ihn Richtung alter Position zurück; wird diese Phase übersprungen, kehrt der Engstand oft wieder. Ein dünner, geflochtener Festdraht wird an die Rückseite der oberen und unteren Schneidezähne geklebt, meist ergänzt um einen herausnehmbaren durchsichtigen Retainer für die Nacht. Weil der Festdraht über Jahre bleibt, sammeln sich dahinter weiterhin Plaque und Zahnstein — hören Sie mit der Zwischenraumpflege nicht auf, nur weil die Brackets weg sind; reinigen Sie täglich mit der Einfädelhilfe unter dem Draht. Bei den Kontrollen wird nicht nur die Zahnstellung angesehen, sondern auch, ob der Draht intakt und das Zahnfleisch darum gesund ist. Im ersten Jahr wird der Retainer intensiver getragen, danach meist nur noch nachts — und das empfehlen wir über viele Jahre. Merken Sie, dass sich der Festdraht gelöst hat, melden Sie sich ohne Verzögerung: Zähne können binnen weniger Wochen zu wandern beginnen." },
    { q: "Was tue ich im Notfall und wann sollte ich die Praxis kontaktieren?", a: "Ein gelöstes Bracket ist meist kein Notfall — es bleibt in der Regel am Draht hängen und lässt sich mit orthodontischem Schutzwachs vorübergehend fixieren. Bohrt sich das Drahtende in die Wange, decken Sie die Spitze zuerst mit Wachs ab. Hilft das nicht und muss das überstehende Ende gekürzt werden: Legen Sie Mull oder ein Taschentuch über den Bereich, damit das abgetrennte Stück nicht verschluckt oder eingeatmet wird, schneiden Sie es mit einem sauberen Nagelknipser ab und entfernen Sie das Stück mitsamt dem Tuch. Rufen Sie auch nach solchen Übergangslösungen in der Praxis an — ein lange unrepariertes Bracket verzögert die Behandlung. Haben Sie ein Stück verschluckt, hat sich ein Draht in den Mundboden gebohrt oder geht eine Schwellung nicht zurück, melden Sie sich sofort, ohne zu warten." }
  ],
  closing: "Ob die festsitzende Spangenbehandlung zu Ihrer Zahnstellung passt, zeigt sich erst nach klinischer Untersuchung und vollständigen kieferorthopädischen Unterlagen. Die Frage Metall oder Keramik beantworten wir am liebsten gemeinsam — entlang Ihrer Alltagsgewohnheiten, Ihrer Hygieneroutine und Ihrer Behandlungsziele. Für Termine und Fragen erreichen Sie uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
