window.ARTICLE_DE = {
  slug: "dolgu",
  title: "Zahnfüllungen",
  category: "Allgemeine Behandlungen",
  metaDescription: "Füllungen bei Karies: Komposit- und Glasionomer-Optionen, Behandlungsschritte, Empfindlichkeit danach, Risiken, Sekundärkaries und Erneuerung.",
  lead: "Karies verursacht in Schmelz und Dentin einen bleibenden Substanzverlust — der Körper kann das verlorene Gewebe nicht von selbst ersetzen. Eine Füllung repariert den Hohlraum, der nach dem Ausräumen der Karies zurückbleibt, mit einem geeigneten Material und stellt die Kaufunktion des Zahns wieder her. Diese Seite behandelt die Füllungstherapie bei Karies, die Materialoptionen, die mögliche Empfindlichkeit danach und die Erneuerung einer Füllung im Laufe der Zeit.",
  faqs: [
    { q: "Was ist eine Füllung und wann braucht man sie?", a: "Fortschreitende Karies höhlt im Zahn einen Hohlraum aus, der sich mit Bakterien füllt. Das geschädigte Gewebe wird entfernt und der Hohlraum mit einem biokompatiblen Material verschlossen — das meint der Begriff Füllung. Ziel ist, den Zahn normal funktionieren zu lassen und das Fortschreiten der Läsion in Richtung Pulpa, des Nervgewebes des Zahns, zu bremsen. Bei sehr frühen, auf den Schmelz begrenzten Läsionen kann auch entschieden werden, dass Beobachtung und vorbeugende Pflege allein genügen. Farb- und Formkorrekturen aus ästhetischen Gründen behandelt unsere Seite zu den <a href=\"/de/hizmet/estetik-dolgular/\">ästhetischen Füllungen</a>." },
    { q: "Wie wird die Karies ausgeräumt und wie läuft eine Füllung ab?", a: "Zuerst wird die tatsächliche Ausdehnung der Karies über die klinische Untersuchung und, wo nötig, ein Röntgenbild bestimmt. Nach örtlicher Betäubung wird das erweichte Dentin mit Bohrer oder Handinstrumenten entfernt — so viel gesundes Gewebe wie möglich bleibt erhalten. Der Hohlraum wird gespült, getrocknet und je nach Tiefe mit einer schützenden Unterfüllung versehen. Nahe der Pulpa kann ein Abdeckmaterial wie Kalziumhydroxid gewählt werden. Zur Isolation kann ein Gummituch — der Kofferdam — eingesetzt werden, denn Komposit haftet auf feuchter Fläche schlecht. Bei Kavitäten, die den Kontaktbereich zwischen den Zähnen einbeziehen, formen Matrizenband und Keil den Kontaktpunkt und den Übergang zum Nachbarzahn. Beim Komposit werden Ätzgel und Haftvermittler aufgetragen, das Material in dünnen Schichten aufgebaut und jede Schicht einzeln mit der Polymerisationslampe gehärtet. Zum Schluss wird der Biss mit Artikulationspapier geprüft, ein zu hoher Kontakt eingeschliffen und die Oberfläche poliert — ein Schritt, der nicht ausgelassen werden sollte, denn die Politur verringert die Plaquebildung." },
    { q: "Welche Füllungsarten werden verwendet?", a: "Kompositkunststoff ist heute weit verbreitet, weil er die natürliche Zahnfarbe trifft und in einem Termin gelegt werden kann. Glasionomerzement gibt Fluorid ab und lässt sich auch dort legen, wo sich der Bereich nicht vollständig trocken halten lässt — deshalb wird er bei Milchzähnen, Wurzelkaries und provisorischen Versorgungen eingesetzt. Amalgam wiederum ist nach dem Minamata-Übereinkommen in vielen Ländern nur noch eingeschränkt in Gebrauch und für Kinder und Schwangere nicht das Material der Wahl. Neben diesen direkt im Mund geschichteten Füllungen gehören auch <a href=\"/de/hizmet/inlay-onlay-dolgular/\">Inlay- und Onlay-Füllungen</a> zu den Optionen — sie entstehen nach Abformung im Labor und werden dann auf den Zahn zementiert. Form- und Farbkorrekturen an Frontzähnen behandelt gesondert das <a href=\"/de/hizmet/bonding/\">Bonding</a>." },
    { q: "Wer kann eine Füllung bekommen — auch Kinder?", a: "Eine Füllung kommt in jedem Alter infrage, in dem Karies entsteht — vom Milchzahn bis zum bleibenden Gebiss. Bei Kindern fällt die Wahl meist auf Glasionomer oder Komposit; auch <a href=\"/de/hizmet/fissur-ortucu/\">Fissurenversiegelungen</a> können Teil desselben Vorsorgeplans sein. Bei schwacher Mundhygiene wird vor der Füllung die Zahnfleischgesundheit beurteilt. In der Schwangerschaft gilt das zweite Drittel im Allgemeinen als der geeignetere Zeitraum." },
    { q: "Wie lange dauert ein Füllungstermin?", a: "Eine kleine, einflächige Kavität ist meist in zwanzig bis dreißig Minuten versorgt. Restaurationen über mehrere Flächen einschließlich der Kontaktpunkte können bis zu fünfundvierzig Minuten brauchen. Die Dauer hängt direkt davon ab, wo die Karies sitzt und wie tief sie reicht. Die Betäubung selbst kann Lippe und Zunge noch einige Stunden taub lassen. Sind mehrere Zähne zu versorgen, kann der Plan auf einige Termine aufgeteilt werden." },
    { q: "Warum treten nach einer Füllung Empfindlichkeit oder Ziehen auf?", a: "Empfindlichkeit auf Kälte und beim Zubeißen ist in den ersten Tagen nach der Behandlung häufig und legt sich meist binnen weniger Tage. Die Ursache ist oft die Wärmeentwicklung des Bohrers, freiliegende Dentinkanälchen oder ein minimal zu hoch gebliebener Bisskontakt. Gibt es eine zu hohe Stelle, wird der Kontakt in einem kurzen Termin angepasst — danach verschwindet die Beschwerde meist schnell. Verstärkt sich der Schmerz nachts, beginnt er von selbst oder wird er durch Wärme ausgelöst, kann eine Pulpaentzündung dahinterstecken, und eine <a href=\"/de/hizmet/kanal-tedavisi/\">Wurzelbehandlung</a> kann nötig werden. Anhaltende Empfindlichkeit behandelt auch unsere Seite <a href=\"/de/hizmet/disim-sizliyor/\">Empfindliche Zähne</a>." },
    { q: "Worauf achten — und wann darf man wieder essen?", a: "Mit lichtgehärtetem Komposit können Sie direkt nach dem Termin wieder kauen; vernünftig ist trotzdem, das Abklingen der Betäubung abzuwarten — sonst beißen Sie sich unbemerkt auf Lippe oder Wange. Bei Glasionomerfüllungen wird womöglich gebeten, einige Stunden auf harte Kost zu verzichten. Sehr heiße und sehr kalte Getränke können die Empfindlichkeit in den ersten Tagen verstärken. Führen Sie die Zahnseide am Kontaktpunkt vorsichtig am Füllungsrand entlang. Regelmäßige Termine zur <a href=\"/de/hizmet/dis-tasi-temizligi/\">professionellen Zahnreinigung</a> reduzieren die Plaquebildung am Rand." },
    { q: "Welche Risiken und Nachteile gibt es?", a: "Jede Restauration bedeutet einen gewissen Verlust gesunder Substanz, und kein Material verhält sich exakt wie natürlicher Schmelz. Beim Komposit kann die Polymerisationsschrumpfung am Rand einen kleinen Spalt öffnen, aus dem Mikroundichtigkeit entstehen kann. Die Oberfläche einer Kompositfüllung kann sich mit der Zeit durch Tee, Kaffee und Rauchen verfärben. In tiefen Kavitäten kann die Pulpa ihre Vitalität verlieren — dann braucht der Zahn eine Wurzelbehandlung. Manche Menschen entwickeln außerdem eine Kontaktempfindlichkeit gegenüber Haftvermittlern. In stark kaubelasteten Bereichen kann eine Füllung brechen, am Rand absplittern oder ganz herausfallen. Läuft ein Riss in einen Zahnhöcker, wird die verbliebene Wand dünn, und aus der Situation kann eine umfassendere Reparatur werden, die eine <a href=\"/de/hizmet/kaplama/\">Krone</a> braucht." },
    { q: "Wann wird eine Füllung nicht gelegt oder verschoben?", a: "Bleibt zu wenig Zahnsubstanz, findet die Füllung nicht genug Halt — dann werden Onlay, Krone oder in fortgeschrittenen Fällen die Entfernung besprochen. Hat die Karies die Pulpa erreicht und schmerzt der Zahn von selbst, hat die endodontische Behandlung Vorrang. Bei Abszess oder akuter Infektion an der Wurzelspitze wird die Restauration verschoben. In Bereichen mit ausgeprägter Zahnfleischentzündung stört die Blutung die Trockenlegung — die Zahnfleischbehandlung wird vorgezogen. Bei eingeschränkter Mundöffnung ist der Weg zu den hinteren Zähnen schwierig, und die Behandlungsreihenfolge wird entsprechend angepasst." },
    { q: "Was ist Sekundärkaries und wie wird sie entdeckt?", a: "<strong>Sekundärkaries</strong> ist neue Karies, die am Rand einer bestehenden Füllung erneut beginnt — einer der Hauptgründe, warum Füllungen erneuert werden müssen. In den Spalt am Rand eingelagerte bakterielle Plaque arbeitet in einem mikroskopischen Raum weiter, den die Zahnbürste nicht erreicht. Im Frühstadium macht sie meist keine Beschwerden — entdeckt wird sie bei der Untersuchung über Randverfärbungen, eine hängen bleibende Sonde oder ein Bissflügel-Röntgenbild. Genau deshalb lohnt die jährliche Kontrolle auch ganz ohne Beschwerden. Bleibt die Läsion unbemerkt, kann sie sich unter der Füllung ausbreiten und am Ende eine umfassendere Restauration verlangen." },
    { q: "Warum fällt eine Füllung heraus und wann muss sie erneuert werden?", a: "Eine herausgefallene oder gebrochene Füllung geht meist auf übermäßige Kaulast, nächtliches Pressen, Karies am Rand oder die Form der ursprünglichen Kavität zurück. Bei jeder Kontrolle werden Randschluss, Oberflächenintegrität und Bisskontakt der Füllung überprüft. Kleine Randdefekte lassen sich manchmal einfach reparieren; ist die Undichtigkeit verbreitet, wird die ganze Füllung erneuert. Ist Ihre Füllung herausgefallen, lohnt der zügige Termin — bevor die verbliebene Zahnsubstanz Gelegenheit hat zu brechen." },
    { q: "Was bestimmt die Haltbarkeit einer Füllung?", a: "Über die Haltbarkeit entscheidet kein einzelner Faktor: Größe der Kavität, Position des Zahns im Mund, das verwendete Material, die Trockenlegung während der Behandlung und Ihre tägliche Pflege wirken zusammen. Große Restaurationen im hinteren Bereich tragen ein anderes Lastmuster als kleine Füllungen an den Frontzähnen. Wer nachts presst und keine Schiene trägt, sieht Randfrakturen tendenziell früher. Wie oft Sie zu Süßem greifen und wie gut Sie die Zahnzwischenräume reinigen, zählt genauso viel wie das Material selbst. Eine exakte Zahl lässt sich nicht nennen — eine fundierte Einschätzung gibt es bei der Untersuchung, auf Grundlage des Zustands Ihres Zahns." }
  ],
  closing: "Wenn Ihnen Empfindlichkeit, eine Verfärbung oder eine Stelle aufgefallen ist, an der die Zahnseide immer wieder hängen bleibt, lohnt die Kontrolle ohne Verzögerung — früh erkannt, genügt meist eine kleinere Restauration. Nach der Untersuchung geht das Team der Smile Group die passenden Optionen ausführlich mit Ihnen durch. Für Termine und Fragen erreichen Sie uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
