window.ARTICLE_DE = {
  slug: "empress",
  title: "Empress-Kronen (IPS Empress)",
  category: "Ästhetische Behandlungen",
  metaDescription: "Was ist eine IPS-Empress-Glaskeramikkrone, für wen eignet sie sich? Ablauf, Risiken, Pflege und der Unterschied zu E.max — Schritt für Schritt erklärt.",
  lead: "IPS Empress ist eine mit Leuzitkristallen verstärkte Glaskeramikfamilie, die in der Zahnmedizin vor allem für ästhetische Arbeiten im Frontzahnbereich eingesetzt wird. Weil sie Licht ähnlich wie natürlicher Zahnschmelz weiterleitet, gehört sie seit vielen Jahren zu den Materialien der Lächelästhetik. Auf dieser Seite finden Sie den Aufbau von Empress, die Behandlungsschritte, die Grenzen und die möglichen Risiken.",
  faqs: [
    { q: "Was ist eine Empress-Krone?", a: "Empress ist der Name, den Ivoclar Vivadent seiner <a href=\"/de/hizmet/cam-seramik/\">Glaskeramik</a>-Restaurationsfamilie gibt. Sie enthält sogenannte <em>Leuzit</em>-Kristalle, die in der Glasmatrix verteilt sind und dem Material sein charakteristisches Transluzenz- und Festigkeitsprofil geben. Da kein Metallgerüst vorhanden ist, durchdringt Licht die Restauration — der metalltypische graue Schatten bleibt aus. Der Zahntechniker formt das Material entweder im Heißpressverfahren oder durch Fräsen aus einem Block. Die fertige Restauration kann als Krone, Veneer oder Inlay ausgeführt werden." },
    { q: "Was ist der Unterschied zwischen E.max und Empress?", a: "Beide Materialien gehören zur Glaskeramikfamilie; der Unterschied liegt in der Kristallphase im Inneren. Empress enthält Leuzitkristalle, während <a href=\"/de/hizmet/emax/\">E.max</a> auf einer Lithiumdisilikat-Struktur mit einem <strong>anderen Festigkeitsprofil</strong> beruht. Deshalb decken sich die Einsatzgebiete nicht vollständig: Empress kommt eher bei Einzelzahn-Veneers und Frontzahnkronen ins Spiel, wo die Transluzenz den Ausschlag gibt. Auch Einzelzahn-Inlays und -Onlays mit begrenzter Belastung sind denkbar; für mehrgliedrige Brücken und Pläne mit konzentrierter Kaulast greift die Zahnärztin oder der Zahnarzt zu anderen Materialien. Die technischen Werte der Materialien sehen Sie in der Tabelle auf unserer Seite zum <a href=\"/de/hizmet/kaplama-materyalleri-karsilastirma/\">Kronen- und Veneer-Materialvergleich</a> nebeneinander." },
    { q: "Für wen kann diese Option geeignet sein?", a: "Verfärbungen der Frontzähne, kleinere Formabweichungen, schmale Zahnlücken und oberflächliche Frakturen an der Schmelzoberfläche sind die häufigsten Anlässe, mit denen Patienten kommen. Für alle, die die Vitalität ihres natürlichen Zahns erhalten und aggressives Beschleifen vermeiden möchten, können dünne Veneers die bevorzugte Wahl sein. Gesundes Zahnfleisch, Karies unter Kontrolle und ein stabiler Biss bilden die passendere Grundlage für diese Behandlung. In der <a href=\"/de/hizmet/gulus-tasarimi/\">Smile-Design</a>-Planung wird Empress mal allein, mal neben anderen Materialien eingesetzt. Ob es passt, klären die klinische Untersuchung und eine Wax-up-Anprobe." },
    { q: "Wo trennt sich der Weg von Fällen, die für Zirkon sprechen?", a: "Zirkon bietet ein opakes, hochfestes Gerüst, während Empress dank seiner glasigen Struktur Licht hindurchlässt. Dieser Verhaltensunterschied knüpft die Wahl an die Balance zwischen ästhetischem Anspruch und mechanischer Belastung. Wo es vorrangig darum geht, das Lichtverhalten eines einzelnen Frontzahns an die Nachbarn anzugleichen, kommt Glaskeramik ins Spiel; für breite Brücken, implantatgetragene Lösungen oder Pläne, bei denen sich die Last über eine größere Fläche verteilen muss, kann <a href=\"/de/hizmet/zirkonyum/\">Zirkon</a> die bessere Wahl sein. Beide Materialien lassen sich im selben Mund auch in unterschiedlichen Bereichen kombinieren." },
    { q: "Wie wird eine Empress-Krone eingesetzt, welche Schritte gehören dazu?", a: "Der Weg beginnt mit Untersuchung und Diagnose: Karies, Zahnfleischentzündung oder Bissprobleme werden zuerst gelöst. Dann folgt eine digitale oder klassische Abformung, und auf einem Wachsmodell entsteht der Vorentwurf. Diesen Entwurf sieht der Patient in einer provisorischen Phase im eigenen Mund; Form und Länge werden gemeinsam abgestimmt. Nach der Freigabe trägt die Zahnärztin oder der Zahnarzt eine dünne, der Materialstärke entsprechende Schicht von der Zahnoberfläche ab; bei <a href=\"/de/hizmet/porselen-lamina/\">Keramik-Veneers</a> bleibt dieser Abtrag in den meisten Fällen unter einem Millimeter. Der Techniker fertigt die Restauration im Labor durch Pressen oder Fräsen und vollendet sie mit Oberflächenbemalung und Glasur. Bei der Einprobe werden Farbton und Randschluss geprüft. Zum Schluss wird die Zahnoberfläche angeätzt und die Restauration mit einem lichthärtenden Spezialzement befestigt. Überschüsse werden entfernt, der Biss wird ein letztes Mal kontrolliert." },
    { q: "Wie lange dauert die Behandlung?", a: "Die Zahl der Termine hängt vom Umfang des Falls ab. Für einen einzelnen Zahn genügen meist zwei bis drei Besuche, wobei Abformung, Einprobe und Befestigung auf verschiedene Tage verteilt sind. Bei umfassenderen Lächelplänen können Laborfertigung und Anprobephasen den Prozess auf ein bis zwei Wochen ausdehnen. Sind vorab Zahnfleisch- oder Kariesbehandlungen nötig, verlängert sich der Zeitrahmen entsprechend." },
    { q: "Was unterscheidet Pressen und CAD/CAM-Fertigung?", a: "Die Empress-Familie unterstützt zwei Fertigungswege. Beim klassischen Verfahren bereitet der Techniker ein Wachsmodell vor, und ein Keramikrohling wird unter hoher Hitze und Druck in die Form gepresst — ein Weg, der viel Spielraum für geschichtete Farbeffekte lässt. Beim CAD/CAM-Verfahren wird die Restauration nach einem Digitalscan aus industriell gefertigten Blöcken gefräst und kann in manchen Fällen noch im selben Termin fertiggestellt werden. Weil die Blockstruktur homogen ist, fällt das Ergebnis vorhersehbar aus; geschichtete, natürlich wirkende Effekte gelingen freier mit der Presstechnik. So oder so gehört das fertige Material derselben Glaskeramikfamilie an." },
    { q: "Ist das dasselbe Produkt wie das Komposit Empress Direct?", a: "Nein — die Namensähnlichkeit sorgt recht häufig für Verwirrung. Empress Direct ist ein lichthärtendes Kompositfüllungssystem, das die Zahnärztin oder der Zahnarzt direkt im Mund verarbeitet; es gehört nicht in dieselbe Materialklasse wie laborgefertigte Glaskeramikrestaurationen. Kompositarbeiten sind in einem einzigen Termin abgeschlossen und brauchen meist eine begrenztere Oberflächenvorbereitung; Kompositoberflächen können sich in Glanz und Farbstabilität mit der Zeit verändern, Keramikoberflächen verhalten sich hier anders. Für kleine Formkorrekturen kann <a href=\"/de/hizmet/bonding/\">Bonding</a> genügen, während für umfangreichere Farb- und Formveränderungen die Keramikoptionen ins Spiel kommen." },
    { q: "Welche Risiken und möglichen Komplikationen gibt es?", a: "Fraktur und Rissbildung sind die Hauptsorgen bei Glaskeramikrestaurationen; der Biss auf einen harten Gegenstand oder ein Stoß kann die Restauration zerbrechen, meist ist dann eine Neuanfertigung nötig. Beschliffene Zähne können vorübergehend auf Heiß und Kalt empfindlich reagieren; selten verliert die Pulpa ihre Vitalität, und eine Wurzelbehandlung wird nötig. An der Klebefuge können sich mit der Zeit Mikroundichtigkeit und Randverfärbungen entwickeln. In manchen Fällen löst sich die Restauration im Ganzen; die Zahnärztin oder der Zahnarzt beurteilt die Fläche und plant Wiederbefestigung oder Ersatz. Zieht sich das Zahnfleisch zurück, kann der Restaurationsrand sichtbar werden. Der abgetragene Schmelz wächst nicht nach — die Entscheidung ist deshalb <strong>unumkehrbar</strong>. Bei Menschen, die <a href=\"/de/hizmet/dislerimi-sikiyorum/\">mit den Zähnen pressen</a>, ist das Frakturrisiko erhöht." },
    { q: "Wann wird sie nicht gemacht oder verschoben?", a: "Aktive Karies, unbehandelte Zahnfleischentzündung und unzureichende Mundhygiene sind die vorrangigen Hindernisse; eine Restauration wird erst geplant, wenn diese Probleme gelöst sind. Wo die Lastverteilung gestört ist — schwerer Bruxismus, ein tiefer Biss oder kieferorthopädisch nicht korrigierter Engstand —, schlägt die Zahnärztin oder der Zahnarzt andere Lösungen vor. Bei Zähnen mit deutlich reduziertem Schmelz, großflächigen Füllungen oder nach Wurzelbehandlung spröde gewordener Substanz reicht die Klebefläche womöglich nicht aus. Bei jungen Menschen mit unabgeschlossenem Wachstum wird der Eingriff verschoben, weil sich der Zahnfleischrand noch verändert; bei Patienten mit kieferorthopädischem Plan wird zuerst die Zahnstellung korrigiert." },
    { q: "Worauf sollten Sie achten, wie wird gepflegt?", a: "Leichte Empfindlichkeit in den ersten Tagen ist normal und legt sich meist schnell. Hartschaliges mit den Frontzähnen abbeißen, Eis kauen, auf Stiften oder Nägeln beißen — solche Gewohnheiten strapazieren die Restauration. Zweimal täglich mit einer nicht abrasiven Zahnpasta putzen und die Zahnzwischenräume reinigen reduziert Ablagerungen am Rand. Wer nachts presst, bekommt eine Knirscherschiene empfohlen. Bei den halbjährlichen Kontrollen beurteilt die Zahnärztin oder der Zahnarzt Randschluss und Zahnfleischgesundheit; die professionelle Reinigung arbeitet mit Aufsätzen, die zur Keramikoberfläche passen." },
    { q: "Was bestimmt die Haltbarkeit?", a: "Auf der technischen Seite zählen die Präzision der Präparationsgeometrie, die Feuchtigkeitskontrolle beim Kleben und die Fertigung in der richtigen Materialstärke. Bei leuzitverstärkter Glaskeramik hat eine zu dünn gefertigte Restauration eine niedrigere Bruchschwelle — die Stärke wird deshalb von Fall zu Fall geplant. Auch ob die Klebefläche auf Schmelz oder Dentin liegt, beeinflusst die Haftkraft; Restaurationen, die im Schmelz enden, bieten der adhäsiven Befestigung die verlässlichere Grundlage. Bisstyp und Mundhygiene des Patienten bestimmen die Alltagsbelastung. Wer regelmäßig zur Kontrolle geht, erlebt in den meisten Fällen viele Jahre störungsfreien Gebrauch." }
  ],
  closing: "Empress gehört zu den Glaskeramikoptionen für ästhetische Fälle, in denen die natürliche Lichtdurchlässigkeit an erster Stelle steht; welches Material zu Ihnen passt, lässt sich erst nach einer klinischen Untersuchung planen. Wenn Sie die Optionen vergleichen oder Ihre vorhandenen Restaurationen beurteilen lassen möchten, können Sie über unsere <a href=\"/de/kontakt/\">Kontaktseite</a> einen Termin anfragen."
};
