window.ARTICLE_DE = {
  slug: "fissur-ortucu",
  title: "Fissurenversiegelung",
  category: "Kinderzahnheilkunde",
  metaDescription: "Was sind Fissurenversiegelungen und wann werden sie eingesetzt? Schutz des Sechsjahrmolaren, Ablauf, Risiken und der richtige Kontrollrhythmus.",
  lead: "Die Kauflächen der Backenzähne tragen Rillen, die zu eng und zu tief sind, als dass eine Zahnbürstenborste hineinreichen könnte. Die Fissurenversiegelung ist eine vorbeugende Behandlung, die diese Rillen mit einem fließfähigen Material auffüllt und so Bakterien- und Speiseresteinlagerung reduziert. Am häufigsten wird sie auf frisch durchgebrochenen bleibenden Backenzähnen eingesetzt.",
  faqs: [
    { q: "Was ist eine Fissurenversiegelung und was leistet sie?", a: "In der Zahnmedizin heißt die enge, tiefe Rille zwischen den Höckern der Schmelzoberfläche <em>Fissur</em>. Diese Rillen sind oft feiner als ein Haar — eine Borste kommt nicht hinein, Bakterien schon. In die Rillen wird ein kunststoff- oder glasionomerbasiertes Material eingebracht; Kunststoffversiegler werden mit der Polymerisationslampe ausgehärtet, manche Glasionomer-Varianten härten von selbst. Die Fläche bleibt flacher zurück und lässt sich mit der Bürste leichter sauber halten. Die Idee: den Risikobereich physisch abriegeln, bevor die Karies eine Chance hat zu beginnen." },
    { q: "Bei wem wird sie eingesetzt und in welchem Alter?", a: "Bei Kindern ist das erste Ziel meist der Sechsjahrmolar. Dieser Zahn bricht um das sechste Lebensjahr ganz hinten durch, ohne dass vorher ein Milchzahn ausfällt — viele Eltern halten ihn für einen Milchzahn und schieben die Kontrolle auf. Der richtige Zeitpunkt zum Versiegeln ist, sobald der Zahn vollständig durchgebrochen ist und sich trocken und speichelfrei halten lässt. Dasselbe Timing-Prinzip gilt für die zweiten bleibenden Backenzähne, die um das zwölfte Lebensjahr durchbrechen. Ein paar Monate zu warten, solange ein Zahn erst teilweise durch ist, senkt das Risiko, eine Versiegelung zu legen, die bald erneuert werden muss. Der Termin wird um Essgewohnheiten und Putz-Mitarbeit des Kindes herum geplant." },
    { q: "Welche Schritte umfasst die Anwendung?", a: "Zuerst wird der Zahn mit rotierendem Bürstchen und Paste gereinigt, dann mit Watterollen vom Speichel isoliert. Anschließend kommt ein Ätzgel auf die Fläche — es erzeugt mikroskopische Rauheit am Schmelz, die dem Material Halt gibt. Nach Spülen und Trocknen wird der Versiegler in die Rillen geflossen, mit Luft verteilt und je nach Material mit der Lampe ausgehärtet. Zum Schluss wird der Biss geprüft und eine zu hohe Stelle mit dem Fräser geglättet. Der ganze Ablauf kommt <em>ohne Beschleifen des Zahns</em> aus, und die meisten Kinder brauchen dafür keine Betäubung." },
    { q: "Wie lange dauert es und was spürt das Kind dabei?", a: "Mehrere Zähne in einem Besuch zu versiegeln dauert meist rund fünfzehn bis zwanzig Minuten. Weil der Eingriff selbst nichts am Zahn schneidet, brauchen die meisten Kinder keine Betäubung — was ihnen vor allem auffällt, ist der leicht saure Geschmack des Ätzgels. Muss der Biss angepasst werden, hören sie kurz das Geräusch des Winkelstücks. Manche Kinder finden die Watte der Trockenlegung etwas unbequem." },
    { q: "Was ist der Unterschied zwischen Füllung und Fissurenversiegelung?", a: "Die beiden Eingriffe setzen an unterschiedlichen Punkten an. Die Fissurenversiegelung deckt eine gesunde Fläche ab, bevor ein Loch entstanden ist — Zahnsubstanz wird nicht entfernt. Die <strong>Füllung</strong> verlangt dagegen das Ausräumen kariösen Gewebes und das Ausformen des entstandenen Raums — sie dient also einer anderen Indikation. Sitzt am Rillengrund eine begrenzte Karies, kann minimal präpariert und dann versiegelt werden — die sogenannte erweiterte Fissurenversiegelung. Kurz: Die Versiegelung ist vorbeugend, die <a href=\"/de/hizmet/dolgu/\">Füllung</a> restaurativ." },
    { q: "Welche Risiken und möglichen Nachteile haben Fissurenversiegelungen?", a: "Der teilweise oder vollständige Materialverlust mit der Zeit ist das häufigste Problem — und nicht selten. Kinder bemerken eine verlorene Versiegelung meist nicht, denn sie erzeugt kein deutliches Gefühl; ans Licht kommt es in der Regel erst bei der Routinekontrolle. Eine teilweise verlorene Versiegelung kann eine raue Kante hinterlassen, an der sich Plaque stärker sammelt. Bleibt der Bereich unter einem verlorenen Stück unbeobachtet, kann darunter unbemerkt Karies fortschreiten. Arbeiten im feuchten Feld schwächt die Haftung — die Versiegelung löst sich dann früher. Etwas zu hoch gebliebenes Material kann beim Kauen stören, und das Kind meidet womöglich diese Seite. Sitzt darunter unentdeckte Karies, deckt die Versiegelung sie schlicht ab, und das Problem wird eine Weile still — deshalb wird bei verdächtig wirkender Rille zuerst ein Röntgenbild angefertigt. Eine ausgeprägte Empfindlichkeit auf kunststoffbasierte Materialien ist sehr selten — nennen Sie eine bekannte Allergie aber unbedingt." },
    { q: "Wann wird sie nicht eingesetzt oder verschoben?", a: "Hat die Karies am Rillengrund bereits das Dentin erreicht, ist eine Versiegelung keine geeignete Option mehr — für diesen Zahn wird eine restaurative Behandlung geplant. Bei erst halb durchgebrochenen Zähnen, deren hinterer Teil noch unter dem Zahnfleisch liegt, gelingt die Trockenlegung nicht — dann wird gewartet, bis der Zahn ganz durch ist. Auf sehr flachen, fast ebenen Rillen bringt eine Versiegelung nur begrenzten Zusatznutzen. Bei kleinen Kindern mit starkem Würgereiz oder kurzer Mundöffnungsausdauer kann der Termin nach hinten rutschen. Auf einen Zahn, für den in naher Zukunft eine <a href=\"/de/hizmet/kanal-tedavisi/\">Wurzelbehandlung</a> oder Entfernung ansteht, kommt ebenfalls keine Versiegelung. Bei aktiver Zahnfleischentzündung wird zuerst diese behandelt." },
    { q: "Was bestimmt die Haltbarkeit?", a: "Kein einzelner Faktor entscheidet das. Die Qualität der Trockenlegung beim Legen, die Kaukraft des Kindes, eine etwaige Pressgewohnheit und die Rillentiefe wirken zusammen. In den meisten Fällen bleibt eine Versiegelung einige Jahre an ihrem Platz — weil die Oberflächenabnutzung aber langsam voranschreitet, gehört sie bei jedem Besuch per Blick kontrolliert. Gewohnheiten wie das Beißen auf harte Bonbons, Eis oder Stifte nutzen das Material früher ab. Bei jeder Kontrolle fährt die Sonde über die Fläche; ausgedünnte Bereiche werden aufgefüllt oder die Versiegelung wird bei Bedarf komplett erneuert. Die Erneuerung folgt weitgehend denselben Schritten wie die Erstanwendung." },
    { q: "Worauf sollten Sie danach achten?", a: "Das Kind kann noch am selben Tag normal essen — das Material ist beim Verlassen des Stuhls vollständig ausgehärtet und einsatzbereit. In den ersten Tagen schützt es das Material, klebrige Dinge wie Kaugummi und Gummibonbons zu begrenzen. Die Putzgewohnheiten müssen sich nicht ändern; auch mit versiegelter Rille brauchen die Seitenflächen und der Zahnfleischsaum weiter Pflege. Bei den halbjährlichen Kontrollen werden der Zustand der Versiegelung und der Bedarf an einer <a href=\"/de/hizmet/dis-tasi-temizligi/\">professionellen Zahnreinigung</a> gleichermaßen geprüft. Bei Kindern mit höherem Kariesrisiko kann sie zusammen mit der <a href=\"/de/hizmet/fluorid-uygulamasi/\">Fluoridierung</a> geplant werden." },
    { q: "Auf welchen Zähnen wird sie eingesetzt — auch auf Milchzähnen?", a: "Vorrang haben die hinteren Backenzähne mit ihren breiten, zerfurchten Kauflächen. Das Rillenmuster der unteren Backenzähne ist tendenziell komplexer und wird gesondert beurteilt. In manchen Fällen werden auch die Prämolaren und die Grübchen auf der Gaumenseite der oberen Schneidezähne versiegelt. Milchbackenzähne mit tiefen Rillen sind nicht ausgenommen — auch sie können versiegelt werden, abgewogen gegen die erwartete Verweildauer des Zahns im Mund und die Karieshistorie des Kindes. Der Plan ändert sich bei früh verlorenen Milchbackenzähnen: Dort hat der <a href=\"/de/hizmet/yer-tutucu/\">Lückenhalter</a> Vorrang, um den Platz zu sichern. Die glatten Flächen der Frontzähne liegen außerhalb dieser Behandlung." },
    { q: "Nimmt eine Fissurenversiegelung das Kariesrisiko allein weg?", a: "Nein — die Versiegelung wirkt nur auf der Fläche, die sie bedeckt. Die Kontaktpunkte zwischen den Zähnen, der Zahnfleischsaum und die Frontzähne bleiben außerhalb dieses Schutzes. Rutscht bei einem Kind mit Versiegelung der Putzstandard ab oder wird zuckriges Naschen häufiger, kann auf den nicht abgedeckten Flächen weiterhin neue Karies entstehen. Ein ganz anderes Bild zeigt sich bei Babys, die noch mit dem Fläschchen einschlafen — das behandeln wir gesondert auf unserer Seite zur <a href=\"/de/hizmet/biberon-curugu/\">Nuckelflaschenkaries</a>. Das Kariesrisiko sinkt durch das Zusammenspiel mehrerer Faktoren: Mahlzeiten und Snacks mit Abstand, zweimal täglich Putzen mit Fluoridzahnpasta und regelmäßige Kontrollen. Bei Kindern mit schiefer Zahnstellung werden mehr Flächen für die Bürste unerreichbar — dann kann auch eine Beurteilung in der <a href=\"/de/hizmet/cocuk-ortodontisi/\">Kieferorthopädie für Kinder</a> Teil des Plans sein." }
  ],
  closing: "Auf dem richtigen Zahn zum richtigen Zeitpunkt gelegt, ist die Fissurenversiegelung ein kleiner Schritt, der die Kariesvorsorge Ihres Kindes stützt — sie braucht nur regelmäßige Kontrollen, um weiterzuwirken. Ob die Backenzähne Ihres Kindes dafür geeignet sind, klärt ein Kontrolltermin; Ihre Fragen erreichen uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
