window.ARTICLE_DE = {
  slug: "invisalign",
  title: "Invisalign",
  category: "Kieferorthopädie",
  metaDescription: "Invisalign: wie das Aligner-System arbeitet, digitale Planung, Attachments, tägliche Tragezeit, Schienenhygiene und die Risiken, die Sie kennen sollten.",
  lead: "Invisalign ist ein kieferorthopädisches System, bei dem die Zahnbewegung am Computer geplant und mit einer Serie durchsichtiger Schienen umgesetzt wird, die nacheinander getragen werden. Das Grundprinzip ist einfach: Jede Schiene rückt den Zahn einen kleinen Schritt näher an seine Zielposition. Das Ergebnis hängt vor allem davon ab, wie viele Stunden am Tag die Schienen tatsächlich getragen werden.",
  faqs: [
    { q: "Was ist Invisalign und wie funktioniert das System eigentlich?", a: "Was hinter dem Namen zählt, ist der Prozess: ein Intraoralscan, eine dreidimensionale Planung und eine passgenau gefertigte Schienenserie. Die Kieferorthopädie scannt die Ausgangsposition Ihrer Zähne, legt die Zielposition digital fest und zerlegt die Strecke dazwischen in Dutzende kleiner Zwischenschritte. Das Fertigungszentrum produziert dann für jeden Schritt eine eigene thermoplastische Schiene. Während Sie die Schienen der Reihe nach durcharbeiten, wandern Ihre Zähne schrittweise Richtung geplanter Position. Die allgemeinen Prinzipien des Aligner-Ansatzes finden Sie auf unserer Seite zur <a href=\"/de/hizmet/seffaf-plakla-ortodonti/\">Aligner-Therapie</a>." },
    { q: "Wie bewegt die Schiene den Zahn tatsächlich?", a: "Jede Schiene wird mit einer Geometrie gefertigt, die minimal von der aktuellen Zahnposition abweicht; sitzt sie, überträgt genau dieser kleine Unterschied eine sanfte, kontinuierliche Kraft auf den Zahn und den Knochen darum. Das Knochengewebe antwortet darauf, indem es sich auf der einen Seite abbaut und auf der anderen neu aufbaut — es formt sich allmählich um. Die Bewegung pro Schiene bleibt im Bereich von Zehntelmillimetern, denn die Kraft soll innerhalb dessen bleiben, was der Zahn sicher verträgt. Deshalb kann die Schienenzahl eines Falls je nach Komplexität in die Dutzende gehen." },
    { q: "Was passiert bei der digitalen Behandlungsplanung?", a: "Zuerst wird mit dem Intraoralscanner ein dreidimensionaler Scan Ihrer Kiefer angefertigt, ergänzt um Röntgenbilder und Fotos. Mit diesen Daten werden Zahnstellung, Biss und der nötige Platz beurteilt. Die Planungssoftware simuliert die Zahnbewegungen dann Schritt für Schritt. Wo nötig, baut die Kieferorthopädie Bogenerweiterung, minimale approximale Schmelzreduktion oder eine Extraktion in den Plan ein. Nach der Freigabe geht der Plan ans Fertigungszentrum, wo die Schienenserie passend produziert wird. Die Simulation ist ein Zielbild, keine Garantie — weil die biologische Antwort im Mund nicht bei jedem gleich schnell verläuft, kann der Plan bei den Kontrollen unterwegs angepasst werden." },
    { q: "Was ist ein Attachment und warum wird es auf den Zahn geklebt?", a: "Ein Attachment ist ein kleiner Kompositpunkt auf der Schmelzoberfläche, der der Schiene besseren Halt am Zahn gibt; gesetzt wird er in einem Termin über eine Schablone und nach Behandlungsende auf demselben Weg wieder entfernt. Für anspruchsvollere Bewegungen — Rotation, vertikales Herausbewegen oder Wurzelbewegung — sind Attachments meist unverzichtbar. Sie werden eng an Ihre Zahnfarbe angepasst, können aus der Nähe aber sichtbar bleiben und sich durch dunkle Getränke mit der Zeit verfärben. Löst sich ein Attachment, sitzt die Schiene womöglich nicht mehr richtig — sofort in der Praxis Bescheid zu geben vermeidet Verzögerungen." },
    { q: "Für wen ist Invisalign eine geeignete Option?", a: "Leichter bis mittlerer Engstand, Lücken zwischen den Zähnen und ein leichter Rückfall nach früherer kieferorthopädischer Behandlung sind die häufigsten Einsatzgebiete des Systems. Erwachsene, die den Anblick von Metallbrackets vermeiden möchten, und Berufstätige mit viel Präsentations- und Meetingzeit neigen oft zur Schienenoption. Es gibt auch Systemvarianten für Kinder und Jugendliche — Wachstumsrichtung und der Zustand der Milchzähne brauchen in diesen Altersgruppen aber eine eigene Beurteilung. Wenn Sie Ihrem Anliegen einen Namen geben möchten, helfen unsere Seiten <a href=\"/de/hizmet/dislerim-yamuk/\">Meine Zähne sind schief</a> und <a href=\"/de/hizmet/dislerim-ayrik/\">Lücken zwischen den Zähnen</a> bei der Orientierung." },
    { q: "In welchen Fällen reicht es allein womöglich nicht?", a: "Aligner bewegen Zähne. Sie lassen den Kiefer nicht wachsen und verändern die Position des Kieferknochens nicht. Bei fortgeschrittenen skelettalen Bissproblemen und deutlichen Kieferfehlstellungen erreicht das System das Ziel allein womöglich nicht. Dann wird die Kieferorthopädie zusammen mit einer Kieferoperation geplant. Auch das parallele Bewegen von Wurzeln über lange Strecken, das Einordnen eines retinierten Zahns in den Bogen und das Aufrichten stark rotierter Prämolaren gehören zu den Bewegungen, mit denen Schienen ringen. In manchen Fällen werden der Schienenbehandlung kurzzeitig Brackets oder Minischrauben-Verankerung zur Seite gestellt. Die chirurgische Seite der Kieferrelation behandelt unsere Seite zur <a href=\"/de/hizmet/ortognatik-cerrahi/\">Umstellungsosteotomie (Kiefer-OP)</a>." },
    { q: "Wann wird nicht behandelt oder verschoben?", a: "Bei aktiver Karies, unbehandelter Zahnfleischentzündung oder starkem Zahnsteinbefund beginnt die Kieferorthopädie nicht sofort. Diese Themen werden zuerst gelöst, erst dann startet der Scan. Bei Parodontalerkrankung mit fortgeschrittenem Knochenabbau wird der ganze Plan neu durchdacht, denn Zahnbewegung könnte weiteren Haltverlust verursachen. Für Patienten, die von vornherein sagen, dass sie die Tragestunden nicht schaffen, kann ein festsitzendes System die realistischere Option sein. Unkontrollierte Allgemeinerkrankungen, bestimmte Medikamente mit Wirkung auf den Knochenstoffwechsel und schweres nächtliches Knirschen können den Behandlungsstart ebenfalls verschieben. Die <a href=\"/de/hizmet/dis-tasi-temizligi/\">professionelle Zahnreinigung</a> ist in den meisten Plänen der erste Schritt." },
    { q: "Wie viele Stunden am Tag müssen die Schienen getragen werden?", a: "Die Schienen sollen rund <strong>20 bis 22 Stunden am Tag</strong> im Mund bleiben — jede Stunde außer Essen und Zähneputzen zählt dazu. Wird diese Zeit unterschritten, gerät die Passung zwischen Zahn und Schiene aus dem Takt, und die nächste in der Serie sitzt nicht mehr richtig. Wochen mit rutschender Tragezeit ziehen den Gesamtzeitplan in die Länge und bedeuten manchmal, dass eine zusätzliche Schienenserie gefertigt werden muss. An Tagen mit kürzerer Tragezeit wird das Wiedereinsetzen spürbar schwerer, und der Druck der ersten Stunden fällt intensiver aus. Die Schiene beim Herausnehmen direkt in ihre Box zu legen — statt sie in eine Serviette zu wickeln — senkt die Zahl der Verluste deutlich." },
    { q: "Wie oft werden die Schienen gewechselt und wie laufen die Kontrollen?", a: "In den meisten Plänen wird jede Schiene zwischen sieben und vierzehn Tagen getragen. Auf die nächste wechseln Sie selbst, zu Hause; in die Praxis kommen Sie meist alle sechs bis zehn Wochen. Bei diesen Terminen wird geprüft, ob die Attachments noch sitzen und das Zahnfleisch gesund ist. Neue Schienensätze werden nach Bedarf ausgehändigt, scharfe Kanten werden geglättet. Der Wechsel auf eine neue Schiene am Abend macht es leichter, den anfänglichen Druck zu verschlafen. Wer mit eingesetzten Schienen zur Kontrolle kommt, lässt die Passung direkt beurteilen." },
    { q: "Wie lange dauert eine Invisalign-Behandlung?", a: "Die Behandlungsdauer hängt davon ab, wie viele Zähne sich bewegen müssen und um welchen Bewegungstyp es geht. Begrenzte Korrekturen können in wenigen Monaten fertig sein, während Fälle mit vollständiger Bisskorrektur über ein Jahr hinauslaufen können. Mehr Attachments und mehr Zähne mit nötiger Wurzelbewegung erhöhen die Schienenzahl — und damit den Zeitplan. Laufen Ober- und Unterkiefer unterschiedlich schnell, kann sich das Enddatum verschieben. Der digitale Plan nach Ihrem Scan nennt den erwarteten Zeitrahmen samt Schienenzahl." },
    { q: "Welche Risiken und Nachteile gibt es?", a: "In den ersten Tagen nach dem Wechsel auf eine neue Schiene sind Druck, leichtes Unbehagen und vorübergehende Veränderungen beim Sprechen häufig. Die Schienenränder können Zunge und Wangenschleimhaut reizen; bei Bedarf wird die Kante geglättet. Um Attachments sammelt sich Plaque leichter — lässt die Reinigung nach, steigen das Risiko weißer Schmelzflecken und das Kariesrisiko. Eine gewisse Verkürzung der Wurzelspitzen ist bei jeder kieferorthopädischen Behandlung möglich; meist bleibt die klinische Bedeutung begrenzt, doch die eingetretene Verkürzung ist dauerhaft — bei Patienten mit höherem Risiko wird das Bewegungsausmaß deshalb begrenzt. In manchen Fällen können auch Zahnfleischrückgang, eine unerwartete Lücke im Biss oder eine nicht vollständig erreichte geplante Bewegung auftreten. Dass sich die Schiene herausnehmen lässt, sieht nach einem Vorteil aus — bei Patienten, denen die nötige Disziplin schwerfällt, wird es zum ernsten Nachteil. Auch der Ersatz verlorener oder gebrochener Schienen kostet Zeit. In dieser Situation sehen die meisten Pläne vor, zur vorherigen Schiene zurückzukehren und die Praxis noch am selben Tag zu informieren. Bei schwerem Knirschen nutzen sich die Schienen schnell durch — mehr dazu auf unserer Seite zum <a href=\"/de/hizmet/dislerimi-sikiyorum/\">Zähnepressen</a>." },
    { q: "Was gehört zur Schienenhygiene?", a: "Die Grundregel: die Schienen bei jedem Herausnehmen mit lauwarmem Wasser abspülen und mit einer weichen Bürste sanft reinigen; keine Zahnpasta verwenden — ihre Schleifkörper zerkratzen die Oberfläche. Von heißem Wasser fernhalten, denn das thermoplastische Material kann sich unter Hitze verziehen, und gefärbte Mundspülungen können die Oberfläche trüb wirken lassen. Mit der Zeit bildet sich innen ein weißlicher Film aus Speichel und Mineralablagerungen; vom Hersteller freigegebene Reinigungstabletten ein paarmal pro Woche reduzieren Belag und den Geruch, der damit einhergeht. Die Box regelmäßig mit Seifenwasser zu waschen verhindert den feuchten Film in ihrem Inneren." },
    { q: "Was passiert, wenn eine Schiene nicht richtig sitzt?", a: "Im Plan zu bleiben heißt: Die Bewegung in Ihrem Mund hält Schritt mit der Planung. Zeichen, dass etwas aus dem Takt geraten ist: Die Attachment-Mulden füllen sich nicht vollständig, die Schiene hebt an den hinteren Backenzähnen ab, oder sie sitzt ohne Nachdrücken nicht ganz. Bei kleinen Abweichungen wird die aktuelle Schiene länger getragen und mit einem Chewie zum Setzen gebracht. Ist die Lücke größer, wird neu gescannt und für die restlichen Bewegungen eine Zusatzserie geplant. Die Gewohnheit, die das Tracking am ehesten kippt: mit eingesetzten Schienen essen — für alles außer Wasser kommen sie heraus. Gefärbte Getränke wie Tee, Kaffee oder Cola mit Schiene trinken verfärbt die Oberfläche und sperrt den Zucker am Zahn ein. Wenn Sie nach dem Essen nicht putzen können, ist gründliches Ausspülen vor dem Wiedereinsetzen die nächstbeste Option." },
    { q: "Warum braucht es nach der Behandlung eine Retention?", a: "Sind die Zähne in ihre neue Position gewandert, neigen sie dazu zurückzudriften, bis sich Bänder und Knochen ringsum vollständig angepasst haben. Deshalb wird direkt nach Behandlungsende ein Retainer empfohlen — oder ein dünner, an die Zahnrückseiten geklebter Draht. Anfangs wird der Retainer ganztags getragen; in späteren Monaten meist nur noch nachts. Wer den Retainer weglässt, kann in den Folgejahren leichten Engstand zurückkehren sehen. Den klassischen Ansatz mit festsitzenden Apparaturen finden Sie auf unserer Seite zur <a href=\"/de/hizmet/dis-teli/\">Zahnspange</a> — und bei Fragen rund ums Wohlfühlen mit dem eigenen Lächeln hilft unsere Seite <a href=\"/de/hizmet/gulerken-rahat-hissetmiyorum/\">Ich fühle mich beim Lächeln nicht wohl</a>." }
  ],
  closing: "In den richtigen Fällen ist Invisalign eines der Systeme, mit denen sich kieferorthopädische Ziele mit durchsichtigen Schienen erreichen lassen — doch neben der Genauigkeit des Plans entscheidet Ihr tägliches Tragen über das Ergebnis. Wenn wir Ihre Zähne beurteilen und die passenden Optionen durchsprechen sollen, erreichen Sie uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
