window.ARTICLE_DE = {
  slug: "kaplama",
  title: "Zahnkronen",
  category: "Allgemeine Behandlungen",
  metaDescription: "Was ist eine Zahnkrone, welche Arten gibt es? Materialwahl, Behandlungsschritte, mögliche Risiken und Pflege — klar und praxisnah erklärt.",
  lead: "Krone ist der Oberbegriff für festsitzende Restaurationen, die auf einen beschädigten Zahn oder einen Zahn mit Änderungswunsch zementiert werden — von der vollständig umfassenden Kappe bis zur dünneren, auf die Vorderfläche geklebten Veneer-Variante. Darunter versammelt sich eine breite Materialpalette, von Zirkon und Glaskeramik bis zu Keramik- und Komposit-Veneers. Diese Seite zeichnet das Gesamtbild der Kronenbehandlung: die Schritte, die alle Typen teilen, und die Faktoren, die die richtige Option für Sie bestimmen.",
  faqs: [
    { q: "Was ist eine Krone und wozu dient sie?", a: "Eine <strong>Krone</strong> ist eine Restauration, die für einen Zahn mit erheblichem Substanzverlust oder Änderungswunsch vorbereitet und auf ihn aufgesetzt wird — je nach Typ als vollständige Kappe oder als dünnere Schale. Die verbliebene Zahnsubstanz wird auf eine festgelegte Stärke präpariert, die Restauration selbst entsteht im Dentallabor aus dem gewählten Material. Das Ziel ist eine Form, die das normale Kauen trägt und sich in die Nachbarzähne einfügt. Ins Bild kommt die Krone, wenn ein Zahn auf seiner eigenen Substanz nicht mehr stehen kann oder der Schaden zu groß ist, als dass eine Füllung ihn tragen könnte. Die technischen Details jedes Materials stehen auf seiner eigenen Seite." },
    { q: "Welche Kronenarten gibt es?", a: "In der Praxis sind mehrere Materialfamilien im Einsatz: <a href=\"/de/hizmet/zirkonyum/\">zirkonbasierte Kronen</a> und die Ein-Block-Option <a href=\"/de/hizmet/monolitik-zirkonyum/\">monolithisches Zirkon</a>, <a href=\"/de/hizmet/emax/\">E.max</a>- und <a href=\"/de/hizmet/empress/\">Empress</a>-Restaurationen aus der <a href=\"/de/hizmet/cam-seramik/\">Glaskeramik</a>-Familie, als dünne Schalen für die Frontzähne gefertigte <a href=\"/de/hizmet/porselen-lamina/\">Keramik-Veneers</a>, direkt im Mund aufgebaute <a href=\"/de/hizmet/kompozit-lamina/\">Komposit-Veneers</a> sowie metallgestützte <a href=\"/de/hizmet/porselen-kron-kopru/\">Kronen- und Brückenarbeiten</a>. Jede Familie hat ihren eigenen Lichtdurchlass, ihre eigene Bruchfestigkeit und ihre eigenen Anforderungen an das Beschleifen." },
    { q: "Für wen ist sie geeignet?", a: "Die Entscheidung entsteht aus dem Abwägen der verbliebenen natürlichen Substanz gegen das, was Sie erreichen möchten. Die Vollkrone ist meist die Wahl für frakturierte, stark abgenutzte oder nach Wurzelbehandlung zerbrechlich gewordene Zähne; dünnere Restaurationen kommen eher bei Verfärbungen zum Einsatz, die das Bleaching nicht gelöst hat, oder bei Frontzähnen mit abweichender Größe oder Form. Bei begrenztem Substanzverlust werden zuerst konservativere Optionen wie Füllung oder Inlay/Onlay geprüft. Behandelt wird erst, wenn die Zahnfleischgesundheit unter Kontrolle und etwaige Karies versorgt ist. Eine Krone kann auf einem einzelnen Zahn sitzen oder über mehrere Zähne der Lachlinie geplant werden; wie viele Zähne versorgt werden, richtet sich nach Symmetrie und Farbabstimmung." },
    { q: "Was ist der Unterschied zwischen Krone und Veneer?", a: "Die beiden Ansätze unterscheiden sich darin, wie viel vom Zahn sie bedecken. Die Krone umfasst den Zahn ringsum einschließlich der Kaufläche — entsprechend größer ist die zu präparierende Fläche. Das Veneer bedeckt im Allgemeinen nur die sichtbare Vorderfläche mit einer dünnen Schicht und braucht deutlich weniger Abtrag. Was richtig ist, hängt von der verbliebenen gesunden Substanz, vom Zusammentreffen der Zähne beim Biss und vom angestrebten Bild ab. Die beiden sind keine austauschbaren Alternativen — sie beantworten unterschiedliche klinische Bedürfnisse." },
    { q: "Welche Schritte umfasst die Behandlung?", a: "Am Anfang stehen Untersuchung, Röntgenbilder und, wo nötig, digitale Planung. Vor dem Beschleifen wird der Bereich örtlich betäubt — während des Eingriffs sollten Sie also keinen Schmerz spüren, auch wenn die Taubheit selbst einige Stunden anhalten kann. Dann wird der Zahn je nach gewähltem Restaurationstyp auf eine festgelegte Stärke präpariert und mit Intraoralscanner oder klassischer Methode abgeformt. Während die Restauration im Labor entsteht, trägt der Zahn ein Provisorium — es schützt ihn und lässt Sie die Form zwischenzeitlich erproben. Ist die endgültige Restauration fertig, wird sie einprobiert; Kontaktpunkte und Biss werden einzeln geprüft. Stimmt der Sitz, wird zementiert und der Zementüberschuss entfernt. In umfangreicherer ästhetischer Planung sitzt dieser ganze Ablauf innerhalb eines größeren <a href=\"/de/hizmet/gulus-tasarimi/\">Smile-Design</a>-Plans." },
    { q: "Wie lange dauert es und wie viele Termine braucht es?", a: "Für einen einzelnen Zahn sind Präparation und Abformung meist in einem Termin abgeschlossen; ein zweiter Termin gehört dem Einzementieren der endgültigen Restauration. Die Laborarbeit dazwischen dauert typischerweise einige Werktage. Umfasst die Behandlung mehrere Zähne, kommen zusätzliche Einprobetermine dazu, was den Gesamtzeitraum verlängert. Wo eine hauseigene digitale Fertigung vorhanden ist, lassen sich manche Fälle schneller abschließen." },
    { q: "Was bestimmt die Materialwahl?", a: "Die Wahl liegt am Schnittpunkt mehrerer Faktoren. Die Position des Zahns im Mund wiegt schwer: Vorn hat der Lichtdurchlass Vorrang, hinten die Widerstandskraft gegen die Kaukraft. Menge und Farbton der Restsubstanz, das Bild der Nachbarzähne, nächtliches Pressen oder Knirschen und eine etwaige Metallallergie fließen alle in die Beurteilung ein. Auch ob eine Brücke geplant ist, engt die Auswahl geeigneter Materialien ein. Kein Material liegt auf ganzer Linie vorn — jede Familie hat ihr eigenes Festigkeits- und Ästhetikprofil. Um Festigkeit und Erscheinungsbild der Gruppen nebeneinander zu vergleichen, lohnt der Blick auf unsere Seite zum <a href=\"/de/hizmet/kaplama-materyalleri-karsilastirma/\">Kronen- und Veneer-Materialvergleich</a>." },
    { q: "Geht eine Krone auch ohne Beschleifen des Zahns?", a: "In manchen Fällen lässt sich der Abtrag auf ein Minimum begrenzen. Ist der Zahn von Natur aus klein oder besteht eine Lücke, kann manchmal eine dünne Schalenrestauration fast ohne Beschleifen geplant werden. Steht der Zahn aber weiter vorn als seine Nachbarn oder muss eine dunkle Verfärbung abgedeckt werden, muss ein gewisser Raum geschaffen werden. Eine Restauration, die ohne ausreichenden Platz zementiert wird, kann klobig wirken und das Zahnfleisch reizen. Wie viel Präparation nötig ist, entscheidet sich in der Planungsphase — nicht erst bei der Einprobe. Die Details zu den Präparationsschwellen behandelt unsere Seite zu den <a href=\"/de/hizmet/porselen-lamina/\">Keramik-Veneers</a>." },
    { q: "Was sind die wichtigsten Vorteile dieser Behandlung?", a: "Auf einem Zahn mit erheblichem Substanzverlust will die Krone das Frakturrisiko senken, indem sie das Verbliebene umfasst und stützt. Weil die Kaufläche neu geformt wird, lässt sich der Kontakt zu den Gegenzähnen auf ausgeglichenerer Basis wiederherstellen. Bei abweichender Farbe, Größe oder Stellung ist das Ziel ein stimmigeres Gesamtbild. Eine gut polierte Keramikoberfläche bleibt glatt und nimmt Verfärbungen deutlich schlechter auf. Fehlt ein Zahn, entstehen mit derselben Technik Brückenlösungen, die sich auf die Nachbarzähne stützen. Der Komfort beim Sprechen und Lächeln verbessert sich in den meisten Fällen." },
    { q: "Welche Risiken und möglichen Nachteile gibt es?", a: "Die Krone ist eine unumkehrbare Behandlung — die beim Präparieren entfernte Substanz wächst nicht nach. Heiß-Kalt-Empfindlichkeit ist in den ersten Tagen häufig und legt sich meist; ist aber das Nervgewebe betroffen, kann eine Wurzelbehandlung ins Bild kommen. Sitzt der Rand nicht sauber, sammelt sich dort Plaque, das Zahnfleisch kann sich entzünden, und darunter kann mit der Zeit Karies beginnen. Keramikrestaurationen tragen ein gewisses Risiko für Absplitterung oder Fraktur — bei nächtlichem Pressen oder Knirschen steigt es deutlich. Ein minimal zu hoch gebliebener Bisskontakt kann Kiefergelenk und Kaumuskulatur belasten. Selten versagt der Zement, und die Restauration lockert sich. Auch das Entfernen einer verbrauchten Krone kostet weitere Zahnsubstanz. Sorgfältige Planung und regelmäßige Kontrollen senken diese Risiken, ganz ausschließen lässt sich keines — deshalb gehören die möglichen Ausgänge vor der Entscheidung ausführlich besprochen." },
    { q: "Wann wird sie nicht gemacht oder verschoben?", a: "Bei aktiver Zahnfleischentzündung, fortgeschrittenem Knochenabbau oder unbehandelter Karies wird zuerst behandelt und die Restaurationsphase zurückgestellt. Zeigt sich an der Wurzelspitze ein Entzündungsherd, wird erst nach abgeschlossener endodontischer Behandlung abgeformt. Bleibt zu wenig Substanz, um eine Restauration zu tragen, werden andere Lösungen erwogen. Bei jungen Menschen mit noch wachsendem Kiefer und Gebiss werden dauerhafte Restaurationen aus ästhetischen Gründen in der Regel verschoben. Unkontrolliertes Pressen, nicht aufrechtzuerhaltende Mundhygiene und die aktive Phase mancher Allgemeinerkrankungen verändern das Timing ebenfalls. In der Schwangerschaft werden nicht dringliche Eingriffe meist auf einen passenderen Zeitpunkt verschoben." },
    { q: "Ist Empfindlichkeit nach der Krone zu erwarten?", a: "Weil beim Präparieren Dentinfläche freigelegt wird, können Sie in den ersten Tagen auf Temperaturwechsel empfindlich reagieren. Lauwarme Getränke erleichtern diese Phase. Spüren Sie beim Zubeißen an einem bestimmten Punkt einen scharfen Druck, lässt sich die Bisshöhe in wenigen Minuten anpassen. Melden Sie sich ohne Verzögerung, wenn Sie pochenden Schmerz bemerken, der länger als ein paar Wochen anhält, nachts zunimmt oder auf Schmerzmittel nicht anspricht — Schwellung oder ein Lockerungsgefühl am Zahnfleischrand gehören genauso gemeldet." },
    { q: "Worauf achten — und wie pflegt man eine Krone?", a: "Die Putzgewohnheiten ändern sich für überkronte Zähne nicht — zweimal täglich mit weicher Bürste bleibt Pflicht. Weil der Restaurationsrand nahe am Zahnfleischsaum sitzt, zählt die Interdentalbürste oder Zahnseide hier genauso viel. Eis kauen, Hartschaliges knacken und Nägelkauen können die Keramikoberfläche anreißen. Bei nächtlichem Pressen in der Vorgeschichte reduziert eine Schutzschiene die Last auf der Restauration. Abrasive Weißmacher-Zahnpasten werden nicht empfohlen — sie können die Politur der Keramik stumpf machen. Bei den halbjährlichen Kontrollen werden Randschluss und Zahnfleischgesundheit geprüft." },
    { q: "Was bestimmt die Haltbarkeit — und lässt sich eine Krone erneuern?", a: "Für die Verweildauer einer Restauration im Mund gibt es keine feste Zahl. Die Qualität des Randschlusses, die Stärke des Zahns darunter, die Zahnfleischgesundheit, die Verteilung der Kaukräfte und Ihre tägliche Pflege wirken alle direkt darauf ein. Bei jemandem, der mit den Zähnen presst, kann dasselbe Material früher verschleißen. Zieht sich das Zahnfleisch über die Jahre zurück, kann der Kronenrand sichtbar werden — dann steht die Erneuerung im Raum. Die verbrauchte Restauration wird aufgetrennt und entfernt, der Zahn darunter beurteilt und bei Bedarf neu präpariert. Weil jede Erneuerung weitere Substanz kostet, hat das Verlängern der Lebensdauer Ihrer bestehenden Krone immer Vorrang." }
  ],
  closing: "Ob eine Krone der richtige Schritt ist, wird klar, sobald der Zustand des Zahns und Ihre Wünsche ans eigene Lächeln gemeinsam besprochen sind. Wenn Sie wissen möchten, welche Option zu Ihnen passt, vereinbaren Sie eine Untersuchung — Ihre Fragen erreichen uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
