window.ARTICLE_DE = {
  slug: "kompozit-lamina",
  title: "Komposit-Veneers",
  category: "Ästhetische Behandlungen",
  metaDescription: "Was sind Komposit-Veneers, für wen eignen sie sich, was unterscheidet sie von Keramik-Veneers und Bonding? Ablauf, Risiken, Pflege und Haltbarkeit.",
  lead: "Komposit-Veneers gehören zu den ästhetischen Optionen bei kleineren Form-, Farb- und Lückenproblemen der Frontzähne. Weil die Zahnärztin oder der Zahnarzt das Kompositmaterial in Schichten direkt im Mund aufbaut und formt, ist die Behandlung in den meisten Fällen in einem einzigen Termin abgeschlossen. Unten finden Sie den Umfang der Behandlung, die Unterschiede zu Keramik-Veneers und Bonding, die Risiken und die Anforderungen an die Pflege.",
  faqs: [
    { q: "Was ist ein Komposit-Veneer und aus welchem Material besteht es?", a: "Ein Komposit-Veneer ist eine ästhetische Verkleidung, die aus dünnen Schichten Kompositkunststoff auf der sichtbaren Fläche der Frontzähne aufgebaut wird. Jede Schicht wird mit einer Speziallampe ausgehärtet; ein Laborschritt ist in den meisten Fällen nicht beteiligt. Farbe, Form, Länge und Oberflächentextur erreichen ihre endgültige Gestalt im selben Termin. Der Abtrag von Zahnsubstanz bleibt im Allgemeinen begrenzt, in manchen Fällen wird der Schmelz gar nicht berührt." },
    { q: "Für wen kann das infrage kommen?", a: "Dieser Ansatz kann für Menschen mit einer kleinen Absplitterung, Abnutzung, einem Haarriss, einer leichten Formunregelmäßigkeit oder einer Lücke an den Frontzähnen infrage kommen. Auch bei örtlich begrenzten Verfärbungen, die auf Bleaching nicht ansprechen, wird er erwogen. Leichte Rotationen und Längenunterschiede lassen sich bei Patienten, die keine kieferorthopädische Behandlung möchten, mit Komposit kaschieren. Bei gesundem Zahnfleisch und einer konstanten Pflegeroutine sind die Ergebnisse vorhersehbarer. Bei Patienten mit <a href=\"/de/hizmet/dislerim-ayrik/\">Lücken zwischen den Zähnen</a> nimmt die Zahnärztin oder der Zahnarzt bei der ersten Untersuchung Messungen und Fotos ab." },
    { q: "Wie läuft es ab, welche Schritte gehören dazu?", a: "Zuerst wird die Zahnoberfläche gereinigt, der Farbton bei Tageslicht gewählt und die Zielform über ein Wachsmodell oder eine digitale Planung festgelegt. Dann wird die Schmelzoberfläche angeätzt, ein Haftvermittler aufgetragen und das Komposit Schicht für Schicht aufgebaut. Jede Schicht wird mit Licht gehärtet; unterschiedliche Transluzenzstufen werden übereinandergelegt, um Dentin- und Schmelzeffekte nachzubilden. Zum Schluss wird die Form mit Fräsern verfeinert und die Oberfläche mit Polierscheiben auf Glanz gebracht. Der Termin ist erst zu Ende, wenn der Biss geprüft wurde — die Kontaktbeziehung der Frontzähne wirkt direkt auf das Frakturrisiko. Fälle, die eine umfassendere Planung brauchen, laufen im Rahmen des <a href=\"/de/hizmet/gulus-tasarimi/\">Smile Designs</a>." },
    { q: "Wie lange dauert es und wie viele Besuche braucht es?", a: "Für einen einzelnen Zahn dauert der Eingriff meist 30 bis 60 Minuten. Ist die gesamte Frontgruppe geplant, kann sich der Termin auf zwei bis drei Stunden ausdehnen; manche Fälle teilt die Praxis dem Komfort zuliebe auf zwei Besuche auf. Ohne Beschleifen wird meist keine Betäubung gebraucht; ist eine Schmelzpräparation nötig, kann örtliche Betäubung ins Spiel kommen. Da die direkte Methode ohne Abformung und Laborwartezeit auskommt, ist die Behandlung im Allgemeinen am selben Tag abgeschlossen. Für Politur und Bissfeinschliff wird ein kurzer Nachsorgetermin eingeplant." },
    { q: "Was ist der Unterschied zu Keramik-Veneers?", a: "Beide Methoden bedecken die Vorderfläche, aber Material und Prozess unterscheiden sich. Komposit wird im Mund geformt und in den meisten Fällen in einem Besuch fertig; <a href=\"/de/hizmet/porselen-lamina/\">Keramik-Veneers</a> brauchen Abformung, Laborfertigung und einen zweiten Termin fürs Kleben. Bei Keramik wird vor der Abformung ein gewisser Oberflächenabtrag vorgenommen. Was die Oberflächenaufnahme angeht, kann Komposit unter Kaffee, Zigaretten und ähnlichen Färbequellen mit der Zeit den Ton verändern, während sich die glasige Keramikoberfläche an dieser Stelle anders verhält. Andererseits lässt sich eine abgeplatzte oder abgenutzte Stelle im Komposit im selben Termin wieder aufbauen, während bei Keramik meist die ganze Restauration ersetzt werden muss. Beim Komposit plant die Praxis typischerweise häufigere Politurauffrischungen und punktuelle Reparaturen ein; bei Keramik verlangen die Kontrolltermine keine vergleichbare Oberflächenbehandlung. Beide Optionen nähern sich dem ästhetischen Ziel für die Frontzähne auf unterschiedlichen Wegen. Wer die Optionen nebeneinander sehen möchte: Unsere Seite zum <a href=\"/de/hizmet/kaplama-materyalleri-karsilastirma/\">Kronen- und Veneer-Materialvergleich</a> hilft weiter." },
    { q: "Was ist der Unterschied zwischen Bonding und Komposit-Veneers?", a: "Bonding ist eine <em>punktuelle</em> Korrektur mit demselben Kompositmaterial: Es kümmert sich um eine abgeplatzte Ecke, eine kleine Lücke oder einen begrenzten Formfehler an einem einzelnen Zahn. Beim Komposit-Veneer bedeckt die Zahnärztin oder der Zahnarzt die <strong>gesamte</strong> Vorderfläche des Zahns und arbeitet im Allgemeinen an vier bis acht Zähnen zusammen, um Symmetrie, einheitliche Länge und eine geschlossene Lachlinie aufzubauen. Der Unterschied liegt also nicht im Material, sondern in Umfang und Planung. Bei einem örtlich begrenzten Problem an einem Zahn kann <a href=\"/de/hizmet/bonding/\">Bonding</a> genügen; sollen Farbe und Form über die ganze Frontgruppe zusammenpassen, rückt der Veneer-Ansatz nach vorn." },
    { q: "Was ändert sich zwischen direkter und indirekter Anwendung?", a: "Bei der direkten Methode wird das Komposit unmittelbar im Mund geformt, was die Zahl der Besuche senkt. Bei der indirekten Methode fertigt der Techniker die Veneers im Labor, geklebt wird bei einem zweiten Termin. Im Labor unter höherer Hitze und Druck polymerisierte Komposite zeigen ein anderes Festigkeitsprofil. Vorgefertigte Komposit-Veneers kommen als fertige Schalen, die die Zahnärztin oder der Zahnarzt an den Zahn anpasst. Welcher Weg gewählt wird, zeigt sich bei der Untersuchung anhand der vorhandenen Zahnsubstanz und der angestrebten Form." },
    { q: "Welche Risiken und Nachteile gibt es?", a: "Kompositkunststoff kann mit der Zeit seinen Oberflächenglanz verlieren, und an den Rändern können dünne Verfärbungslinien erscheinen. Der Biss auf Hartes, Nägelkauen oder nächtliches Knirschen kann zu Fraktur oder Ablösung am Rand führen. Überstehende Ränder können eine Zahnfleischentzündung anstoßen — deshalb wird der Randschluss sorgfältig geprüft. Wo beschliffen wurde, wächst der verlorene Schmelz nicht nach; die Entscheidung kann also einen unumkehrbaren Schritt enthalten. Manche Patienten bemerken in den ersten Tagen Kälteempfindlichkeit, die sich meist rasch legt. Bei Patienten mit der Beschwerde des <a href=\"/de/hizmet/dislerimi-sikiyorum/\">Zähnepressens</a> wird eine langfristige Prognose ohne eingeplante Knirscherschiene schwierig." },
    { q: "Wann wird es nicht gemacht oder verschoben?", a: "Bei aktiver Karies, fortgeschrittener Zahnfleischerkrankung oder unbehandelter Wurzelkanalinfektion wird die Behandlung verschoben und zuerst das Fundament gelegt. Bei starkem Engstand, ausgeprägtem Bissproblem oder schwerer Abnutzung reicht Komposit allein womöglich nicht — dann kommt ein kieferorthopädischer oder prothetischer Plan in Betracht. Bei wurzelbehandelten, avitalen Zähnen oder tief ins Gewebe eingezogener Verfärbung deckt eine dünne Kompositschicht den darunterliegenden Ton womöglich nicht gut genug ab; hier prüft die Praxis andere Stärke- und Opazitätsoptionen. Weil das Frakturrisiko bei unkontrolliertem Bruxismus steigt, wird ohne Schutzmaßnahme nicht begonnen. Ist der Zahnverlust im Frontbereich umfangreich, werden stattdessen umfassende Versorgungen erwogen. Bei Patienten ohne gefestigte Mundhygieneroutine stehen zuerst Reinigung und Anleitung zur Pflege auf dem Plan." },
    { q: "Wie sieht die Pflege danach aus?", a: "In den ersten 24 Stunden sollten dunkle Getränke und Rauchen gemieden werden, weil die Oberfläche in dieser Zeit anfälliger für Verfärbung ist. Fürs tägliche Putzen eine nicht abrasive Zahnpasta verwenden; scharfe Weißmacher-Pasten können den Glanz stumpf machen. Hartschaliges abbeißen, Eis kauen und Verpackungen mit den Frontzähnen öffnen sind riskante Gewohnheiten. Bei der halbjährlichen Kontrolle beurteilt die Zahnärztin oder der Zahnarzt Randschluss und Zustand der Oberfläche." },
    { q: "Wie lange halten Komposit-Veneers und was bestimmt das?", a: "Die Haltbarkeit schwankt von Patient zu Patient deutlich; bei guter Pflege steht nach einigen Jahren Gebrauch meist eine Politurauffrischung oder Teilreparatur an, bei hohen Bisskräften kann es früher so weit sein. Die Hauptfaktoren sind die Konstanz Ihrer Mundpflege, der Konsum färbender Speisen und Getränke und die Frage, ob Sie nachts mit den Zähnen pressen. Auch der verwendete Komposittyp und die Schichttechnik beeinflussen, wie sich die Oberfläche über die Zeit verhält. Entwickelt sich eine Randundichtigkeit oder eine Fraktur, plant die Praxis den Ersatz." },
    { q: "Was passiert bei Verfärbung — lassen sie sich erneuern?", a: "Bei oberflächlichen Verfärbungen wird die alte Polierschicht abgedünnt und neu poliert — ein schneller Eingriff. Ist die Farbveränderung tiefer ins Komposit gewandert, wird diese Schicht entfernt und frisches Komposit ergänzt; die gesamte Restauration zu ersetzen ist meist nicht nötig. Eine abgeplatzte Ecke wird nach demselben Prinzip repariert, und genau diese <em>Reparierbarkeit</em> gehört zu den Kennzeichen der Methode. Wer den Farbton der natürlichen Zähne aufhellen möchte, plant das <a href=\"/de/hizmet/dis-beyazlatma/\">Bleaching</a> vor der Veneer-Anfertigung — Komposit reagiert nicht auf Aufhellungsmittel. Substanzverluste weiter hinten im Mund behandelt die Praxis gesondert im Rahmen der <a href=\"/de/hizmet/estetik-dolgular/\">ästhetischen Füllungen</a>." }
  ],
  closing: "Komposit-Veneers gehören zu den Optionen, die sich lohnen, wenn Sie Form- und Farbabweichungen Ihrer Frontzähne innerhalb eines einzigen Termins angehen möchten. Welche Methode zu Ihnen passt, zeigt sich, sobald Zahnsubstanz und Bissrelation untersucht sind. Bei Fragen erreichen Sie uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
