window.ARTICLE_DE = {
  slug: "ortognatik-cerrahi",
  title: "Umstellungsosteotomie (Kiefer-OP)",
  category: "Kieferorthopädie",
  metaDescription: "Umstellungsosteotomie: wer sie braucht und was die Kieferorthopädie davor und danach leistet. Zeitplan, Erholung und Risiken im Überblick.",
  lead: "Bei manchen Bissproblemen liegt die Ursache nicht in der Zahnstellung, sondern im Verhältnis von Ober- und Unterkieferknochen zueinander. Die Umstellungsosteotomie ist ein sorgfältig geplanter Prozess, der diese skelettale Abweichung gemeinsam mit der kieferorthopädischen Behandlung angeht. Unten finden Sie die Etappen, den Zeitplan, die Erholungsphase und die möglichen Risiken.",
  faqs: [
    { q: "Was ist die Umstellungsosteotomie und was soll sie korrigieren?", a: "Die Chirurgin oder der Chirurg durchtrennt den Kieferknochen entlang geplanter Linien und fixiert ihn in seiner neuen Position mit kleinen Titanplatten und Schrauben. Das Ziel ist nicht bloß gerade Zähne — verändert werden soll das Verhältnis von Ober- zu Unterkiefer. Deshalb steht der Eingriff nie für sich allein; er wird als ein Paket zusammen mit der kieferorthopädischen Behandlung geplant. Ein Biss, der nicht richtig schließt, Kauprobleme, Schwierigkeiten beim Sprechen und eine Asymmetrie der Gesichtsmittellinie sind die Hauptgründe, diesen Weg zu erwägen. <a href=\"/de/hizmet/dislerim-yamuk/\">Eng wirkende Zähne</a> sind für sich genommen kein Operationsgrund — entscheidend ist das darunterliegende Knochenverhältnis." },
    { q: "Bei wem reicht Zahnbewegung allein nicht — und die Operation kommt ins Bild?", a: "Von einer skelettalen Abweichung spricht man, wenn der Biss nicht richtig schließt, egal wie weit man die Zähne im Knochen bewegt. Häufige Beispiele dieser Gruppe: ein deutlich zurückliegender oder zu weit vorstehender Unterkiefer, ein schmaler Oberkiefer, ein offener Biss, bei dem sich die Frontzähne nie berühren, und eine einseitige Gesichtsasymmetrie. Auch die Verengung der Atemwege im Schlaf gehört zur Beurteilung; bei manchen Patienten mit <a href=\"/de/hizmet/horluyorum/\">Schnarch</a>-Beschwerde wird die Kieferposition als möglicher Faktor untersucht. Ob die Abweichung von den Zähnen oder vom Knochen kommt, klärt die Kieferorthopädie über Fernröntgenseitenbilder und CT-Messungen." },
    { q: "Warum kommt die Kieferorthopädie zuerst — wird der Biss nicht sofort besser?", a: "Die vorbereitende Kieferorthopädie kann sich zunächst widersinnig anfühlen, denn der Biss verbessert sich in dieser Phase meist nicht — er kann eine Weile sogar auffälliger wirken. Tatsächlich wird jeder Zahn auf seiner eigenen Knochenbasis in die korrekte Position gebracht, damit die Zähne beim Umstellen der Kiefer in der Operation richtig zusammenfinden. Das heißt: Die Kippung, die die Zähne über Jahre angenommen haben, um die skelettale Abweichung zu kaschieren, wird zurückgenommen — die sogenannte Dekompensation. Deshalb kann das Profil eine Zeit lang markanter wirken. In dieser Phase wird ein festsitzendes Spangensystem verwendet, denn die Operation braucht feste Ankerpunkte. Die Kontrollen laufen alle vier bis sechs Wochen weiter, und die Vorbereitung dauert in den meisten Fällen 12 bis 18 Monate." },
    { q: "Auf welche Bildgebung und Messungen stützt sich der Plan?", a: "Die Planung beginnt damit, Gesichtsfotos, CT-Daten und digitale Modellscans zusammenzuführen. Mit 3D-Software wird für jeden Kiefer Richtung und exakte Strecke in Millimetern bestimmt, dann werden die Operationssplinte gefertigt, die während des Eingriffs verwendet werden. Diese Entscheidungen treffen Kieferorthopädie und Kieferchirurgie in dieser Phase gemeinsam, denn Zahnstellung und Knochenbewegung sind direkt verknüpft. Atemweg, Lippenstütze und die Position des Kinns gehören in denselben Plan." },
    { q: "Was passiert unter Vollnarkose und wie viele Tage dauert der Klinikaufenthalt?", a: "Der Eingriff läuft unter Vollnarkose und größtenteils vom Mundinneren aus — eine sichtbare Narbe auf der Gesichtshaut ist deshalb meist nicht nötig. Die Dauer hängt davon ab, ob ein Kiefer oder beide umgestellt werden; geplant wird eine Operation von mehreren Stunden. Ist der Knochen in seiner neuen Position, wird er mit Titanplatten und Schrauben fixiert. Der Klinikaufenthalt beträgt meist zwei bis drei Tage. Das vollständige Verdrahten der Kiefer ist weit seltener als früher; in den meisten Fällen führen stattdessen Gummizüge den Biss." },
    { q: "Warum läuft die Kieferorthopädie weiter, wenn der Knochen an seinem Platz sitzt?", a: "Sobald der Knochen in seiner neuen Position steht, bleiben zwischen den Zähnen kleine Lücken und ungleichmäßige Kontakte. Diesen Feinschliff übernimmt die Kieferorthopädie nach der Operation — Ziel ist, dass sich die Bisskraft gleichmäßig über alle Zähne verteilt. Diese Phase dauert in den meisten Fällen sechs bis acht Monate und läuft mit festsitzender Spange oder, in geeigneten Fällen, mit einem <a href=\"/de/hizmet/seffaf-plakla-ortodonti/\">Aligner-System</a>. Wie konsequent die Gummizüge in dieser Phase getragen werden, wirkt direkt auf den Fortschritt." },
    { q: "Wie sieht der Gesamtzeitplan von Anfang bis Ende aus?", a: "Der Zeitplan besteht aus drei Blöcken: Kieferorthopädie vor der Operation, Operation und Erholung, dann Kieferorthopädie danach. Zusammengerechnet sind das meist rund zwei Jahre; die Größe der skelettalen Abweichung und die Ausgangsstellung der Zähne beeinflussen die Dauer. Der Großteil der Schwellung geht im ersten Monat zurück, bis sich die Gesichtskonturen vollständig gesetzt haben, können aber mehrere Monate vergehen. Die Rückkehr an den Schreibtisch oder in die Schule liegt meist zwischen zwei und vier Wochen; das Autofahren wird daran ausgerichtet, wie viel Schmerzmittel Sie noch brauchen. Körperlich fordernde Arbeit und Kontaktsport bedeuten im Allgemeinen eine längere Pause — diese Zeiträume variieren mit dem Rückgang der Schwellung und dem Erholungsverlauf. Die Knochenheilung macht in den ersten sechs Wochen deutliche Fortschritte, und in dieser frühen Phase nach der Operation liegen die Termine dichter." },
    { q: "Welche Risiken und möglichen Komplikationen gibt es?", a: "Wie jeder chirurgische Eingriff trägt auch die Umstellungsosteotomie ihre eigenen Risiken. Am häufigsten besprochen wird die Gefühlsveränderung: Taubheit an Unterlippe, Kinn und Zahnfleisch ist nach der Operation ein <em>erwarteter</em> Befund, keine Komplikation an sich. In den meisten Fällen kehrt das Gefühl binnen Wochen oder Monaten zurück, bei manchen Patienten kann es dauerhaft bleiben. Schwellung, Bluterguss und Schluckbeschwerden gehören zu den normalen ersten Wochen. Die Mundöffnung bleibt meist vier bis sechs Wochen eingeschränkt; in dieser Zeit werden die gezeigten Öffnungsübungen fortgeführt, bei Bedarf mit Physiotherapie. Die Fixierungsplatten bleiben in der Regel im Knochen; bei anhaltendem Unbehagen oder einer Infektion im Bereich lassen sie sich nach abgeschlossener Heilung mit einem kleinen Eingriff entfernen. Infektion, Blutung und — selten — die Notwendigkeit eines zweiten Eingriffs sind weitere Möglichkeiten. Bestehende Kiefergelenkbeschwerden können sich nach der Operation verändern: Bei manchen werden sie leichter, bei anderen auffälliger. Ein gewisser Rückfall Richtung Ausgangsposition kann auftreten, besonders bei größeren Bewegungen." },
    { q: "Wann wird nicht operiert oder verschoben?", a: "Vor Abschluss des Wachstums wird nicht operiert, denn ein korrigiertes Verhältnis kann sich verschieben, solange die Kiefer noch wachsen. Dass das Wachstum beendet ist, wird etwa über ein Handwurzelröntgen und die Größenverlaufskontrolle bestätigt; diese Schwelle liegt bei Mädchen und Jungen in unterschiedlichem Alter. Unkontrollierter Diabetes, Gerinnungsstörungen und schwere Herz- oder Atemwegserkrankungen können aus Narkosesicht ein Hindernis sein — ohne Stellungnahme der jeweiligen Fachrichtung wird nicht geplant. Aktive Zahnfleischentzündung und unbehandelte Karies werden zuerst gelöst, und für die Dauer des Prozesses wird um einen Rauchstopp gebeten. Für Menschen, deren Biss kein skelettales Problem hat und deren einziges Anliegen das Aussehen ist, ist diese Operation nicht angemessen. Bei noch wachsenden Kindern versucht stattdessen die <a href=\"/de/hizmet/cocuk-ortodontisi/\">Kieferorthopädie für Kinder</a>, die Kieferentwicklung zu lenken." },
    { q: "Wie sind Essen und Sprechen nach der Operation betroffen?", a: "In den ersten Tagen ist die Ernährung komplett flüssig — Suppe, Milch, fein pürierte Mischungen und Getränke decken diese Phase ab. Ab der zweiten Woche geht es zu weicher Kost über, dann schrittweise zurück zur normalen Ernährung; Hartes und schwer Kaubares bleibt meist bis etwa zur achten Woche liegen. Gewichtsverlust ist im ersten Monat häufig — Eiweiß- und Kalorienzufuhr werden deshalb mit einer Ernährungsberatung geplant. Das Sprechen kann in den ersten Wochen wegen Schwellung und verändertem Gefühl anders klingen; die Deutlichkeit kehrt bei den meisten mit der Zeit zurück. Eine weiche Zahnbürste und eine empfohlene Mundspülung erleichtern die Mundpflege in dieser Phase." },
    { q: "Lässt sich das auch ohne Operation mit Spange oder Alignern lösen?", a: "Bei grenzwertigen skelettalen Abweichungen kann es möglich sein, den Biss über die Zahnstellung auf ihrer Knochenbasis auszugleichen — die sogenannte Camouflage-Orthodontie. Sie läuft mit <a href=\"/de/hizmet/dis-teli/\">Zahnspange</a> oder Aligner-Systemen und kann in geeigneten Fällen die Operation ganz vom Tisch nehmen. Je größer die zugrunde liegende Abweichung, desto klarer zeigen sich die Grenzen der Camouflage: Zahnwurzeln können aus dem Knochenmantel gedrängt werden, das Zahnfleisch kann zurückgehen, und das Profil verändert sich nicht in die erhoffte Richtung. Die Kieferorthopädie erklärt das wahrscheinliche Ergebnis beider Optionen — entschieden wird gemeinsam, entlang Ihrer Prioritäten." },
    { q: "Hängen Kiefergelenkschmerz und Kauprobleme mit diesem Bild zusammen?", a: "Schmerz, Knacken und Blockieren im Kiefergelenk stammen nicht immer aus einer skelettalen Abweichung; Zähnepressen, Muskelverspannung und eine minimal zu hohe Füllung können ein ähnliches Bild erzeugen. Deshalb wird die Beschwerde <a href=\"/de/hizmet/cene-agrisi-yasiyorum/\">Kieferschmerzen</a> zuerst als eigenes Thema abgeklärt. Trifft der Biss nur auf wenigen Zähnen auf oder lässt sich Essen beim Kauen nicht richtig zerkleinern, kann diese Art von <a href=\"/de/hizmet/rahat-cigneyemiyorum/\">Kauproblem</a> auf eine skelettale Ursache deuten. Vor der Operation vorhandene Gelenkbeschwerden werden zu Beginn dokumentiert, und Schmerzniveau und Mundöffnung werden über den ganzen Prozess an denselben Messgrößen verfolgt." },
    { q: "Was braucht es, damit das Ergebnis hält?", a: "Die Retentionsphase ist der am leichtesten vernachlässigte Teil der Behandlung — und wirkt direkt darauf, wie gut das Ergebnis hält. Sobald die Spange abkommt, wird ein festsitzender oder herausnehmbarer Retainer eingegliedert, geplant fürs langfristige Tragen. Bei Patienten, die weiter mit den Zähnen pressen, kann eine Knirscherschiene empfohlen werden, denn übermäßige Kraft belastet Zähne und Fixierungsstelle gleichermaßen. Im ersten Jahr sind die Kontrollen häufiger. Eine gepflegte Mundhygiene hilft, den erreichten Biss langfristig stabil zu halten." }
  ],
  closing: "Die Quelle eines Bissproblems allein am Blick auf die Zahnstellung zu erkennen ist schwierig; steckt eine skelettale Abweichung dahinter, muss der Behandlungsplan von Anfang an anders gebaut werden. Die Entscheidung zur Umstellungsosteotomie gehört nicht übers Knie gebrochen — sie braucht das ausführliche Gespräch über Optionen und Gesamtzeitplan. Bei Fragen erreichen Sie uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
