window.ARTICLE_DE = {
  slug: "sinus-lifting",
  title: "Sinuslift",
  category: "Implantat-Behandlungen",
  metaDescription: "Was ist ein Sinuslift, worin unterscheiden sich offene und geschlossene Technik? Heilungsdauer, Knochenbildung und die Implantatvorbereitung im Oberkiefer.",
  lead: "Wer im hinteren Oberkiefer Implantate plant, hat dort oft nur begrenzte Knochenhöhe – der Sinuslift ist eine chirurgische Vorbereitung, die genau dieses Maß vergrößern soll. Diese Seite behandelt den Unterschied zwischen offener und geschlossener Technik, die Dauer des Eingriffs, den Heilungsfahrplan und die möglichen Risiken – jedes Thema für sich. Tippen Sie auf eine Überschrift, um die Erklärung zu öffnen.",
  faqs: [
    { q: "Was ist ein Sinuslift?", a: "Die Kieferhöhle (Sinus maxillaris) ist ein luftgefüllter Hohlraum unter dem Wangenknochen, nahe den Wurzeln der oberen Backenzähne. Die dünne Haut, die diesen Hohlraum auskleidet, heißt Schneider-Membran. Beim Eingriff wird diese Membran vorsichtig vom Boden der Kieferhöhle angehoben, und der entstandene Raum darunter wird mit Aufbaumaterial gefüllt – mit dem Ziel, den vertikalen Platz für ein Implantat zu vergrößern. Der Eingriff ist auch als Sinusbodenaugmentation bekannt. Bei einem einzelnen fehlenden Zahn ist diese Vorbereitung oft der erste Schritt im Plan für ein <a href=\"/de/hizmet/tek-dis-implant/\">Einzelzahnimplantat</a>." },
    { q: "Wann ist ein Sinuslift nötig?", a: "Nach Zahnverlust baut der Kieferknochen allmählich ab, während sich die Kieferhöhle nach unten ausdehnt – beides zusammen verengt den Raum für ein Implantat. In lange zahnlosen Bereichen schreitet der Abbau weiter fort, eine fortgeschrittene Zahnfleischerkrankung beschleunigt ihn. Bei manchen Menschen ist die Kieferhöhle von Geburt an groß und lässt von vornherein wenig Platz. Die vorhandene Knochenhöhe wird per 3D-Aufnahme millimetergenau gemessen; dieselben Bilder zeigen die Sinusanatomie, die knöchernen Trennwände im Inneren und die Dicke der Membran. Sich in dieser Region allein auf ein Panoramaröntgen zu verlassen, kann täuschen. Fehlen hinten mehrere Zähne, gehört die Planung der <a href=\"/de/hizmet/coklu-dis-koprulu-implant/\">implantatgetragenen Brücke</a> in dieselbe Beurteilung." },
    { q: "Wie läuft die offene Technik (laterales Fenster) ab?", a: "Bei dieser auch als laterales Fenster oder externer Zugang bekannten Technik wird das Zahnfleisch angehoben und in der Seitenwand des Kiefers ein kleines Fenster geöffnet. Mit feinen Handinstrumenten wird die Membran behutsam angehoben, der entstandene Raum schichtweise mit Aufbaumaterial gefüllt und die Stelle vernäht. Dieser Weg kommt in Betracht, wenn die Restknochenhöhe deutlich reduziert ist. Ist die Membran sehr dünn, kann eine schützende Barrieremembran eingelegt werden, um das Verstreuen des Materials unwahrscheinlicher zu machen. Dieser Zugang kann in manchen Fällen mehr Höhengewinn erzielen, heilt dafür aber länger. Müssen beide Seiten behandelt werden, lassen sich beide Kieferhöhlen in einer Sitzung versorgen – oder die Sitzungen werden auseinandergelegt, um Schwellung und Essbeschwerden zu begrenzen. Die Fäden werden meist nach sieben bis zehn Tagen entfernt. Mehr zu den Materialoptionen auf unserer Seite zum <a href=\"/de/hizmet/kemik-grefti/\">Knochenaufbau</a>." },
    { q: "Kann bei der geschlossenen (internen) Technik das Implantat in derselben Sitzung gesetzt werden?", a: "Dieser auch als interne oder Osteotom-Technik bekannte Zugang braucht kein eigenes Fenster: Gearbeitet wird durch das Implantatlager selbst, der Sinusboden wird von innen angehoben. Der erreichbare Hub ist begrenzt und bleibt meist bei drei bis vier Millimetern. Bevorzugt wird die Methode ab etwa fünf Millimetern Restknochenhöhe – wobei dieses Maß allein nicht als ausreichende Entscheidungsgrundlage gilt. In Bereichen geringerer Dichte wird das Lager eher verdichtet als erweitert. Da das Gewebetrauma klein bleibt, fällt die Schwellung meist milder aus. Während der Operation wird beurteilt, ob genügend Primärstabilität für die Implantation in derselben Sitzung erreicht ist; reicht sie nicht, bleibt das Implantat einer zweiten Sitzung vorbehalten. Auch bei der geschlossenen Technik kann die Membran reißen – und weil das von innen schwerer zu sehen ist, kann der Eingriff in dem Fall abgebrochen werden. Wo das Setzen in derselben Sitzung gelingt, verkürzt sich der Behandlungszeitplan. Die endgültige Wahl zwischen beiden Techniken leiten Befunde der Aufnahme und der Eindruck während der Operation gemeinsam." },
    { q: "Wie lange dauert der Eingriff, und gehen Sie am selben Tag nach Hause?", a: "Mit der geschlossenen Technik dauert die Operation meist zwanzig bis vierzig Minuten, mit der offenen bis zu einer Stunde. Örtliche Betäubung genügt in den meisten Fällen; bei stärkerer Anspannung kann die Option einer Sedierung angesprochen werden. Da ambulant operiert wird, gehen Sie am selben Tag nach Hause. Die Rückkehr an den Schreibtisch ist meist binnen weniger Tage möglich; körperlich fordernde Arbeit braucht länger Pause." },
    { q: "Wie lange dauern Heilung und Knochenneubildung?", a: "In den ersten Tagen können Schwellung, Bluterguss und etwas Nasenbluten auftreten; das legt sich meist binnen drei bis sieben Tagen. Deutlich länger dauert es, bis das Aufbaumaterial mit Ihrem eigenen Knochen verwächst. Eigenknochen integriert tendenziell schneller; Material bovinen oder synthetischen Ursprungs bildet langsamer Knochen. Bei der offenen Technik wird üblicherweise mit vier bis neun Monaten Wartezeit gerechnet. Ist sie vorbei, wird das Implantat gesetzt – und ein zweiter Prozess beginnt: Im aufgebauten Oberkiefer dauert die Verwachsung des Implantats meist vier bis sechs Monate, mitunter länger als in natürlichem Knochen. Beide Zeiträume laufen nacheinander – für die Gesamtdauer werden sie addiert. Während der Wartezeit kann der Bereich mit einem Provisorium abgedeckt werden. Allgemeinzustand, Materialtyp und Mundhygiene beeinflussen den Zeitplan. Die Knochenneubildung wird per Kontrollaufnahme überwacht – meist am Ende der Wartezeit, kurz vor dem Implantattermin." },
    { q: "Welche Behandlungsoptionen eröffnet dieser Eingriff?", a: "Erreicht ein zuvor implantatuntauglicher Bereich ausreichende Höhe, werden festsitzende Versorgungen möglich – und eine herausnehmbare Prothese ist in vielen Fällen nicht mehr nötig. Ziel ist, die Kaukraft über den hinteren Mundbereich zu verteilen. Bei umfangreicherem Zahnverlust im Oberkiefer kann auch eine <a href=\"/de/hizmet/all-on-4/\">All-on-4</a>-Planung erwogen werden, die ohne Aufbau auskommt. Fehlen etwa auf einer Seite zwei Backenzähne, kann statt einer Brücke eine feste Lösung mit zwei einzelnen Implantaten entworfen werden." },
    { q: "Welche Risiken und Komplikationen hat der Sinuslift?", a: "Wie jeder chirurgische Eingriff trägt auch dieser bestimmte Risiken. Am häufigsten ist ein Riss der Sinusmembran – mit einer Rate, die alles andere als vernachlässigbar ist. Kleine Risse lassen sich meist in derselben Sitzung versorgen; größere bedeuten Abbruch, Ausheilung und einen neuen OP-Termin einige Monate später. Möglich sind Infektionen, das Aufflammen einer Sinusitis, anhaltende Schwellung oder verstopfte Nase. In manchen Fällen entwickelt sich daraus eine chronische Sinusitis oder eine bleibende Verbindung zwischen Mund und Kieferhöhle (oroantrale Fistel), die eine weitere Operation verlangt. Bei der offenen Technik kann die Verletzung des Gefäßes in der Seitenwand Blutungen verursachen. Bei der geschlossenen kann das Klopfinstrument vorübergehend Schwindel und Gleichgewichtsstörungen (BPPV) auslösen. Materialpartikel oder das Implantat selbst können in die Kieferhöhle wandern und müssen dann gegebenenfalls chirurgisch entfernt werden. Manchmal bildet das Material weniger neuen Knochen als erhofft, und der Eingriff muss wiederholt werden. Auch vorübergehende Geruchsveränderungen sind beschrieben. Membrandicke, Sinusitis-Vorgeschichte und Allgemeinzustand sind die Hauptfaktoren für die Höhe des Risikos." },
    { q: "Für wen ist der Eingriff nicht geeignet?", a: "Bei aktiver Sinusitis, einem Schub allergischer Rhinitis oder einer örtlichen Infektion wird verschoben. Zeigt die Aufnahme eine Zyste, einen Polypen oder eine andere Raumforderung, wird zuerst die Beurteilung durch die Hals-Nasen-Ohren-Heilkunde eingeholt. Ein schlecht eingestellter Diabetes und Gerinnungsstörungen verlangen eigene Vorbereitung. Bei antiresorptiven Medikamenten wie Bisphosphonaten oder Denosumab wird der Eingriff wegen des Risikos einer Kiefernekrose gemeinsam mit der verordnenden Fachrichtung beurteilt; bei intravenöser Gabe wird meist verschoben. Starke Raucher tragen ein höheres Risiko des Aufbau-Misserfolgs – empfohlen wird ein Rauchstopp-Plan im Vorfeld. Bei jungen Patientinnen und Patienten mit unfertigem Kieferwachstum wird das Wachstumsende abgewartet. Diese Informationen ersetzen keine zahnärztliche Diagnose – über die Eignung entscheidet die Untersuchung samt Bildgebung." },
    { q: "Was sollten Sie in den Wochen danach vermeiden?", a: "In den ersten Tagen nicht kräftig schnäuzen; müssen Sie niesen, senkt ein geöffneter Mund den Druckaufbau in der Kieferhöhle. Trinken mit Strohhalm, Blasinstrumente und anstrengender Sport müssen ebenfalls eine Weile warten. Bevorzugen Sie warme, weiche Kost. Empfohlen wird ein kompletter Rauchverzicht für die Wochen vor und nach dem Eingriff – die genaue Dauer wird individuell festgelegt. Aktivitäten mit Druckwechseln wie Fliegen oder Tauchen nicht ohne Rücksprache planen. Längerfristig kann auch Plaque den Knochenpegel senken – regelmäßiges Putzen und Termine zur <a href=\"/de/hizmet/dis-tasi-temizligi/\">professionellen Zahnreinigung</a> verringern dieses Risiko. Die erste Kontrolle fällt meist auf den Tag der Fadenentfernung." }
  ],
  closing: "Die Entscheidung für einen Sinuslift entsteht aus dem Zusammenspiel von Bildbefunden, Allgemeinzustand und Ihren Behandlungszielen. Ob Ihr Fall diese Vorbereitung braucht, klären klinische Untersuchung und 3D-Aufnahme. Die Informationen auf dieser Seite dienen nur der allgemeinen Orientierung und ersetzen keinen persönlichen Behandlungsplan. Bei Fragen erreichen Sie uns über unsere <a href=\"/de/kontakt/\">Kontaktseite</a>."
};
