window.ARTICLE_FR = {
  slug: "all-on-4",
  title: "Implants All-on-4",
  category: "Traitements Implantaires",
  lead: "Soutenir une restauration fixe sur une mâchoire totalement édentée avec seulement quatre implants : voilà le cœur du concept All-on-4. Cette page examine objectivement la logique des implants inclinés, les mesures de planification comme le cantilever et la répartition des appuis, les étapes, le calendrier de cicatrisation, les limites et les risques possibles. Ouvrez la rubrique qui vous intéresse ci-dessous.",
  faqs: [
    {
      q: "Qu'est-ce que le traitement All-on-4 ?",
      a: "Le « quatre » du nom désigne le nombre d'implants qui portent la restauration — pas le nombre de dents posées dessus. Votre praticien place quatre implants dans une mâchoire totalement édentée et construit par-dessus une restauration fixe monobloc portant toutes les dents de cette mâchoire. Deux implants se dressent verticalement à l'avant, deux sont inclinés vers l'arrière. La conception étant d'une seule pièce, toute la charge de la restauration se répartit sur ces quatre appuis. Le traitement par <a href=\"/fr/hizmet/tek-dis-implant/\">implant unitaire</a>, qui prévoit un implant distinct pour chaque dent manquante, suit une logique différente. Les mâchoires supérieure et inférieure ayant des structures osseuses différentes, chaque mâchoire se planifie séparément."
    },
    {
      q: "Pourquoi incliner les implants ?",
      a: "L'os à l'arrière des mâchoires se résorbe plus vite après la perte des dents. Incliner les implants contourne le sinus au maxillaire et le canal nerveux à la mandibule : votre praticien peut ainsi utiliser un implant plus long dans l'os disponible et reculer l'appui postérieur. Dans la plupart des plans, le chirurgien incline les implants arrière entre 30 et 45 degrés. Cela élargit la distance entre l'implant le plus antérieur et le plus postérieur — ce qu'on appelle la répartition antéro-postérieure des appuis. Une répartition plus large raccourcit la section sans appui de la restauration qui s'étend derrière le dernier implant, le <em>cantilever</em> ; un cantilever plus court aide les forces masticatoires à mieux se transmettre aux appuis. Dans certains cas, cela peut aussi réduire le besoin d'une chirurgie supplémentaire comme le <a href=\"/fr/hizmet/sinus-lifting/\">sinus lift</a>. L'angle retenu dépend de la distance entre le plancher sinusien et le canal nerveux."
    },
    {
      q: "À qui ce traitement convient-il ?",
      a: "Votre praticien envisage ce concept pour les adultes qui n'ont plus de dents sur une mâchoire, ou dont les dents restantes ne peuvent être sauvées. Les personnes qui portent une prothèse amovible complète et souffrent de son instabilité relèvent de la même évaluation. Le facteur décisif se situe à l'arrière de la bouche : quand la hauteur osseuse a diminué au niveau des molaires, que le sinus est descendu ou que le canal nerveux affleure, le plan à quatre implants inclinés prend tout son sens. À l'avant, il faut un volume osseux suffisant entre les deux côtés de la mâchoire. Votre praticien vérifie aussi une santé générale compatible avec la chirurgie et une hygiène bucco-dentaire tenable sur la durée."
    },
    {
      q: "Quelles étapes le traitement traverse-t-il ?",
      a: "La feuille de route commence par un examen approfondi et un scanner 3D ; votre praticien étudie la densité osseuse et l'anatomie du sinus et des nerfs, puis planifie numériquement les positions implantaires. Au rendez-vous chirurgical, l'équipe choisit la méthode d'anesthésie appropriée, extrait les dents non conservables et pose les quatre implants aux angles prévus. Si des seuils mesurables comme le couple de pose sont atteints, votre praticien peut fixer une restauration provisoire fixe dans la même séance ; sinon, la mise en charge est différée. La charge immédiate n'est donc pas possible dans tous les cas. Notre page <a href=\"/fr/hizmet/1-gunde-implant/\">implant immédiat</a> détaille cette approche. La cicatrisation terminée, votre praticien prend une empreinte, et le prothésiste prépare la restauration définitive au laboratoire."
    },
    {
      q: "Combien de temps dure le processus ?",
      a: "Le calendrier se mesure entre le jour de la chirurgie et le jour de pose de la restauration définitive. L'étape chirurgicale se termine généralement en un seul rendez-vous ; poser les quatre implants dans la même séance fait partie de la logique du concept. Vient ensuite l'<em>ostéo-intégration</em> — la période où les implants fusionnent avec l'os. Le délai varie selon la mâchoire : deux à quatre mois en bas, trois à six mois en haut, différence expliquée par la densité osseuse généralement plus faible du maxillaire. La restauration monobloc reposant sur les quatre appuis à la fois, la plupart des protocoles attendent l'intégration de chaque implant avant de fabriquer la restauration définitive. Un retard sur un seul appui peut allonger tout le calendrier. Vous passez cette période avec une restauration provisoire fixe, le temps que l'élocution et les habitudes masticatoires se remettent en place."
    },
    {
      q: "Quatre implants ou six ?",
      a: "La différence clé : le nombre d'implants qui portent la mâchoire. All-on-4 utilise quatre appuis, tandis que le traitement <a href=\"/fr/hizmet/all-on-6/\">All-on-6</a> en place six. Les deux appuis supplémentaires élargissent la répartition avant-arrière et raccourcissent l'extension postérieure de la restauration. Six implants exigent en revanche plus de hauteur osseuse à l'arrière et une chirurgie généralement plus longue. Quand l'arrière de la mâchoire s'est nettement résorbé, le plan incliné à quatre implants passe devant ; quand le volume osseux est bien préservé, l'option à six appuis entre en discussion. C'est la hauteur osseuse à l'arrière de votre mâchoire qui tranche entre les deux."
    },
    {
      q: "Quelle différence avec les implants d'arcade complète ?",
      a: "Les deux termes ne sont pas synonymes. Les <a href=\"/fr/hizmet/full-agiz-implant/\">implants d'arcade complète</a> désignent, au sens large, la reconstruction d'une ou des deux mâchoires sur implants ; sous ce parapluie, on trouve des nombres d'implants variables, des restaurations fixes ou amovibles et des solutions de prothèse stabilisée sur implants. All-on-4 est un concept précis : une seule mâchoire, quatre implants, une restauration fixe monobloc. Quand le nombre d'implants change, la planification, le calendrier et l'entretien changent aussi. En bref : l'arcade complète est le terme générique, All-on-4 une approche clairement définie qui s'y range."
    },
    {
      q: "La restauration peut-elle s'enlever et se remettre ?",
      a: "Avec cette conception, vous ne pouvez pas retirer et remettre la restauration vous-même ; la suprastructure est généralement transvissée sur les piliers de connexion des implants. Votre praticien obture les puits d'accès des vis avec du composite ; comme celui-ci peut se colorer avec le temps, il peut être remplacé aux contrôles. Seul votre praticien dépose et repose la restauration, quand un contrôle, un nettoyage ou une réparation l'exige. Le fait qu'une conception transvissée soit démontable est d'ailleurs, dans certains cas, une raison de la choisir — pour faciliter l'entretien et la planification des réparations."
    },
    {
      q: "Quels matériaux pour la restauration ?",
      a: "Trois approches principales se distinguent. La <em>restauration hybride</em> : des dents en résine et une fausse gencive rose en acrylique sur une armature en titane — votre praticien peut la réparer dans des conditions cliniques normales. Avec les restaurations en <a href=\"/fr/hizmet/monolitik-zirkonyum/\">zircone monolithique</a>, le prothésiste usine l'ensemble dans un seul bloc de zircone : aucune jonction nulle part en surface. Dans les conceptions sur <em>barre en titane</em>, une barre métallique forme le squelette de la restauration, avec des dents en céramique ou en composite montées dessus. Vos habitudes masticatoires, l'état des dents antagonistes et vos attentes esthétiques sont pesés ensemble pour choisir."
    },
    {
      q: "Quels changements fonctionnels attendre ?",
      a: "Les quatre implants sont positionnés pour soutenir une restauration fixe portant toute la mâchoire. La suprastructure fixe vise une amélioration fonctionnelle de la mastication ; son ampleur varie avec la qualité osseuse et le type de restauration. Au maxillaire, votre praticien peut poser une conception qui laisse le palais dégagé. Les implants inclinés peuvent, dans certains cas, réduire le besoin d'une chirurgie supplémentaire comme la <a href=\"/fr/hizmet/kemik-grefti/\">greffe osseuse</a>. Vos soins quotidiens et votre santé générale façonnent directement la fonction obtenue. Avec une conception sans palais, la perception du goût et l'élocution demandent quelques semaines d'adaptation."
    },
    {
      q: "Quels sont les risques et inconvénients ?",
      a: "Comme tout acte chirurgical, ce traitement comporte des risques. Œdème, ecchymoses et difficulté passagère à parler peuvent suivre la chirurgie. Infection, perte osseuse autour d'un implant et défaut d'intégration restent possibles. Travailler près du canal nerveux mandibulaire peut provoquer un engourdissement ou une sensibilité modifiée — le plus souvent passager, parfois définitif. Des complications liées au sinus peuvent survenir au maxillaire. Le système reposant sur quatre appuis, la perte d'un implant peut affecter toute la restauration ; le cas échéant, votre praticien dépose provisoirement la restauration et, la zone cicatrisée, envisage un nouvel implant ou un autre nombre d'appuis. Des changements inflammatoires peuvent se développer dans la gencive et l'os autour d'un implant — la <em>péri-implantite</em> — que votre praticien surveille par sondage et radiographies. Raideur à l'élocution, salivation accrue et difficulté à s'habituer à manger sont fréquents pendant la période du provisoire. Desserrage de vis, fracture d'acrylique et usure des dents artificielles peuvent apparaître avec le temps."
    },
    {
      q: "Dans quelles situations ne peut-il pas être réalisé ?",
      a: "Votre praticien classe les contre-indications en deux groupes. Une radiothérapie récente de la tête et du cou et un trouble de la coagulation non contrôlé sont des obstacles définitifs ; certains médicaments agissant sur le métabolisme osseux s'y ajoutent. Diabète non équilibré, infection buccale active et tabagisme important composent le second groupe. Certains de ces facteurs sont temporaires — une fois maîtrisés, le plan peut être réexaminé. Si l'os antérieur entre les deux côtés de la mâchoire ne suffit même pas à une pose inclinée, le plan change : greffe ou autre nombre d'appuis entrent en considération. Quand le serrement est sévère et mal contrôlé, fractures et usure de la restauration se montrent plus souvent — voir notre page <a href=\"/fr/hizmet/dislerimi-sikiyorum/\">serrement des dents</a>. Chez les jeunes patients dont la croissance des mâchoires n'est pas terminée, l'acte est reporté. Seuls l'examen clinique et l'anamnèse peuvent en décider."
    },
    {
      q: "À quoi faire attention après la chirurgie ?",
      a: "Les premiers jours, tenez-vous-en aux aliments mous et évitez tout ce qui est dur ou collant. Tabac et alcool ralentissent la cicatrisation : faites une pause après la chirurgie. Limitez les efforts physiques intenses et tout ce qui met la zone sous pression les premiers jours — saignement et œdème peuvent augmenter. Sous la restauration monobloc à quatre appuis subsiste un espace étroit entre gencive et suprastructure : nettoyez-le chaque jour avec une brossette interdentaire et un hydropulseur. Faites réaliser nettoyage professionnel et contrôle des vis aux intervalles fixés par votre praticien — généralement plus d'une fois par an. Contactez la clinique sans attendre en cas de jeu, saignement, mauvaise odeur ou douleur."
    },
    {
      q: "Qu'est-ce qui détermine la longévité de la restauration ?",
      a: "Impossible de réduire la durée de vie à un chiffre unique. Une fois intégrés à l'os, les corps implantaires peuvent fonctionner de longues années ; la suprastructure peut demander un renouvellement plus tôt. Respecter le calendrier de contrôle compte énormément dans ce concept, car seul l'examen régulier permet à votre praticien de saisir les problèmes tôt. Usure et coloration augmentent avec le temps sur les surfaces acryliques ; les restaurations en zircone présentent un profil de durabilité différent. L'hygiène bucco-dentaire et l'état des dents antagonistes influencent directement le résultat. Le résultat varie d'une bouche à l'autre, et aucune durée ne peut être garantie à l'avance."
    }
  ],
  closing: "En cas d'édentement complet, le plan se dessine selon la répartition de votre volume osseux et l'état de la mâchoire opposée. Votre praticien examine vos scanners 3D et vos antécédents de santé avant de vous présenter les options adaptées. Le choix entre le concept à quatre appuis et l'approche à <a href=\"/fr/hizmet/all-on-6/\">six appuis</a> se joue sur la hauteur osseuse à l'arrière de votre mâchoire. Pour une évaluation, vous pouvez demander un rendez-vous via notre <a href=\"/fr/contact/\">page de contact</a>.",
  metaDescription: "All-on-4 : pour qui ? Implants inclinés, cantilever, étapes du traitement, temps de cicatrisation, risques et entretien expliqués."
};
