window.ARTICLE_FR = {
  slug: "bonding",
  title: "Bonding dentaire (composite bonding)",
  category: "Traitements Esthétiques",
  lead: "Le bonding est une technique esthétique où une résine composite de la couleur de la dent se colle directement sur la surface dentaire et se façonne à la main. Pour les petits éclats, les bords incisifs usés, les espaces étroits entre les dents et les irrégularités de forme d'une seule dent, il se termine généralement en une seule visite. Tailler l'émail sain est soit totalement inutile, soit réduit au strict minimum.",
  faqs: [
    { q: "Qu'est-ce que le bonding, et pour quels problèmes dentaires l'utilise-t-on ?", a: "La résine composite est un matériau photopolymérisable qui adhère à l'émail grâce à un système adhésif. Votre praticien la monte en couches, durcit chacune et la façonne pour épouser la forme naturelle de la dent. Les situations les plus fréquentes : petits éclats des dents de devant, bords usés, espaces étroits entre les dents, et une dent qui paraît plus courte que sa voisine. Il convient mieux aux corrections limitées et ciblées qu'aux changements sur toute la bouche. Les <a href=\"/fr/hizmet/dislerim-ayrik/\">dents écartées</a> et les <a href=\"/fr/hizmet/dislerim-asindi/\">dents usées</a> sont des motifs de consultation typiques." },
    { q: "Qui est un bon candidat au bonding ?", a: "Les personnes dont l'émail est largement intact, la santé gingivale stable et la zone de correction limitée sont généralement considérées comme de bons candidats. Les patients présentant un défaut de forme sur une seule dent entrent souvent dans ce groupe. Votre praticien évalue toujours aussi l'occlusion : la façon dont les dents du haut et du bas entrent en contact influence directement la tenue du matériau. L'indication se confirme par un examen clinique et, au besoin, une radiographie." },
    { q: "Comment procède-t-on, et quelles sont les étapes ?", a: "Première étape : le choix de la teinte ; votre praticien accorde la couleur du composite aux dents voisines dans des conditions proches de la lumière du jour. La surface est ensuite nettoyée, rendue rugueuse au gel de mordançage et enduite d'un adhésif. Le composite se monte en couches jusqu'à la forme cible, chaque couche durcie à la lampe. La forme obtenue, votre praticien l'affine aux fraises fines, contrôle l'occlusion et polit la surface. L'anesthésie n'est généralement pas nécessaire : l'émail sain n'est pas touché du tout, ou très peu." },
    { q: "Se termine-t-il en une visite, et combien de temps faut-il ?", a: "Pour une seule dent, le traitement se termine généralement en 30 à 60 minutes. Quand plusieurs dents sont traitées ensemble, cela prend plus de temps, mais le nombre de rendez-vous reste le plus souvent d'un seul. Sans étape de laboratoire, pas d'empreinte, d'essayage ni d'attente intermédiaire. Dans la plupart des cas, vous reprenez votre routine le jour même." },
    { q: "Quelle différence entre plombage esthétique et bonding ?", a: "Les deux actes utilisent des composites similaires ; la distinction tient à l'objectif. Le travail qui remplace du tissu perdu par carie relève des <a href=\"/fr/hizmet/estetik-dolgular/\">plombages esthétiques</a>. Le bonding, lui, se concentre sur des zones sans carie dont la forme ou la taille pose simplement problème. La ligne se brouille parfois — une dent ébréchée peut cumuler perte structurelle et préoccupation esthétique." },
    { q: "Quelle différence entre facettes en composite et bonding d'une dent ?", a: "C'est le périmètre et l'échelle de planification qui font la différence. Avec les <a href=\"/fr/hizmet/kompozit-lamina/\">facettes en composite</a>, votre praticien couvre toute la face avant de plusieurs dents le long de la ligne du sourire et conçoit la symétrie de zéro. Avec le bonding, le travail reste limité à une dent ou une petite zone, et votre ligne du sourire actuelle demeure en général inchangée. Les <a href=\"/fr/hizmet/porselen-lamina/\">facettes en céramique</a> de laboratoire présentent encore un autre profil de surface et de résistance — avec empreinte, étape de laboratoire et rendez-vous supplémentaires. Qui envisage un changement plus large est évalué dans le cadre du <a href=\"/fr/hizmet/gulus-tasarimi/\">smile design</a>." },
    { q: "Dans quel ordre planifier blanchiment et bonding ?", a: "C'est un détail critique. Si vous envisagez un <a href=\"/fr/hizmet/dis-beyazlatma/\">blanchiment dentaire</a>, il se termine d'abord, la teinte du composite se choisissant ensuite — le composite ne réagit pas au gel de blanchiment et ne s'éclaircira pas plus tard. Coller juste après le blanchiment réduit aussi temporairement la force d'adhésion : une attente d'une à deux semaines est généralement recommandée. Cette attente sert deux buts : laisser la nouvelle teinte se stabiliser et permettre un collage plus fort. L'ordre inverse est possible, mais change le résultat : blanchir après le bonding éclaircit les dents naturelles tandis que le composite garde sa teinte d'origine. La couche de composite ne répondant pas aux agents blanchissants, cet écart ne se corrige pas seul. S'il devient visible, votre praticien retire le composite et applique une nouvelle couche accordée à la teinte plus claire — soit un rendez-vous en plus. Voilà la raison principale de planifier le blanchiment d'abord ; en fixant l'ordre, votre praticien intègre aussi vos attentes de teinte à plus long terme." },
    { q: "Le composite se colore-t-il avec le temps ?", a: "Le matériau lui-même ne répond pas aux agents blanchissants, mais il est sensible aux colorations externes. Thé, café, vin rouge et jus de fruits foncés peuvent créer un écart de teinte en surface avec le temps. À mesure que la brillance s'estompe, la coloration s'accumule plus vite ; nettoyage professionnel régulier et repolissage périodique ralentissent le processus. Si l'écart devient visible, votre praticien peut repolir la surface ou renouveler la couche externe. Dire que le composite <em>ne change jamais de couleur</em> serait donc inexact." },
    { q: "Quels sont les risques et inconvénients possibles ?", a: "La résine composite a un profil d'usure et de fracture différent des options à base de céramique. Se ronger les ongles, mâchonner un stylo ou croquer de la glace peut ébrécher le bord incisif. Une fine ligne colorée peut devenir visible à la limite du collage avec le temps ; le polissage la réduit, mais elle peut réapparaître. Si la zone traitée jouxte la gencive, un excès de matériau peut déclencher une inflammation gingivale. Une partie ou la totalité du composite peut se détacher et devoir être réappliquée. En cas d'éclat, la réparation se fait souvent sans retirer toute la couche — la ligne de réparation peut toutefois devenir visible avec le temps, et quand la coloration pénètre en profondeur, le repolissage ne suffit plus : la couche se renouvelle. Du matériau ayant été ajouté, le volume de la dent augmente légèrement, ce qui peut sembler inhabituel les premiers jours. Si l'occlusion n'a pas été correctement réglée, vous pouvez ressentir pression ou sensibilité à la mastication. Quand une partie de l'émail a été rendue rugueuse, cette modification de la structure ne s'inverse pas." },
    { q: "Quand n'est-il pas réalisé, ou reporté ?", a: "En cas de carie active, d'inflammation gingivale avancée ou d'infection canalaire, votre praticien s'en occupe d'abord et laisse l'étape esthétique pour plus tard. Sur les dents très délabrées, dévitalisées et fragilisées, les options de couronne peuvent passer devant. Face à un chevauchement notable ou un trouble occlusal, une évaluation orthodontique est recommandée d'abord. Chez les patients au <a href=\"/fr/hizmet/dislerimi-sikiyorum/\">serrement</a> ou grincement nocturne, le risque de fracture est plus élevé : le traitement n'avance pas sans gouttière de nuit planifiée. En cas de tabagisme important, les attentes sur la coloration se discutent d'emblée." },
    { q: "À quoi faire attention après le traitement ?", a: "Les 48 premières heures sont la période la plus sensible ; boissons colorées et tabac tachent la surface plus facilement. Éviter de casser des coques dures avec les dents de devant, et ne pas décapsuler avec les dents, réduit le risque d'éclat de bord. Brossage deux fois par jour et fil dentaire réduisent l'accumulation de plaque à la limite." },
    { q: "Combien de temps dure-t-il, et qu'est-ce qui en décide ?", a: "La longévité du bonding varie considérablement d'une personne à l'autre — avancer un chiffre unique ne serait pas réaliste. La charge masticatoire de la zone traitée, votre routine de soins et les habitudes comme le serrement influencent directement le résultat. Le risque de fracture augmente aux bords où le composite reste fin — c'est pourquoi votre praticien vise un résultat plus prévisible là où une épaisseur suffisante peut être maintenue." }
  ],
  closing: "Le bonding compte parmi les options envisagées pour les corrections de petite ampleur qui font pourtant une différence visible dans votre sourire. La méthode qui vous convient ne se précise qu'après évaluation de l'état actuel de la dent, de la qualité de l'émail et de l'occlusion. Pour un rendez-vous d'examen, vous pouvez nous joindre via notre <a href=\"/fr/contact/\">page de contact</a>.",
  metaDescription: "Bonding : pour qui, en combien de temps ? Réparation composite en une visite — éclats, bords usés, espaces — risques et entretien."
};
