window.ARTICLE_FR = {
  slug: "dis-cekimi",
  title: "Extraction dentaire",
  category: "Traitements Généraux",
  lead: "L'extraction dentaire est le retrait d'une dent de son alvéole osseuse avec des instruments spécialisés, réalisé une fois que la garder en bouche ne sert plus à rien. En dentisterie moderne, la priorité va toujours à la préservation de la dent naturelle — l'extraction n'entre en scène qu'une fois les autres options épuisées. Sur cette page : le déroulé d'une extraction simple, l'importance du caillot sanguin qui suit, et comment combler l'espace laissé.",
  faqs: [
    { q: "Qu'est-ce que l'extraction dentaire, et pourquoi la réalise-t-on ?", a: "Extraire une dent, c'est détacher sous anesthésie locale le tissu conjonctif autour d'elle et la retirer de son alvéole osseuse. Votre praticien considère d'abord les options qui préservent la dent — plombage, <a href=\"/fr/hizmet/kanal-tedavisi/\">traitement de canal</a> ou couronne ; l'extraction n'entre en scène que si la dent ne peut se garder par ces moyens. Le but : supprimer la source de douleur et d'infection, tout en protégeant dents voisines et os. La technique utilisée sur les dents visibles en bouche, aux racines largement saines, s'appelle l'<em>extraction simple</em>." },
    { q: "Quand l'extraction devient-elle inévitable ?", a: "L'extraction passe en tête quand la carie avancée a atteint le niveau radiculaire, quand une fissure descend sous le bord osseux, ou quand la maladie gingivale a nettement rongé l'os qui tient la dent. Abcès récidivants et infections qui ne cèdent pas malgré les traitements répétés figurent aussi sur cette liste. L'extraction peut aussi se planifier en orthodontie, pour créer de la place dans une mâchoire encombrée. Les dents restées dans l'os demandent une approche chirurgicale différente, détaillée sur notre page <a href=\"/fr/hizmet/gomulu-dis-cekimi/\">extraction de dent incluse</a>." },
    { q: "Quelle différence entre extraction simple et extraction chirurgicale ?", a: "Dans l'extraction simple, la dent est visible en bouche ; le praticien la détache de son alvéole à l'élévateur et au davier, sans inciser la gencive en général. Dans l'extraction chirurgicale, il soulève un petit lambeau gingival, retire au besoin de l'os et sort la dent en fragments. Les deux techniques ne s'échangent pas — la position de la dent décide de la bonne. Les dents de sagesse partiellement sorties ou inclinées relèvent en général du second groupe — nous les couvrons à part sous <a href=\"/fr/hizmet/yirmilik-yas-disi-cekimi/\">extraction des dents de sagesse</a>. La radiographie est la première étape de la planification : elle renseigne sur le nombre de racines et leur proximité au canal nerveux." },
    { q: "Quelles sont les étapes de l'acte ?", a: "Votre praticien commence par l'examen et la radiographie, et interroge antécédents médicaux, médicaments en cours et tendance au saignement. Il anesthésie ensuite localement la zone et attend quelques minutes l'effet. Les fibres parodontales autour de la dent se détachent, la dent sort de son alvéole par mouvements contrôlés, et l'alvéole se nettoie. Quelques points peuvent se poser au besoin, puis on vous demande de mordre sur une compresse stérile pour comprimer la zone. Vous pouvez sentir pression et poussée tout au long de l'acte ; à la moindre douleur vive, prévenez immédiatement — l'anesthésie se complète." },
    { q: "Combien de temps cela prend-il, et combien de jours pour cicatriser ?", a: "L'anesthésie prise, extraire une dent monoradiculée se termine en général en quelques minutes ; les molaires peuvent prendre un peu plus. Le rendez-vous entier, examen et consignes compris, dépasse rarement la demi-heure. Les tissus mous se referment en une à deux semaines. Le comblement et la maturation de l'alvéole osseuse sont un processus silencieux qui se joue sur plusieurs mois. Le gonflement culmine en général les deux premiers jours puis régresse ; une douleur qui <strong>augmente</strong> après le troisième jour sort du schéma normal." },
    { q: "Pourquoi le caillot sanguin est-il si important après une extraction ?", a: "Le caillot qui se forme en quelques minutes dans l'alvéole vide est une couverture naturelle protégeant l'os exposé et les terminaisons nerveuses dessous. Nouveaux vaisseaux et cellules osseuses y poussent — c'est l'échafaudage sur lequel la cicatrisation se construit. Boire à la paille, rincer fort, cracher à répétition et l'aspiration du tabac peuvent tous le déloger. Voilà pourquoi, les premières vingt-quatre heures, on vous demande d'avaler plutôt que de cracher, et de ne pas toucher la zone du doigt ni de la langue. Douche chaude, effort intense et alcool peuvent relancer le saignement — mieux vaut les remettre au lendemain." },
    { q: "Qu'est-ce que l'alvéolite sèche, et comment la reconnaître ?", a: "Si le caillot part trop tôt, ou ne se forme jamais correctement, l'os reste exposé à la bouche et l'alvéolite sèche s'installe. Elle démarre typiquement deux à quatre jours après l'extraction, par une douleur pulsatile irradiant vers l'oreille ou la tempe ; l'alvéole peut paraître vide et grisâtre là où le caillot devrait être, avec une odeur désagréable. Les antalgiques contrôlent en général mal cette douleur — attendre qu'elle passe seule fait perdre du temps. Elle est nettement plus fréquente après extraction des molaires inférieures et des dents incluses, chez les fumeurs et en cas d'hygiène insuffisante. Votre praticien irrigue l'alvéole au sérum et place un pansement médicamenteux pour apaiser la douleur ; cela peut se répéter sur quelques visites." },
    { q: "Quels sont les risques et complications possibles de l'extraction ?", a: "Comme tout acte chirurgical, des issues indésirables restent possibles. Saignement, gonflement, ecchymoses et ouverture limitée par la contraction des muscles masticateurs sont courants et se règlent en général en quelques jours. Moins fréquents : infection, atteinte d'une dent voisine ou de son plombage, apex fracturé resté dans l'alvéole, et engourdissement de la lèvre ou du menton quand les racines inférieures jouxtent le nerf. Cet engourdissement se résout en quelques semaines dans la plupart des cas — rarement, il peut rester définitif ; si la radiographie montre une proximité risquée, votre praticien vous prévient à l'avance. Aux molaires supérieures, une communication peut aussi s'ouvrir entre sinus et bouche, exigeant parfois un geste de fermeture. Sous anticoagulants ou avec un trouble de la coagulation, le saignement peut mettre plus de temps à se calmer. Contactez la clinique en cas de douleur qui s'aggrave encore après quarante-huit heures, de fièvre ou de difficulté à avaler." },
    { q: "À qui ne convient-elle pas, et quand se reporte-t-elle ?", a: "Face à une infection aiguë qui s'étend, votre praticien la contrôle en général d'abord — antibiotiques et drainage — et reporte l'extraction. Diabète non contrôlé, infarctus ou AVC récents, troubles graves de la coagulation et antécédent de radiothérapie tête et cou demandent tous une évaluation détaillée. Les personnes sous traitements renforçant l'os peuvent avoir des problèmes de cicatrisation de la mâchoire — le praticien se concerte avec le spécialiste qui gère ce traitement. Pendant la grossesse, les extractions non urgentes se planifient en général au deuxième trimestre. Partager avant le rendez-vous tous vos médicaments et maladies chroniques est essentiel à cette évaluation." },
    { q: "À quoi faire attention, et que couvrent les suites ?", a: "Mordez la compresse d'une pression constante environ une demi-heure, sans la retirer trop souvent pour vérifier. Le premier jour : compresse froide sur la joue par intervalles, nourriture tiède et molle. Continuez de vous brosser les dents en évitant le site d'extraction ; le feu vert du praticien donné, passez aux rinçages doux à l'eau salée tiède. Une pause de tabac est un pas important pour réduire le risque d'alvéolite sèche. Prenez les antalgiques comme indiqué, et ne prenez pas de votre propre chef de médicaments comme l'aspirine, qui peuvent augmenter le saignement." },
    { q: "Que peut-on faire pour remplacer la dent extraite ?", a: "Un espace laissé ouvert longtemps : les dents voisines y basculent, la dent antagoniste s'égresse et l'équilibre de votre occlusion se dérègle. L'os de la mâchoire perd aussi du volume dans une zone qui ne travaille plus. Voilà pourquoi votre praticien discute du comblement de l'espace dès la planification de l'extraction : <a href=\"/fr/hizmet/tek-dis-implant/\">implant unitaire</a>, <a href=\"/fr/hizmet/porselen-kron-kopru/\">couronne et bridge en céramique</a> appuyés sur les dents voisines, ou prothèses amovibles sont les options. Si un implant s'envisage, la cicatrisation prend en général quelques mois avant de pouvoir avancer ; si le volume osseux manque, une <a href=\"/fr/hizmet/kemik-grefti/\">greffe osseuse</a> peut entrer en scène. L'option qui vous convient se précise une fois évalués l'état de vos dents restantes et les mesures osseuses." }
  ],
  closing: "L'extraction est la dernière étape, envisagée seulement une fois épuisée toute possibilité de garder la dent. Si une dent vous fait mal ou bouge, vous pouvez prendre rendez-vous via notre <a href=\"/fr/contact/\">page de contact</a> — nous passerons aussi en revue les options au-delà de l'extraction.",
  metaDescription: "Quand l'extraction dentaire s'impose-t-elle, et comment se déroule-t-elle ? Importance du caillot, symptômes de l'alvéolite sèche, risques et remplacement."
};
