window.ARTICLE_FR = {
  slug: "dis-teli",
  title: "Bagues dentaires (métal / céramique)",
  category: "Orthodontie",
  lead: "Le traitement par bagues fixes déplace les dents de façon contrôlée grâce à de petits brackets collés sur chaque dent, reliés par un fil d'arcade. Chez Smile Group, le choix entre brackets métalliques et céramiques ne se planifie qu'après évaluation de votre occlusion et de l'alignement de vos dents. Sur cette page : le fonctionnement du traitement, sa durée, ses implications au quotidien et le déroulé de la contention.",
  faqs: [
    { q: "Qu'est-ce que le traitement par bagues, et comment fonctionnent les brackets fixes ?", a: "Le bracket est une petite pièce collée sur la surface dentaire avec un adhésif spécial, qui retient le fil d'arcade. Le praticien positionne chaque bracket à un angle et une hauteur définis au centre de la dent ; le fil logé dans la gorge cherche à reprendre sa forme d'origine et transmet à la dent une force douce et continue. Cette force lance le remodelage de l'os autour de la racine, et la dent se porte graduellement vers sa nouvelle position. Le système couvre un éventail de tableaux : <a href=\"/fr/hizmet/dislerim-yamuk/\">dents chevauchées</a>, écarts entre les dents, supraclusion profonde." },
    { q: "Quelle différence entre brackets métalliques et brackets céramiques (transparents) ?", a: "Les brackets métalliques sont en alliage d'acier inoxydable, au profil fin, et se comportent de façon prévisible côté friction au changement de fil. Les brackets céramiques sont couleur dent et semi-translucides — bien moins visibles — mais un peu plus volumineux, avec un autre profil de fracture. Les adultes soucieux de l'apparence préfèrent souvent la céramique ; le métal peut être un avantage dans les plans longs à étapes multiples. Qui veut réduire encore la visibilité peut aussi regarder l'<a href=\"/fr/hizmet/seffaf-plakla-ortodonti/\">orthodontie par aligneurs transparents</a> et <a href=\"/fr/hizmet/invisalign/\">Invisalign</a>." },
    { q: "Qui est un bon candidat au traitement par bagues fixes ?", a: "Les bagues fixes se posent une fois la plupart des dents définitives sorties — en général dès 12 ans environ — et sans limite d'âge supérieure. Chez les adultes aux gencives saines et au bon soutien osseux, le traitement se planifie sans difficulté. Chevauchement modéré à sévère, <a href=\"/fr/hizmet/dislerim-ayrik/\">écarts entre les dents</a>, dents tournées et remontée d'une dent incluse sur l'arcade sont les indications typiques. Chez les enfants plus jeunes, encore en croissance, les approches d'<a href=\"/fr/hizmet/cocuk-ortodontisi/\">orthodontie pédiatrique</a> se considèrent en général d'abord." },
    { q: "Que se passe-t-il au premier rendez-vous, et par quelles étapes passe le traitement ?", a: "Le praticien commence par le dossier orthodontique — panoramique et téléradiographie, photos intra-orales et scan numérique pour analyser l'occlusion. Le plan arrêté, le tartre se retire et les caries se traitent ; s'il faut de la place, extraction ou légère réduction interproximale s'intègre au plan. Au rendez-vous de collage : mordançage de la surface au gel acide, application de l'adhésif, et fixation individuelle de chaque bracket à la résine photopolymérisée. Pendant la phase active, le praticien change le fil toutes les quatre à huit semaines et vérifie votre assiduité aux élastiques." },
    { q: "Combien de temps dure le traitement ?", a: "Dans la plupart des cas, la phase active prend 18 à 24 mois ; cela peut descendre vers 12 mois pour un chevauchement limité, et dépasser 30 mois avec un décalage squelettique ou une dent incluse. Le calendrier se façonne sur la vitesse biologique du mouvement dentaire, votre assiduité aux rendez-vous et le port des élastiques. Les brackets décollés sont une cause fréquente d'allongement. Le praticien donne une fourchette au départ, qui se précise au fil des contrôles." },
    { q: "Quel niveau de douleur et de sensibilité attendre, et comment l'adoucir ?", a: "Le collage des brackets ne cause en général aucune gêne — rien ne se coupe ni ne se fraise. La sensibilité démarre typiquement quelques heures après la pose du premier fil, culmine les deuxième et troisième jours, et se calme en une semaine chez la plupart des gens. Une version plus douce peut se répéter deux ou trois jours après chaque changement de fil. Aliments mous, eau froide et l'antalgique recommandé par votre praticien rendent ces jours plus confortables." },
    { q: "À quoi servent les ligatures colorées, et la couleur choisie influence-t-elle le traitement ?", a: "Les ligatures élastomériques sont de petits anneaux colorés qui tiennent le fil dans la gorge du bracket ; le praticien les remplace à chaque contrôle. La couleur choisie n'a aucun effet sur le traitement — pure préférence personnelle — même si les teintes claires peuvent se colorer au café, au thé et aux plats très épicés. Avec les brackets céramiques, cette coloration se remarque plus sur une ligature transparente. Les élastiques inter-arcades sont un tout autre sujet : ils corrigent la relation d'occlusion et se portent de longues heures par jour." },
    { q: "Quels aliments peuvent endommager les bagues ?", a: "Aliments durs et collants peuvent arracher un bracket ou tordre le fil. Noix, noisettes, glaçons, caramels, chewing-gum et loukoums trônent en tête de la liste à risque. Pour pommes, carottes et maïs en épi : couper en petits morceaux et mâcher avec les dents du fond est plus simple que de croquer dedans. Boissons acides et sucrées accélèrent la perte d'émail autour des brackets — mieux vaut les réduire." },
    { q: "Quels outils pour le nettoyage quotidien ?", a: "Brosser après chaque repas principal est la règle d'or avec des bagues fixes — corps du bracket et fil créent un abri où la plaque s'accumule. Une brosse orthodontique à coupe en V loge le fil au milieu des poils ; brossez séparément le bord côté gencive et le bord supérieur du bracket, brosse inclinée à 45 degrés sur chacun. La brossette interdentaire nettoie les petits triangles entre fil et gencive, et un enfile-fil passe le fil dentaire sous le fil d'arcade. L'hydropulseur est un ajout utile mais ne les remplace pas — un complément, pas un substitut. Un <a href=\"/fr/hizmet/dis-etim-kaniyor/\">saignement gingival</a> qui démarre est souvent le tout premier signe d'un nettoyage pas tout à fait assez poussé." },
    { q: "Qu'est-ce qu'une tache blanche (white spot), et comment la prévenir ?", a: "La lésion de tache blanche est une marque terne et crayeuse formée quand l'acide de la plaque accumulée autour d'un bracket puise les minéraux de l'émail. Courante chez les porteurs de bagues fixes, elle peut progresser en carie si rien n'est fait. Ces marques peuvent rester en surface après la dépose ; certaines s'estompent avec le temps, sans disparaître forcément complètement — les cas avancés demandent un traitement restaurateur. Pour réduire le risque : dentifrice fluoré, bain de bouche recommandé par votre praticien et rendez-vous réguliers de <a href=\"/fr/hizmet/dis-tasi-temizligi/\">détartrage</a>." },
    { q: "Quels sont les risques et complications possibles ?", a: "Effets indésirables assez fréquents du traitement fixe : taches blanches sur l'émail, inflammation et hypertrophie gingivales, irritation de la muqueuse des joues et des lèvres, brackets décollés. La résorption radiculaire — un raccourcissement de l'apex — se voit à la radiographie dans une part des cas ; en général limitée, elle est irréversible quand elle progresse. Dans les traitements longs, récession gingivale et amincissement du soutien osseux autour des incisives inférieures peuvent survenir. La dépose des brackets céramiques porte un profil de risque différent pour l'émail — le praticien adapte la technique au type de bracket. Des symptômes articulaires préexistants peuvent évoluer pendant le traitement, dans un sens ou l'autre. L'élocution s'ajuste en quelques jours ; nous recommandons un protège-dents à qui joue d'un instrument à vent ou pratique un sport de contact. Contrôles réguliers et hygiène poussée tiennent la plupart de ces risques au minimum." },
    { q: "Quand le traitement n'est-il pas mené, ou reporté ?", a: "Aucun collage en présence de maladie gingivale active, de caries non traitées ou de plaque incontrôlée ; l'orthodontie attend leur résolution. Avec une perte osseuse parodontale avancée, déplacer les dents pourrait réduire encore le soutien restant — le praticien change le plan ou vise des objectifs plus limités. Diabète non contrôlé, antécédent de radiothérapie tête et cou et certains médicaments du métabolisme osseux appellent d'abord une concertation entre spécialistes. Chez qui n'a pas encore de routine d'hygiène solide, le calendrier se reconsidère à cause du risque de taches blanches. Face à un décalage squelettique marqué, les brackets seuls ne suffiront pas — le traitement se planifie avec la <a href=\"/fr/hizmet/ortognatik-cerrahi/\">chirurgie orthognathique</a>." },
    { q: "Pourquoi l'étape de contention est-elle indispensable ?", a: "La contention est une étape à part entière du traitement, visant à garder les dents dans leur nouvelle position après la dépose. Les ligaments parodontaux autour de chaque dent tendent à la ramener vers son ancienne position — sauter cette étape fait souvent revenir le chevauchement. Le praticien colle un fin fil tressé fixe derrière les incisives supérieures et inférieures, en général avec une gouttière transparente amovible portée la nuit. Le fil fixe restant des années en place, plaque et tartre continuent de s'y déposer — n'arrêtez pas le nettoyage interdentaire sous prétexte que les brackets sont partis ; nettoyez chaque jour sous le fil avec un enfile-fil. Aux contrôles, le praticien regarde l'alignement, mais aussi l'intégrité du fil et la santé de la gencive autour. Le port de la gouttière est plus intensif la première année, puis passe en général aux nuits seules — et nous recommandons de le tenir de longues années. Si vous remarquez le fil fixe décollé, contactez-nous sans attendre : les dents peuvent commencer à bouger en quelques semaines." },
    { q: "Que faire en urgence, et quand contacter la clinique ?", a: "Un bracket décollé n'est en général pas une urgence — il reste souvent accroché au fil et peut se stabiliser provisoirement à la cire orthodontique. Si le bout du fil pique votre joue, couvrez d'abord la pointe de cire. Si cela ne suffit pas et qu'il faut raccourcir le bout qui dépasse : posez une compresse ou un mouchoir sur la zone pour éviter d'avaler ou d'inhaler le fragment coupé, coupez avec un coupe-ongles propre et retirez le morceau avec le tissu. Même après ces réparations provisoires, appelez tout de même la clinique — un bracket laissé longtemps sans réparation retarde le traitement. Fragment avalé, fil enfoncé dans le plancher buccal ou gonflement qui ne retombe pas : contactez-nous immédiatement, sans attendre." }
  ],
  closing: "Savoir si le traitement par bagues fixes convient à votre alignement ne se précise qu'après examen clinique et dossier orthodontique complet. La question métal-ou-céramique, nous préférons y répondre ensemble, en parcourant vos habitudes quotidiennes, votre routine d'hygiène et ce que vous attendez du traitement. Pour rendez-vous et questions, vous pouvez nous joindre via notre <a href=\"/fr/contact/\">page de contact</a>.",
  metaDescription: "Bagues métalliques et céramiques : fonctionnement, durée du traitement en mois, gestion de la douleur et de l'hygiène, et pourquoi la contention compte."
};
