window.ARTICLE_FR = {
  slug: "disim-agriyor",
  title: "J'ai mal aux dents",
  category: "Sommeil & Santé de la Mâchoire",
  lead: "Une rage de dents qui démarre seule, pulse et s'aggrave la nuit est souvent le signe précoce d'un problème du tissu interne de la dent ou du pourtour de la racine. C'est un tableau différent de la sensibilité fugace au froid ou au sucré qui s'efface en quelques secondes — cette douleur-là n'est pas censée se calmer seule. Cette page explique les sources possibles de la douleur, les symptômes qui exigent une attention urgente et le déroulé d'un examen.",
  faqs: [
    { q: "De quoi une rage de dents constante et pulsatile peut-elle être le signe ?", a: "La pulpe au centre de la dent se compose de nerfs et de vaisseaux, entourée de parois dures. Quand une inflammation s'y développe, le gonflement qu'elle produit n'a nulle part où s'étendre : la pression monte, et vous sentez un battement au rythme de votre pouls. Douleur qui démarre sans déclencheur, dure des minutes voire des heures et ne cède pas complètement aux antalgiques : autant de signaux cohérents avec ce tableau. Cela dit, le battement seul n'est pas un diagnostic — la source peut être la dent, la gencive, l'os ou une structure voisine. Les départager passe par l'examen clinique et les constats radiographiques." },
    { q: "Quelles sont les causes les plus fréquentes du mal de dents ?", a: "La carie profonde domine : ayant traversé émail et dentine, elle peut déclencher une inflammation difficile à réverser une fois la pulpe atteinte. Vient ensuite l'inflammation pulpaire avancée — le tissu ayant perdu sa vitalité, un abcès peut se former à l'apex, et la douleur s'aiguise à la pression sur la dent. La dent fissurée s'annonce plutôt par une douleur qui surgit après avoir mordu dans du dur, précisément au relâchement de la morsure. Les abcès d'origine gingivale peuvent produire une douleur sévère même sur une dent d'apparence parfaitement saine ; ce tableau peut s'accompagner de gonflement, de rougeur ou d'un écoulement désagréable de la gencive. Carie qui progresse sous un vieux plombage, couronne cassée et dent de sagesse en éruption sont aussi des causes courantes. Plus rarement, une inflammation des sinus au-dessus de la mâchoire supérieure peut donner une sensation de douleur aux molaires supérieures ; plusieurs dents sont alors en général sensibles à la fois." },
    { q: "Quelle différence avec la sensibilité brève au froid ?", a: "La différence tient largement au rythme. La sensibilité démarre sur un déclencheur, reste brève et cède vite une fois le déclencheur retiré ; eau froide, thé chaud ou bouchée sucrée sont les déclencheurs typiques. Ce que nous décrivons ici est autre : la douleur démarre sans rien faire, dure des minutes, s'étend et vous réveille la nuit. Si vous vivez une sensibilité brève et déclenchée, notre page <a href=\"/fr/hizmet/disim-sizliyor/\">ma dent est sensible</a> est un meilleur point de départ. Les deux tableaux peuvent aussi basculer l'un vers l'autre — une sensibilité installée depuis des semaines qui vire soudain au battement spontané est un signal d'alarme : le problème est descendu plus profond." },
    { q: "Pourquoi ma douleur empire-t-elle la nuit et trouble-t-elle mon sommeil ?", a: "S'allonger augmente le flux sanguin vers la tête, ce qui élève la pression dans le tissu enflammé. Les distractions du jour disparues, votre seuil de douleur baisse aussi. Additionnez les deux : une douleur gérable le jour peut devenir assez sévère pour vous réveiller la nuit. Une douleur qui empire la nuit est un schéma à ne pas ignorer." },
    { q: "Quels symptômes noter avant de voir le praticien ?", a: "Ce qui accompagne la douleur en dit autant que son caractère. Douleur aggravée par la chaleur et un peu calmée par le froid, sensibilité qui s'aiguise au toucher ou à la pression, dent qui semble plus haute que ses voisines, petit bouton sur la gencive, mauvais goût persistant et craquement à la mastication méritent tous d'être notés. Une douleur gagnant l'oreille, la tempe ou le dessous de la mâchoire vaut aussi la mention. Transmettre ces détails à votre praticien raccourcit l'examen et aide à cibler la bonne zone." },
    { q: "Quels symptômes exigent une attention urgente ?", a: "Si l'un des signes suivants s'applique, n'attendez pas — direction les urgences les plus proches ou un service dentaire d'urgence : gonflement qui s'étend sur le visage et grossit vite, gonflement descendant vers l'œil ou le cou, fièvre et frissons, difficulté à avaler, difficulté à respirer, bouche impossible à ouvrir, raideur de la nuque. Ces constats peuvent signifier que l'infection a dépassé la dent vers les espaces des tissus mous — et cela peut engager le pronostic vital. Attendre le matin, <strong>tenir aux antalgiques</strong> ou espérer que le gonflement retombe seul n'est pas le bon choix dans ce tableau. En présence de gonflement, une douleur qui s'apaise ne signifie pas que les choses s'améliorent." },
    { q: "Sans signe urgent, sous quel délai consulter ?", a: "Pour une douleur spontanée et pulsatile, la bonne approche : le rendez-vous le plus tôt possible — cette douleur ne tend pas à se calmer seule. Une douleur qui s'arrête en quelques jours ne signifie souvent pas la guérison ; elle peut signifier que la pulpe a perdu sa vitalité, et après une accalmie, le tableau peut revenir en abcès. Annuler son rendez-vous parce que la douleur a cessé peut mener plus tard à un traitement bien plus lourd." },
    { q: "Que faire à la maison pour un soulagement provisoire ?", a: "Rincer doucement à l'eau salée tiède, dégager au fil dentaire les aliments coincés entre les dents et garder la tête légèrement surélevée en position allongée peuvent alléger un peu la pression locale. Une compresse froide enveloppée d'un linge fin peut s'essayer contre l'extérieur de la joue par courtes périodes. Se tenir loin des boissons très chaudes ou très froides et des aliments durs et sucrés réduit la fréquence des déclenchements. Tout cela soulage provisoirement ; rien ne supprime la source du problème." },
    { q: "Mettre de l'aspirine sur une dent douloureuse fait-il du mal ?", a: "<strong>Poser de l'aspirine directement sur une dent douloureuse</strong> est une habitude courante et nocive : le comprimé brûle chimiquement la gencive et la joue qu'il touche, laisse une plaie blanche — et ne réduit pas la douleur. De même, huile de clou de girofle, eau de Cologne, alcool ou vinaigre appliqués directement irritent le tissu. Une compresse chaude peut aggraver un gonflement en présence d'inflammation. Percer un bouton gingival à l'aiguille peut porter l'infection plus profond. Reprendre de sa propre initiative des antibiotiques restés d'une ancienne cure masque le tableau et augmente le risque de résistance — la décision d'antibiotiques appartient à votre praticien." },
    { q: "Que vérifie le praticien pendant l'examen ?", a: "Le praticien écoute d'abord le début de la douleur, ses déclencheurs et ses irradiations. Il examine ensuite dents et gencives à l'œil, mène un test de percussion sur la dent suspecte et évalue l'état de la pulpe par un test de vitalité au froid ou électrique. Les profondeurs de poches se mesurent à la sonde parodontale. La radiographie rétro-alvéolaire montre les changements à l'apex ; l'imagerie 3D peut se demander au besoin. En cas de suspicion de fissure : test de morsure et examen au grossissement. Le but de ces étapes : distinguer la dent responsable de ses voisines." },
    { q: "Quels traitements peuvent entrer en scène ?", a: "Le traitement dépend de l'origine de la douleur. Pour une carie n'ayant pas atteint la pulpe, un <a href=\"/fr/hizmet/dolgu/\">plombage</a> après nettoyage peut suffire. Face à une inflammation pulpaire ou une infection apicale, le <a href=\"/fr/hizmet/kanal-tedavisi/\">traitement de canal</a> entre en scène ; si beaucoup de tissu a été perdu, protéger ensuite la dent par une <a href=\"/fr/hizmet/kaplama/\">couronne</a> peut se planifier. Quand une fissure descend dans la racine, ou que la dent ne peut plus se garder, l'<a href=\"/fr/hizmet/dis-cekimi/\">extraction dentaire</a> s'envisage. Si la douleur vient d'une dent de sagesse en éruption, l'<a href=\"/fr/hizmet/yirmilik-yas-disi-cekimi/\">extraction de dent de sagesse</a> se discute ; si la dent est encore dans l'os, c'est l'<a href=\"/fr/hizmet/gomulu-dis-cekimi/\">extraction de dent incluse</a>. La bonne option ne se décide pas sans les constats d'examen et de radiographie." },
    { q: "Comment réduire le risque que la douleur revienne ?", a: "Brosser au dentifrice fluoré deux fois par jour et faire du nettoyage interdentaire une habitude agit directement sur le point de départ de la carie. Un contrôle tous les six mois attrape caries et plombages infiltrés tôt, avant la douleur. En cas de saignement ou de récession gingivale, les étapes de notre page <a href=\"/fr/hizmet/dis-etim-kaniyor/\">mes gencives saignent</a> peuvent aider. Chez qui a une habitude nocturne de <a href=\"/fr/hizmet/dislerimi-sikiyorum/\">serrement des dents</a>, le risque de micro-fissures monte — une gouttière protectrice mérite la discussion. Rompre l'habitude de croquer glaçons, capuchons de stylo et coques dures réduit aussi le risque de fissure." },
    { q: "Quelles sont les idées reçues sur le mal de dents ?", a: "En tête : <em>la douleur est partie, la dent a guéri</em> — la mort du tissu nerveux fait aussi taire la douleur. L'approche <em>des antibiotiques régleront ça</em> est erronée aussi : le médicament ne retire pas le tissu à la source de l'infection. La sévérité de la douleur n'est pas toujours proportionnelle à l'étendue des dégâts : une carie d'apparence mineure peut faire très mal, un cas avancé rester muet. Autre croyance courante : une douleur de dent supérieure serait directement liée à l'œil — la douleur projetée des sinus dans la zone postérieure supérieure est en fait une explication bien plus probable." }
  ],
  closing: "Une rage de dents qui vous réveille la nuit réduit vos options à mesure qu'elle se remet. Gonflement du visage, fièvre ou difficulté à avaler : attention urgente sans délai ; rien de tout cela : le rendez-vous le plus tôt possible reste la bonne étape. Vous pouvez nous joindre via notre <a href=\"/fr/contact/\">page de contact</a> pour faire évaluer votre douleur et discuter du bon plan de traitement.",
  metaDescription: "Rage de dents pulsatile qui empire la nuit : causes possibles, signes d'urgence comme gonflement et fièvre, et à quoi s'attendre."
};
