window.ARTICLE_FR = {
  slug: "kemik-grefti",
  title: "Greffe osseuse",
  category: "Traitements Implantaires",
  lead: "La greffe osseuse est une préparation chirurgicale utilisée avant le traitement implantaire pour reconstruire le volume perdu de l'os de la mâchoire. Sur cette page : les types de greffes disponibles, le déroulement de l'acte, la cicatrisation et les risques possibles. Ouvrez la rubrique qui vous intéresse ci-dessous.",
  faqs: [
    { q: "Qu'est-ce qu'une greffe osseuse ?", a: "Votre praticien place dans la zone qui a perdu du volume un matériau qui imite la structure de l'os — la greffe osseuse. Ce matériau agit comme un échafaudage : il offre une trame dans laquelle l'os vivant environnant vient croître. La greffe n'est pas un traitement en soi ; c'est une étape préparatoire du plan global, destinée à bâtir une assise solide pour l'implant. Elle sert le plus souvent d'étape préparatoire à des traitements comme l'<a href=\"/fr/hizmet/tek-dis-implant/\">implant unitaire</a>. Chez les patients au volume osseux déjà suffisant, votre praticien saute cette étape et passe directement à la planification implantaire. La nécessité d'une greffe se décide au cas par cas, après examen et évaluation radiologique." },
    { q: "Pourquoi l'os de la mâchoire perd-il du volume ?", a: "Après une <a href=\"/fr/hizmet/dis-cekimi/\">extraction dentaire</a>, l'os perd la force masticatoire qui le stimulait et fond progressivement — un processus appelé <em>résorption</em>. Dans les zones restées longtemps vides, l'os s'amincit et perd de la hauteur. La maladie gingivale avancée érode aussi l'os qui soutient les dents ; le <a href=\"/fr/hizmet/dis-etim-kaniyor/\">saignement des gencives</a> est l'un des signaux d'alerte précoces de ce processus. Traumatismes, kystes et port prolongé de prothèses mènent à des pertes similaires. La perte osseuse tient rarement à une cause unique — plusieurs facteurs se combinent le plus souvent." },
    { q: "Quels types de matériaux de greffe utilise-t-on ?", a: "Quatre grands groupes se distinguent, selon l'origine du matériau et son mode de production. La greffe autogène est de l'os prélevé sur votre propre corps ; un second site chirurgical étant nécessaire, douleur et gonflement peuvent survenir là où l'os a été prélevé. L'allogreffe provient de banques de tissus humains, la xénogreffe de sources animales transformées. Les greffes synthétiques sont fabriquées en laboratoire à partir de matières premières biocompatibles — minérales, céramiques ou à base de bioverre. Tous ces matériaux sont réglementés comme dispositifs médicaux et doivent satisfaire aux normes en vigueur avant tout usage clinique. Aucun type n'est supérieur dans tous les cas : les greffes en particules conviennent mieux au comblement d'un espace, les greffes en bloc au gain de largeur." },
    { q: "Que se passe-t-il, étape par étape, pendant l'acte ?", a: "Votre praticien mesure d'abord hauteur et largeur osseuses au scanner 3D. Le jour de l'acte, la zone est anesthésiée localement ; pour les patients plus anxieux, la sédation peut aussi être évoquée. Une petite incision dans la gencive expose la zone déficitaire. Le matériau de greffe est placé dans l'espace, recouvert d'une membrane protectrice, et le site est suturé. Si l'os restant permet à l'implant d'atteindre une <em>stabilité primaire</em> suffisante, greffe et implant se posent dans la même séance ; sinon, l'implant se pose séparément, une fois la greffe mûrie. Chez les patients à perte osseuse étendue, des plans qui exploitent l'os disponible sous d'autres angles — comme les <a href=\"/fr/hizmet/all-on-4/\">implants All-on-4</a> — entrent en considération." },
    { q: "Combien de temps dure la cicatrisation, et quand pose-t-on l'implant ?", a: "La cicatrisation des tissus mous progresse nettement dans les une à deux premières semaines. L'intégration osseuse exige une maturation plus longue, typiquement de trois à six mois. Pour les défauts étendus et les greffes en bloc, cela peut aller jusqu'à neuf mois. Tabac, diabète et hygiène bucco-dentaire influencent directement la vitesse de cicatrisation. Une fois l'implant posé, il faut encore compter environ deux à quatre mois à la mandibule, trois à six mois au maxillaire, pour la fusion avec l'os. Si le scanner de contrôle ne montre pas une maturation suffisante, votre praticien prolonge l'attente." },
    { q: "Quelle technique choisir quand le volume manque ?", a: "La direction de la perte osseuse détermine le choix. Quand la largeur manque, votre praticien planifie une technique d'élargissement osseux ou une greffe en bloc. Quand la hauteur fait défaut, une greffe en particules s'utilise avec une membrane barrière. À l'arrière du maxillaire, la hauteur reste limitée parce que le sinus s'étend vers le bas ; là, votre praticien envisage un <a href=\"/fr/hizmet/sinus-lifting/\">sinus lift</a> en complément de la greffe. Dans les cas limites, des implants courts ou de diamètre étroit peuvent constituer une alternative à la greffe." },
    { q: "Quels bénéfices peut-on attendre ?", a: "La greffe peut aider à reconstruire le volume nécessaire à un implant — des zones jugées auparavant inadaptées au traitement implantaire peuvent redevenir exploitables. Le soutien osseux augmenté, l'objectif est une répartition plus homogène des charges autour de l'implant. Dans les zones longtemps édentées, la tendance des contours du visage à se creuser peut diminuer. Un niveau gingival plus régulier soutient aussi le résultat esthétique. Cela dit, la greffe ne restaure pas à elle seule la fonction de la dent perdue — ce rôle revient à l'implant ou à la restauration posés ensuite." },
    { q: "Quels risques et complications peuvent survenir ?", a: "Comme tout acte chirurgical, celui-ci comporte des risques. Œdème, ecchymoses et sensibilité apparaissent dans la zone les premiers jours — généralement passagers. Infection et réouverture de la plaie le long des sutures peuvent perturber la cicatrisation. L'exposition de la membrane peut mener à une infection et à la perte partielle ou totale de la greffe. Dans certains cas, le volume osseux visé n'est pas atteint et l'acte doit être répété. Quand on travaille près des nerfs alvéolaire inférieur et mentonnier à l'arrière de la mandibule, engourdissement et picotements peuvent gagner la lèvre, le menton ou la langue ; cette modification de la sensibilité se résorbe en semaines ou mois dans la plupart des cas, mais peut être <strong>définitive</strong> dans un petit nombre. Chez les patients recevant une greffe autogène, douleur, gonflement et sensibilité passagère peuvent survenir au site donneur. Dans les cas menés avec un <a href=\"/fr/hizmet/sinus-lifting/\">sinus lift</a>, la membrane sinusienne peut se déchirer — avec sinusite possible ou dispersion du matériau dans le sinus. Tabac, diabète non équilibré et hygiène insuffisante augmentent tous ces risques. Arrêter de fumer et équilibrer la glycémie dans les semaines précédant l'acte réduit la probabilité de complications." },
    { q: "À qui ne convient-elle pas ?", a: "Chez certains patients, votre praticien reporte l'acte ou modifie le plan. Diabète non équilibré, infection active et maladie gingivale avancée non traitée figurent en tête de liste. Un antécédent de radiothérapie de la tête et du cou appelle une évaluation complémentaire. Les médicaments antirésorptifs utilisés contre la perte osseuse étant liés à un risque d'ostéonécrose des mâchoires, votre praticien vous interrogera en détail sur vos traitements et antécédents. Les troubles de la coagulation sont également passés en revue avant l'acte. Le tabagisme important nuit nettement à la cicatrisation. Chez les jeunes dont la mâchoire n'a pas fini de se développer, on attend la fin de la croissance. La décision d'indication revient à votre praticien, une fois connus votre historique médical et vos traitements." },
    { q: "À quoi faire attention les premiers jours après une greffe ?", a: "Appliquer du froid sur la zone dans les premières 24 heures aide à réduire l'œdème. Écartez un temps les aliments durs, chauds et très épicés. Toucher la zone traitée avec la langue ou le doigt peut déplacer la greffe. Utilisez bain de bouche et médicaments recommandés selon les consignes. Tabac et alcool nuisent à la cicatrisation : mieux vaut les éviter pendant cette période. Continuez à brosser normalement, en douceur, les zones voisines. Le premier contrôle se programme généralement trois à sept jours après l'acte, et les fils se retirent le plus souvent la deuxième semaine." },
    { q: "Le matériau de greffe placé est-il permanent ?", a: "Le degré de résorption dépend du type de matériau : une partie cède progressivement la place à de l'os nouveau, tandis que certaines particules restent en place comme soutien durable. Brossage régulier, nettoyage interdentaire et contrôles périodiques aident à préserver les niveaux osseux. Une hygiène négligée peut au contraire entraîner de nouvelles pertes. C'est pourquoi le suivi compte autant que l'acte lui-même." }
  ],
  closing: "L'aptitude de votre structure osseuse à recevoir un implant se précise par un examen clinique et un scanner 3D. Les sujets de cette page donnent un aperçu général de la greffe ; le plan de votre propre cas peut différer. Pour toute question sur votre plan de traitement, vous pouvez nous joindre via notre <a href=\"/fr/contact/\">page de contact</a>.",
  metaDescription: "Greffe osseuse : quand l'utiliser ? Types de greffes, déroulement de l'acte, temps de cicatrisation et risques possibles, expliqués clairement."
};
