window.ARTICLE_FR = {
  slug: "ortognatik-cerrahi",
  title: "Chirurgie orthognathique",
  category: "Orthodontie",
  lead: "Dans certains problèmes d'occlusion, la cause n'est pas la position des dents mais la relation entre les os des mâchoires supérieure et inférieure. La chirurgie orthognathique est un parcours soigneusement planifié qui traite cette différence squelettique aux côtés du traitement orthodontique. Ci-dessous : les étapes, le calendrier, la récupération et les risques possibles.",
  faqs: [
    { q: "Qu'est-ce que la chirurgie orthognathique, et que vise-t-elle à corriger ?", a: "Le chirurgien sectionne l'os de la mâchoire le long de lignes planifiées et le fixe dans sa nouvelle position avec des mini-plaques et vis en titane. Le but n'est pas seulement d'aligner les dents — c'est de changer la relation entre les deux mâchoires. Voilà pourquoi l'acte ne se fait jamais isolément : il se planifie en un seul paquet avec le traitement orthodontique. Une occlusion qui ne s'engrène pas, une difficulté à mâcher, des problèmes d'élocution et une asymétrie de la ligne médiane du visage sont les raisons principales d'envisager cette voie. Des <a href=\"/fr/hizmet/dislerim-yamuk/\">dents d'apparence chevauchée</a> ne justifient pas à elles seules une chirurgie — ce qui compte, c'est la relation osseuse sous-jacente." },
    { q: "Chez qui le seul mouvement dentaire ne suffit-il pas, faisant entrer la chirurgie en scène ?", a: "Le décalage squelettique décrit les cas où l'occlusion ne s'engrènera jamais correctement, quelle que soit l'ampleur du déplacement des dents dans l'os. Exemples courants de ce groupe : mâchoire inférieure nettement en retrait ou trop avancée, mâchoire supérieure étroite, béance où les dents de devant ne se touchent jamais, asymétrie d'un côté du visage. Le rétrécissement des voies respiratoires pendant le sommeil fait aussi partie de l'évaluation ; chez certains patients décrivant un <a href=\"/fr/hizmet/horluyorum/\">ronflement</a>, la position des mâchoires s'examine comme facteur possible. L'orthodontiste détermine par téléradiographies et mesures scanner si le décalage vient des dents ou de l'os." },
    { q: "Pourquoi l'orthodontie d'abord — l'occlusion ne s'améliore-t-elle pas tout de suite ?", a: "L'orthodontie préparatoire peut sembler contre-intuitive au départ : l'occlusion ne s'améliore en général pas pendant cette phase — elle peut même paraître plus marquée un temps. Ce que l'orthodontiste fait réellement : ramener chaque dent à sa position correcte sur sa propre base osseuse, pour qu'à la repositionnement chirurgical des mâchoires, les dents s'engrènent correctement. Cela signifie défaire l'inclinaison que les dents ont adoptée au fil des ans pour masquer la différence squelettique — la décompensation. Le profil peut donc paraître plus saillant pendant une période. Un système fixe de bagues s'utilise à ce stade, la chirurgie ayant besoin de points d'ancrage fixes. Les contrôles continuent toutes les quatre à six semaines, et la préparation prend 12 à 18 mois dans la plupart des cas." },
    { q: "Sur quelles images et mesures le plan repose-t-il ?", a: "La planification commence en réunissant photos du visage, données scanner et scans de modèles numériques. L'équipe détermine par logiciel 3D la direction et la distance exacte, au millimètre, du déplacement de chaque mâchoire, puis produit les gouttières chirurgicales utilisées pendant l'opération. Orthodontiste et chirurgien maxillo-facial prennent ces décisions ensemble — alignement dentaire et mouvement osseux sont directement liés. Voies respiratoires, soutien des lèvres et position du menton font partie du même plan." },
    { q: "Que se passe-t-il sous anesthésie générale, et combien de jours d'hôpital ?", a: "L'acte se déroule sous anesthésie générale, largement par l'intérieur de la bouche — une cicatrice visible sur la peau du visage n'est en général pas nécessaire. La durée dépend du repositionnement d'une seule ou des deux mâchoires ; c'est une chirurgie planifiée sur plusieurs heures. L'os déplacé dans sa nouvelle position, il se fixe par plaques et vis en titane. Le séjour hospitalier est en général de deux à trois jours. Le blocage complet des mâchoires par fils est bien plus rare qu'autrefois ; dans la plupart des cas, des élastiques guident l'occlusion à la place." },
    { q: "Pourquoi l'orthodontie continue-t-elle une fois l'os installé ?", a: "L'os en nouvelle position, il reste entre les dents de petits espaces et des contacts inégaux. L'orthodontiste gère ce réglage fin après la chirurgie, visant une force de morsure répartie également sur toutes les dents. Cette étape prend six à huit mois dans la plupart des cas, en bagues fixes ou, dans les cas adaptés, en <a href=\"/fr/hizmet/seffaf-plakla-ortodonti/\">système d'aligneurs transparents</a>. L'assiduité du port des élastiques à ce stade influence directement la progression." },
    { q: "Comment s'organise le calendrier global du début à la fin ?", a: "Le calendrier se compose de trois blocs : orthodontie pré-chirurgicale, chirurgie et récupération, puis orthodontie post-chirurgicale. Additionnés, ils atteignent en général deux ans environ ; l'ampleur de la différence squelettique et la position de départ des dents jouent sur la durée. La majeure partie du gonflement régresse dans le premier mois, mais les contours du visage peuvent mettre plusieurs mois à se poser complètement. Le retour au bureau ou à l'école se situe en général entre deux et quatre semaines, et le praticien cale la reprise du volant sur votre besoin restant d'antalgiques. Métiers physiques et sports de contact attendent en général plus longtemps — ces délais varient selon la fonte du gonflement et l'avancée de la récupération. La cicatrisation osseuse progresse nettement dans les six premières semaines, et les rendez-vous se rapprochent pendant cette période post-chirurgicale précoce." },
    { q: "Quels sont les risques et complications possibles ?", a: "Comme toute chirurgie, l'orthognathique porte ses risques propres. Le plus discuté : le changement de sensation — l'engourdissement de la lèvre inférieure, du menton et de la gencive est un constat <em>attendu</em> après la chirurgie, pas une complication en soi. Dans la plupart des cas, la sensation revient en semaines ou en mois ; chez certains patients, elle peut rester définitive. Gonflement, ecchymoses et difficulté à avaler font partie normale des premières semaines. L'ouverture buccale reste limitée quatre à six semaines dans la plupart des cas ; pendant cette période, les patients tiennent les exercices d'ouverture montrés par le praticien, avec kinésithérapie au besoin. Le chirurgien laisse en général les plaques de fixation en place ; en cas de gêne persistante ou d'infection locale, elles se retirent par un geste mineur une fois la cicatrisation acquise. Infection, saignement et — rarement — un second geste chirurgical restent possibles. Des symptômes articulaires préexistants peuvent changer après la chirurgie ; ils s'apaisent chez certains et s'accentuent chez d'autres. Un certain degré de récidive vers la position d'origine peut survenir, surtout avec les grands déplacements." },
    { q: "Quand la chirurgie n'est-elle pas menée, ou reportée ?", a: "Aucune chirurgie avant la fin de la croissance — une relation corrigée peut se dérégler tant que les mâchoires se développent encore. Le praticien confirme l'arrêt de la croissance par radiographie main-poignet et suivi de la taille ; ce seuil tombe à un âge différent chez les filles et les garçons. Diabète non contrôlé, troubles de la coagulation et maladies cardiaques ou respiratoires sévères peuvent barrer la route côté anesthésie — rien ne se planifie sans l'avis du spécialiste concerné. Inflammation gingivale active et caries non traitées se règlent d'abord, et l'arrêt du tabac se demande pour toute la durée du parcours. Cette chirurgie ne convient pas aux personnes sans problème squelettique sous-jacent, dont la seule préoccupation est l'apparence. Chez les enfants encore en croissance, les approches d'<a href=\"/fr/hizmet/cocuk-ortodontisi/\">orthodontie pédiatrique</a> s'utilisent à la place, pour tenter de guider le développement des mâchoires." },
    { q: "Comment alimentation et élocution sont-elles touchées après la chirurgie ?", a: "L'alimentation est entièrement liquide les premiers jours — soupe, lait, mixés lisses et boissons à la paille couvrent cette période. Dès la deuxième semaine : passage aux aliments mous, puis retour graduel à l'alimentation normale ; les aliments durs ou difficiles à mâcher attendent en général la huitième semaine. La perte de poids est courante le premier mois — une diététicienne planifie apports en protéines et calories en conséquence. L'élocution peut sonner différemment les premières semaines, gonflement et sensation modifiée obligent ; la clarté revient en général avec le temps chez la plupart des gens. Brosse souple et bain de bouche recommandé par le praticien facilitent les soins de cette période." },
    { q: "Bagues ou aligneurs seuls peuvent-ils régler cela sans chirurgie ?", a: "Pour les différences squelettiques limites, corriger l'occlusion en la compensant par la position des dents sur leur base osseuse peut être possible — l'orthodontie de camouflage. Elle se mène en <a href=\"/fr/hizmet/dis-teli/\">bagues</a> ou en aligneurs, et dans les cas adaptés, elle peut écarter la chirurgie complètement. Plus la différence sous-jacente grandit, plus les limites du camouflage se dessinent : racines poussées hors de l'enveloppe osseuse, gencives qui reculent, profil qui n'évolue pas dans le sens espéré. L'orthodontiste explique le résultat probable des deux options, et la décision se prend ensemble, selon vos priorités." },
    { q: "Douleur articulaire et difficulté à mâcher se rattachent-elles à ce tableau ?", a: "Douleur, claquement et blocage de l'articulation ne viennent pas toujours d'un décalage squelettique ; serrement des dents, tension musculaire et plombage un peu haut peuvent produire un tableau similaire. Voilà pourquoi une plainte de <a href=\"/fr/hizmet/cene-agrisi-yasiyorum/\">douleur à la mâchoire</a> s'explore d'abord comme sujet à part. Quand l'occlusion ne touche que quelques dents, ou que les aliments ne se broient pas correctement, ce type de <a href=\"/fr/hizmet/rahat-cigneyemiyorum/\">difficulté à mâcher</a> peut orienter vers une cause squelettique. Tout symptôme articulaire présent avant la chirurgie se consigne au départ, et douleur comme ouverture buccale se suivent aux mêmes mesures tout au long du parcours." },
    { q: "Que faut-il pour que le résultat dure ?", a: "L'étape de contention est la partie du traitement la plus facile à négliger — et elle pèse directement sur la tenue du résultat. Les bagues retirées, l'orthodontiste pose une contention fixe ou amovible, planifiée sur le long terme. Chez les patients qui continuent de serrer, une gouttière de nuit peut se recommander — la force excessive fatigue dents et site de fixation. Les contrôles se rapprochent la première année. Des soins bucco-dentaires suivis aident l'occlusion obtenue à rester stable durablement." }
  ],
  closing: "Difficile de deviner la source d'un problème d'occlusion au seul regard de la position des dents ; si une différence squelettique est en jeu, le plan de traitement se construit autrement dès le départ. La décision d'une chirurgie orthognathique ne se précipite pas — elle demande une conversation complète sur les options et tout le calendrier. Pour vos questions, vous pouvez nous joindre via notre <a href=\"/fr/contact/\">page de contact</a>.",
  metaDescription: "Chirurgie orthognathique : pour qui, et que couvrent les orthodonties pré et post-chirurgicales ? Calendrier de traitement, récupération et risques."
};
