window.ARTICLE_FR = {
  slug: "sinus-lifting",
  title: "Sinus lift",
  category: "Traitements Implantaires",
  lead: "Pour qui envisage des implants à l'arrière du maxillaire, la hauteur osseuse est souvent limitée — le sinus lift est une préparation chirurgicale destinée à augmenter cette mesure. Cette page couvre la différence entre techniques ouverte et fermée, la durée de l'acte, le calendrier de cicatrisation et les risques possibles, chacun sous sa rubrique. Ouvrez celle qui vous intéresse.",
  faqs: [
    { q: "Qu'est-ce qu'un sinus lift ?", a: "Le sinus maxillaire est une cavité remplie d'air sous la pommette, proche des racines des dents postérieures supérieures. La fine membrane qui tapisse cette cavité s'appelle la membrane de Schneider. Pendant la chirurgie, votre praticien soulève délicatement cette membrane de son plancher et comble l'espace créé avec un matériau de greffe, afin d'augmenter la hauteur disponible pour un implant. L'acte est aussi appelé élévation ou augmentation du plancher sinusien. Pour une seule dent manquante, cette préparation est souvent la première étape d'un plan d'<a href=\"/fr/hizmet/tek-dis-implant/\">implant unitaire</a>." },
    { q: "Quand un sinus lift est-il nécessaire ?", a: "Après la perte des dents, l'os se résorbe progressivement tandis que le sinus s'étend vers le bas — combinez les deux, et l'espace disponible pour un implant se réduit. Dans les zones longtemps édentées, la perte osseuse progresse davantage, et la maladie gingivale avancée l'accélère. Chez certaines personnes, le sinus est naturellement volumineux de naissance et ne laisse d'emblée pas assez de place. Votre praticien mesure au scanner 3D la hauteur osseuse existante au millimètre et examine sur les mêmes images l'anatomie sinusienne — cloisons osseuses internes et épaisseur de la membrane comprises. S'appuyer sur la seule panoramique peut induire en erreur dans cette zone. Quand plusieurs dents manquent à l'arrière, la planification du <a href=\"/fr/hizmet/coklu-dis-koprulu-implant/\">bridge sur implants</a> fait partie de la même évaluation." },
    { q: "Comment se déroule la technique ouverte (fenêtre latérale) ?", a: "Aussi appelée abord latéral ou externe, cette technique consiste à soulever la gencive et à ouvrir une petite fenêtre dans la paroi latérale de la mâchoire. À l'aide de fins instruments manuels, votre praticien soulève doucement la membrane et comble l'espace obtenu avec le matériau de greffe, en couches, avant de suturer. Cette voie s'envisage quand la hauteur osseuse restante est nettement réduite. Si la membrane est très fine, une membrane barrière protectrice peut être posée pour réduire le risque de dispersion de la greffe. Cette approche permet parfois un gain de hauteur supérieur, mais la cicatrisation est plus longue. Quand les deux côtés doivent être traités, les deux sinus peuvent l'être en une séance — ou les séances espacées pour limiter œdème et gêne alimentaire. Les fils se retirent généralement après sept à dix jours. Pour les options de greffe, voir notre page <a href=\"/fr/hizmet/kemik-grefti/\">greffe osseuse</a>." },
    { q: "Avec la technique fermée (interne), l'implant peut-il être posé dans la même séance ?", a: "Cette approche, dite interne ou aux ostéotomes, ne nécessite pas de fenêtre distincte. Votre praticien travaille à travers le site implantaire lui-même et soulève le plancher sinusien de l'intérieur. Le gain reste limité, généralement entre trois et quatre millimètres. Cette méthode est privilégiée quand la hauteur restante atteint cinq millimètres ou plus — cette mesure seule ne suffit toutefois pas à trancher. Dans les zones de densité plus faible, le site est compacté plutôt qu'élargi. Le traumatisme tissulaire étant limité, l'œdème est le plus souvent modéré. Pendant la chirurgie, votre praticien évalue si une stabilité primaire suffisante permet de poser l'implant dans la même séance ; sinon, la pose attend une seconde séance. La membrane peut aussi se déchirer avec la technique fermée — et comme on la voit mal de l'intérieur, votre praticien peut choisir d'interrompre l'acte le cas échéant. Quand la pose simultanée est possible, le calendrier se raccourcit. Le choix final entre les deux techniques se guide sur les constats du scanner et les observations peropératoires." },
    { q: "Combien de temps dure l'acte, et rentre-t-on chez soi le jour même ?", a: "Avec la technique fermée, la chirurgie prend généralement vingt à quarante minutes ; l'ouverte peut aller jusqu'à une heure. L'anesthésie locale suffit dans la plupart des cas ; pour les personnes plus anxieuses, la sédation peut être évoquée. Acte ambulatoire : vous rentrez chez vous le jour même. Le retour à un travail de bureau est généralement possible sous quelques jours ; les métiers physiques demandent une pause plus longue." },
    { q: "Combien de temps prennent cicatrisation et formation osseuse ?", a: "Œdème, ecchymoses et un léger saignement de nez peuvent apparaître les premiers jours ; cela se calme en général en trois à sept jours. L'intégration du matériau de greffe à votre propre os prend bien plus longtemps. La greffe issue de votre os s'intègre plus vite ; les matériaux d'origine bovine ou synthétique forment l'os plus lentement. Avec la technique ouverte, les praticiens tablent sur une attente de quatre à neuf mois. Cette attente terminée, l'implant se pose — et un second processus commence : dans un maxillaire greffé, la fusion de l'implant avec l'os prend généralement quatre à six mois, parfois plus que dans l'os naturel. Ces deux périodes se succèdent : le calendrier total les additionne. Pendant l'attente, la zone peut être couverte d'une restauration provisoire. Santé générale, type de greffe et hygiène influencent ce calendrier. La formation osseuse se contrôle par un scanner de suivi, généralement en fin d'attente, juste avant le rendez-vous d'implant." },
    { q: "Quelles options de traitement cet acte ouvre-t-il ?", a: "Quand une zone auparavant inapte à l'implant atteint une hauteur suffisante, les options de restauration fixe deviennent possibles — et une prothèse amovible n'est souvent plus nécessaire. L'objectif est de répartir la force masticatoire sur l'arrière de la bouche. Quand la perte dentaire au maxillaire est plus étendue, votre praticien peut aussi envisager la planification <a href=\"/fr/hizmet/all-on-4/\">All-on-4</a>, qui se passe de greffe. Par exemple, quand deux molaires manquent d'un côté, une solution fixe sur deux implants distincts peut être conçue plutôt qu'un bridge." },
    { q: "Quels sont les risques et complications possibles du sinus lift ?", a: "Comme tout acte chirurgical, celui-ci comporte des risques. Le plus fréquent : une déchirure de la membrane sinusienne, à un taux loin d'être négligeable ; les petites déchirures se réparent en général dans la même séance, tandis que les grandes imposent d'interrompre l'acte, de laisser cicatriser et de reprogrammer la chirurgie quelques mois plus tard. Infection, poussée de sinusite, œdème prolongé ou congestion nasale peuvent se développer. Dans certains cas, cela peut évoluer vers une sinusite chronique ou une communication persistante entre bouche et sinus (fistule bucco-sinusienne), qui exige une nouvelle chirurgie. Avec la technique ouverte, la lésion du vaisseau qui longe la paroi latérale peut provoquer un saignement. Avec la fermée, l'instrument de percussion utilisé peut déclencher des vertiges positionnels passagers (VPPB). Des particules de greffe — ou l'implant lui-même — peuvent migrer dans le sinus ; le matériau doit alors parfois être retiré chirurgicalement. Il arrive aussi que la greffe forme moins d'os que prévu et que l'acte doive être répété. Des modifications passagères de l'odorat ont été rapportées. Épaisseur de la membrane, antécédents de sinusite et santé générale sont les principaux facteurs du niveau de risque." },
    { q: "À qui cet acte ne convient-il pas ?", a: "Votre praticien reporte l'acte en cas de sinusite active, de poussée de rhinite allergique ou d'infection locale. Si le scanner montre kyste, polype ou autre formation, il demande d'abord l'avis d'un ORL. Diabète non équilibré et troubles de la coagulation appellent une préparation distincte. Chez les patients sous antirésorptifs (bisphosphonates, dénosumab), l'acte s'évalue conjointement avec le spécialiste prescripteur, en raison du risque d'ostéonécrose des mâchoires ; en administration intraveineuse, l'acte est le plus souvent reporté. Les gros fumeurs affrontent un risque d'échec de greffe plus élevé : un plan d'arrêt préalable sera recommandé. Chez les jeunes dont la mâchoire n'a pas fini de grandir, on attend la fin de la croissance. Ces informations ne remplacent pas le diagnostic d'un praticien — la décision se prend après examen et imagerie." },
    { q: "Que faut-il éviter dans les semaines qui suivent ?", a: "Ne vous mouchez pas fort les premiers jours ; si vous devez éternuer, garder la bouche ouverte réduit la montée en pression dans le sinus. Boire à la paille, jouer d'un instrument à vent et le sport intense doivent aussi attendre. Privilégiez les aliments tièdes et mous. L'arrêt complet du tabac quelques semaines avant et après l'acte est recommandé — la durée exacte se fixe avec votre praticien. Ne planifiez pas d'activités impliquant des variations de pression — avion, plongée — sans son accord. À plus long terme, l'accumulation de plaque peut aussi abaisser les niveaux osseux : brossage régulier et <a href=\"/fr/hizmet/dis-tasi-temizligi/\">détartrages professionnels</a> réduisent ce risque. Le premier contrôle a généralement lieu le jour du retrait des fils." }
  ],
  closing: "La décision d'un sinus lift se prend en pesant ensemble les constats du scanner, votre santé générale et vos objectifs de traitement. Examen clinique et scanner 3D détermineront si votre cas exige cette préparation. Les informations de cette page sont fournies à titre indicatif et ne remplacent pas un plan de traitement personnel. Pour toute question, vous pouvez nous joindre via notre <a href=\"/fr/contact/\">page de contact</a>.",
  metaDescription: "Sinus lift : techniques ouverte et fermée, temps de cicatrisation, formation osseuse et préparation du maxillaire aux implants."
};
