window.ARTICLE_EN = {
  slug: "dis-cekimi",
  title: "Tooth Extraction",
  category: "General Treatments",
  lead: "Tooth extraction is the removal of a tooth from its bony socket using specialised instruments, carried out once keeping it in the mouth no longer serves any purpose. In modern dentistry, the priority is always to preserve the natural tooth — extraction only comes into the picture once other treatment options have been exhausted. On this page, you'll find how a simple extraction proceeds, why the blood clot afterwards is so important, and how the resulting gap can be filled.",
  faqs: [
    { q: "What is tooth extraction, and why is it carried out?", a: "Tooth extraction means loosening the connective tissue around a tooth under local anaesthetic and removing it from its bony socket. Your dentist first considers tooth-preserving options such as a filling, <a href=\"/en/hizmet/kanal-tedavisi/\">root canal treatment</a> or a crown; extraction only comes into the picture if the tooth can't be kept using these methods. The aim is to remove the source of pain and infection, while protecting the neighbouring teeth and the jawbone. The technique used on teeth that are visible in the mouth and still have largely sound roots is called a <em>simple extraction</em>." },
    { q: "When does tooth extraction become unavoidable?", a: "Extraction becomes the front-running option when advanced decay has reached down to root level, when a crack extends below the bone margin, or when gum disease has significantly eroded the bone holding the tooth in place. Recurring abscesses and infections that don't settle despite repeated treatment also belong on this list. Extraction can also be planned in orthodontic treatment, to create space in a crowded jaw. Teeth that remain inside the jawbone need a different surgical approach, which we cover in detail on our <a href=\"/en/hizmet/gomulu-dis-cekimi/\">impacted tooth extraction</a> page." },
    { q: "What's the difference between a simple extraction and a surgical extraction?", a: "In a simple extraction, the tooth is visible in the mouth; your dentist uses an elevator and forceps to loosen it from its socket, and the gum usually isn't cut. In a surgical extraction, your dentist lifts a small flap of gum, removes some bone if needed, and takes the tooth out in sections. The two techniques aren't interchangeable — the tooth's position determines which one is appropriate. Wisdom teeth that have only partially come through, or that sit at an angle, generally fall into the second group, and we cover them separately under <a href=\"/en/hizmet/yirmilik-yas-disi-cekimi/\">wisdom tooth extraction</a>. An X-ray is the first step in planning, as it gives your dentist an idea of root number and how close the roots sit to the nerve canal." },
    { q: "What are the stages of the procedure?", a: "Your dentist starts with an examination and an X-ray, and asks about your medical history, any medication you're taking, and your bleeding tendency. They then give a local anaesthetic to the area and wait a few minutes for it to take effect. The periodontal fibres around the tooth are loosened, the tooth is eased out of its socket with controlled movements, and the socket is cleaned. A few stitches may be placed if needed, after which you'll be asked to bite down on sterile gauze to apply pressure to the area. You may feel pressure and a pushing sensation throughout the procedure; if you feel any sharp pain, let your dentist know straight away so the anaesthetic can be topped up." },
    { q: "How long does it take, and how many days does healing take?", a: "Once the anaesthetic has taken effect, extracting a single-rooted tooth is usually completed within a few minutes; molars can take a little longer. The whole appointment, including the examination and aftercare instructions, rarely takes more than half an hour in total. The soft tissue closes over within one to two weeks. The bony socket filling in and maturing is a quiet process that plays out over several months. Swelling generally peaks in the first two days and then subsides; pain that <strong>increases</strong> after day three falls outside the normal pattern." },
    { q: "Why is the blood clot so important after an extraction?", a: "The blood clot that forms within minutes in the empty socket is a natural covering that protects the exposed bone and nerve endings underneath. New blood vessels and bone-forming cells grow into this clot — it forms the scaffold that healing is built on. Drinking through a straw, rinsing forcefully, spitting repeatedly, and the suction created by smoking can all dislodge it. That's why, in the first twenty-four hours, you're asked to swallow rather than spit, and to avoid poking at the area with your finger or tongue. A hot shower, strenuous exercise and alcohol can all restart bleeding too, so it's best to put these off for the first day." },
    { q: "What is dry socket (alveolitis), and how do you recognise it?", a: "If the clot is lost early, or never forms properly, the bone is left exposed to the mouth and dry socket develops. It typically starts two to four days after the extraction, with a throbbing pain that radiates to the ear or temple; the socket may look empty and greyish where the clot should be, and there can be an unpleasant smell. Painkillers usually don't control this pain well enough, so waiting for it to pass on its own wastes time. It's noticeably more common after extracting lower molars and impacted teeth, in smokers, and in people with poor oral hygiene. Your dentist irrigates the socket with saline and places a medicated dressing to ease the pain; this may need to be repeated over a few visits." },
    { q: "What are the risks and possible complications of tooth extraction?", a: "As with any surgical procedure, unwanted outcomes can occur. Bleeding, swelling, bruising, and restricted mouth opening caused by the chewing muscles tensing up are common and generally settle within a few days. Infection, damage to a neighbouring tooth or its filling, a root tip breaking off and remaining in the socket, and numbness of the lip or chin where the lower roots sit close to the nerve are all less common. This numbness resolves within weeks in most cases, though it can rarely be permanent; if your dentist spots a risky proximity on the X-ray, they'll let you know in advance. In the upper back teeth, there's also a possibility of a connection opening up between the sinus and the mouth, which may need an additional procedure to close. In people on blood thinners or with a bleeding disorder, bleeding can take longer to settle. Contact the clinic if you have pain that's still getting worse after forty-eight hours, fever, or difficulty swallowing." },
    { q: "Who isn't it suitable for, and when is it postponed?", a: "Where there's an acute, spreading infection, your dentist usually brings it under control first with antibiotics and drainage, and postpones the extraction. Uncontrolled diabetes, a recent heart attack or stroke, serious bleeding disorders, and a history of radiotherapy to the head and neck all call for detailed assessment. People taking bone-strengthening medication can have healing problems in the jawbone, so your dentist liaises with the specialist managing that treatment. In pregnancy, non-urgent extractions are generally planned for the second trimester. Sharing all the medication you take and any chronic conditions you have before your appointment is essential for this assessment to be done properly." },
    { q: "What should you be careful of, and what does aftercare involve?", a: "Bite down on the gauze with steady pressure for about half an hour, and avoid taking it out to check too often. On the first day, apply a cold compress to your cheek at intervals, and stick to warm, soft food. Keep brushing your teeth, but avoid the extraction site itself; once your dentist gives the go-ahead, you can move on to gentle rinsing with warm salt water. Taking a break from smoking is an important step in lowering your risk of dry socket. Take painkillers as directed by your dentist, and don't take medication such as aspirin, which can increase bleeding, on your own judgement." },
    { q: "What can be done to replace the extracted tooth?", a: "If the gap is left open for a long time, the neighbouring teeth tip into the space, the tooth in the opposite jaw over-erupts, and the balance of your bite is thrown off. The jawbone also loses volume in an area that's no longer in use. That's why your dentist discusses how the gap will be filled as part of planning the extraction itself: a <a href=\"/en/hizmet/tek-dis-implant/\">single tooth implant</a>, a <a href=\"/en/hizmet/porselen-kron-kopru/\">porcelain crown and bridge</a> supported by the neighbouring teeth, or removable dentures are all options. If an implant is being considered, healing usually takes a few months before it can proceed; if bone volume is insufficient, a <a href=\"/en/hizmet/kemik-grefti/\">bone graft</a> may come into the picture. Which option suits you becomes clear once the condition of your remaining teeth and bone measurements have been assessed." }
  ],
  closing: "Extraction is the last step, considered only once every possibility of keeping the tooth has been exhausted. If you have a painful or loose tooth, you can book an appointment via our <a href=\"/en/contact/\">contact page</a> so we can talk through the options beyond extraction as well.",
  metaDescription: "When is tooth extraction needed, and how does it proceed? The importance of the blood clot, dry socket symptoms, risks and replacement options."
};
