window.ARTICLE_EN = {
  slug: "disim-agriyor",
  title: "My Tooth Hurts",
  category: "Sleep & Jaw Health",
  lead: "Toothache that starts on its own, throbs, and gets worse at night is often an early sign of a problem in the inner tissue of the tooth or around the root. It's a different picture from the fleeting sensitivity brought on by something cold or sweet that fades within seconds — this kind of pain isn't expected to settle on its own. This page explains the possible sources of the pain, which symptoms call for urgent attention, and what to expect during an examination.",
  faqs: [
    { q: "What can constant, throbbing toothache be a sign of?", a: "The pulp tissue at the centre of a tooth is made up of nerves and blood vessels and is surrounded by hard walls. When inflammation develops in this tissue, the swelling it produces has nowhere to expand into, so pressure builds and you feel a throbbing that matches your pulse. Pain that starts without any trigger, lasts for minutes or even hours, and doesn't fully settle with painkillers are all signals consistent with this picture. That said, throbbing on its own isn't a diagnosis — the source could be the tooth, the gum, the jawbone or a neighbouring structure. Telling these apart is done through a clinical examination together with X-ray findings." },
    { q: "What are the most common causes of toothache?", a: "Deep decay tops the list: decay that's worked its way through the enamel and dentine can trigger inflammation that becomes difficult to reverse once it reaches the pulp. Second comes advanced pulp inflammation — once the tissue loses its vitality, an abscess can form at the root tip, and the pain sharpens when you press on the tooth. A cracked tooth tends to announce itself with pain that appears especially after biting into something hard, and that comes on the moment you release the bite. Gum-related abscesses can produce severe pain even when the tooth itself looks perfectly sound; this picture can come with a swelling, redness or an unpleasant discharge from the gum. Decay progressing beneath an old filling, a broken crown, and a wisdom tooth coming through are also common causes. Less often, inflammation in the sinuses above the upper jaw can produce a sensation of pain in the upper back teeth; in that case, several teeth are usually tender at once." },
    { q: "What's the difference between this and the brief sensitivity you get with cold?", a: "The difference largely comes down to timing. Sensitivity starts with a trigger, is brief, and eases quickly once the trigger is removed; cold water, hot tea or a sweet mouthful are typical triggers. What we're describing here is different: the pain starts without you doing anything, lasts for minutes, spreads, and wakes you at night. If you're dealing with brief, trigger-related sensitivity, our <a href=\"/en/hizmet/disim-sizliyor/\">my tooth is sensitive</a> page is a better starting point. The two pictures can also shift from one to the other — sensitivity that's lasted for weeks suddenly turning into spontaneous throbbing is a warning sign that the problem has gone deeper." },
    { q: "Why does my pain get worse at night and disturb my sleep?", a: "Lying down increases blood flow to the head, which raises the pressure in inflamed tissue. With the distractions of the day gone, your pain threshold also drops. Put the two together, and pain that seemed manageable during the day can become severe enough to wake you at night. Pain that worsens at night is a pattern that shouldn't be ignored." },
    { q: "What symptoms should I note down before I see the dentist?", a: "What comes with the pain is just as telling as its character. Pain that worsens with heat and eases somewhat with cold, sensitivity that sharpens when you touch or press the tooth, a tooth that feels like it's sitting higher than its neighbours, a spot-like bump on the gum, a persistent bad taste in the mouth, and a crackling sound when you chew are all worth noting. Pain spreading to the ear, temple or under the jaw is also worth mentioning. Passing these details on to your dentist shortens the examination and makes it easier to focus on the right area." },
    { q: "Which symptoms need urgent attention?", a: "If any of the following apply, don't wait — go to your nearest A&E department or an emergency dental service: swelling that's spreading across the face and growing quickly, swelling tracking down towards the eye or the neck, fever and shivering, difficulty swallowing, difficulty breathing, being unable to open your mouth, or stiffness in the neck. These findings can mean the infection has spread beyond the tooth into the soft tissue spaces, and that can be life-threatening. Waiting until morning, <strong>managing with painkillers</strong>, or hoping the swelling will go down on its own is not the right choice in this picture. If there's swelling, pain easing doesn't mean things are improving." },
    { q: "If there's no urgent sign, how soon should I see a dentist?", a: "For spontaneous, throbbing pain, the right approach is the earliest appointment you can get — this kind of pain doesn't tend to settle on its own. Pain stopping within a few days often doesn't mean healing; it can mean the pulp tissue has lost its vitality, and after a quiet spell the picture can come back as an abscess. Cancelling your appointment because the pain has stopped can lead to more extensive treatment being needed further down the line." },
    { q: "What can I do at home for temporary relief?", a: "Rinsing gently with warm salt water, clearing trapped food from between your teeth with floss, and keeping your head slightly raised when lying down can ease the pressure in the area a little. A cold compress wrapped in a thin cloth can be tried against the outside of the cheek for short spells. Staying away from very hot or very cold drinks and hard, sugary food reduces how often the pain is triggered. All of these give temporary relief; none of them removes the source of the problem." },
    { q: "Does putting aspirin on a painful tooth cause harm?", a: "<strong>Placing aspirin directly on a painful tooth</strong> is a common but harmful habit: the tablet chemically burns the gum and cheek tissue it touches, leaves a white sore, and doesn't reduce the pain. In the same way, clove oil, cologne, alcohol or vinegar applied directly to the tooth can irritate the tissue. A hot compress can make swelling worse where there's inflammation. Trying to burst a gum bump with a needle can carry the infection deeper into the tissue. Using leftover antibiotics from an old course on your own judgement masks the picture and increases the risk of resistance — the decision on whether antibiotics are needed belongs to your dentist." },
    { q: "What does the dentist check during an examination?", a: "The dentist first listens to when the pain started, what triggers it, and where it spreads to. They then examine the teeth and gums visually, carry out a percussion test on the suspect tooth, and assess the condition of the pulp with a cold or electric vitality test. Pocket depths are measured with a periodontal probe. A periapical X-ray shows changes at the root tip; 3D imaging may be requested where needed. Where a crack is suspected, a bite test and examination under magnification come into play. The aim of these steps is to distinguish the tooth causing the pain from its neighbours." },
    { q: "What treatments might come into the picture?", a: "Treatment depends on where the pain is coming from. For decay that hasn't reached the pulp, a <a href=\"/en/hizmet/dolgu/\">filling</a> after cleaning may be enough. Where pulp inflammation or a root-tip infection is found, <a href=\"/en/hizmet/kanal-tedavisi/\">root canal treatment</a> comes into the picture; if a lot of tooth structure has been lost, protecting the tooth afterwards with a <a href=\"/en/hizmet/kaplama/\">crown</a> may be planned. Where a crack runs down through the root, or the tooth can no longer be kept, <a href=\"/en/hizmet/dis-cekimi/\">tooth extraction</a> is considered. If the pain is coming from a wisdom tooth that's still coming through, <a href=\"/en/hizmet/yirmilik-yas-disi-cekimi/\">wisdom tooth extraction</a> is discussed; if the tooth is still within the bone, <a href=\"/en/hizmet/gomulu-dis-cekimi/\">impacted tooth extraction</a> is discussed instead. Which option is right can't be decided without seeing the examination and X-ray findings." },
    { q: "How can I reduce the pain coming back?", a: "Brushing with fluoride toothpaste twice a day and making interdental cleaning a habit act directly on the point where decay begins. A check-up every six months catches decay and leaking fillings early, before they start causing pain. If you have bleeding or receding gums, the steps on our <a href=\"/en/hizmet/dis-etim-kaniyor/\">my gums bleed</a> page can help. For people with a night-time <a href=\"/en/hizmet/dislerimi-sikiyorum/\">teeth clenching</a> habit, the risk of micro-cracks is higher, so a protective guard may be worth discussing. Breaking the habit of cracking ice, pen lids and hard-shelled nuts with your teeth also reduces the risk of a crack." },
    { q: "What are the common myths about toothache?", a: "Top of the list is the idea that <em>if the pain has gone, the tooth has healed</em> — but the nerve tissue dying off also silences the pain. The approach of <em>starting antibiotics will sort it out</em> is mistaken too, because medication doesn't remove the tissue at the source of the infection. The severity of the pain isn't always proportional to the extent of the damage: decay that looks minor can produce severe pain, while an advanced case can stay silent. Another common belief is that pain in an upper tooth is directly linked to the eye — in fact, referred pain from the sinuses in the upper back area is a far more likely explanation." }
  ],
  closing: "Toothache that wakes you up at night narrows your options the longer it's put off. If there's swelling in the face, fever or difficulty swallowing, urgent attention is needed without delay; if none of these are present, booking the earliest appointment you can is still the right step. You can reach us through our <a href=\"/en/contact/\">contact page</a> to have your pain assessed and discuss the right treatment plan.",
  metaDescription: "Throbbing toothache that worsens at night and disturbs sleep: possible causes, urgent warning signs like swelling and fever, and what to expect."
};
