window.ARTICLE_EN = {
  slug: "ortognatik-cerrahi",
  title: "Orthognathic (Jaw) Surgery",
  category: "Orthodontics",
  lead: "In some bite problems, the underlying cause isn't the position of the teeth but the relationship between the upper and lower jawbones. Orthognathic surgery is a carefully planned process that addresses this skeletal difference alongside orthodontic treatment. Below, you'll find the stages involved, the timeline, the recovery period, and the possible risks.",
  faqs: [
    { q: "What is orthognathic surgery, and what does it aim to correct?", a: "The surgeon divides the jawbone along planned lines and fixes it in its new position with mini titanium plates and screws. The goal isn't simply to line the teeth up neatly — it's to change the relationship between the upper and lower jaw. Because of this, the procedure never happens in isolation; it's planned as a single package together with orthodontic treatment. A bite that doesn't come together properly, difficulty chewing, problems with speech, and asymmetry along the facial midline are the main reasons this route is considered. <a href=\"/en/hizmet/dislerim-yamuk/\">Crowded-looking teeth</a> aren't on their own a reason for surgery — what matters is the underlying bone relationship." },
    { q: "In whom does tooth movement alone fall short, bringing surgery into the picture?", a: "A skeletal discrepancy describes cases where the bite still won't come together properly, no matter how far you move the teeth within the bone. Common examples in this group include a lower jaw that's noticeably set back or too far forward, a narrow upper jaw, an open bite where the front teeth never touch, and asymmetry affecting one side of the face. Narrowing of the airway during sleep is also part of the assessment; in some patients who report <a href=\"/en/hizmet/horluyorum/\">snoring</a>, jaw position is examined as a possible factor. The orthodontist uses cephalometric X-rays and CT measurements to work out whether the discrepancy comes from the teeth or from the bone." },
    { q: "Why is orthodontics done first — doesn't the bite improve straight away?", a: "Preparatory orthodontics can feel counterintuitive at first, because the bite usually doesn't improve during this phase — it can even look more pronounced for a while. What the orthodontist is actually doing is bringing each tooth into the correct position on its own bone base, so that when the jaws are repositioned during surgery, the teeth can come together properly. This means undoing the tilt teeth have gradually adopted over the years to disguise the skeletal difference — a process called decompensation. Because of this, the profile can look more striking for a period. A fixed brace system is used at this stage, since surgery needs fixed points to attach to. Check-ups continue every four to six weeks, and preparation takes 12 to 18 months in most cases." },
    { q: "What imaging and measurements does the plan rely on?", a: "Planning starts by bringing together facial photographs, CT data and digital model scans. The team works out the direction and exact distance, in millimetres, that each jaw needs to move using 3D software, then produces the surgical splints that will be used during the operation. The orthodontist and the jaw surgeon make these decisions jointly at this stage, since tooth alignment and bone movement are directly linked. The airway, lip support and the position of the chin are all part of the same plan." },
    { q: "What happens under general anaesthetic, and how many days is the hospital stay?", a: "The procedure is carried out under general anaesthetic, largely from inside the mouth, so a visible scar on the facial skin isn't usually necessary. How long it takes depends on whether one jaw or both need to be repositioned, and it's planned as a surgery lasting several hours. Once the surgeon has moved the bone into its new position, it's fixed with titanium plates and screws. The hospital stay is usually two to three days. Wiring the jaws fully shut is far less common than it used to be; in most cases, elastics are used to guide the bite instead." },
    { q: "Why does orthodontic treatment continue once the bone has settled into place?", a: "Once the bone is in its new position, small gaps and uneven contacts remain between the teeth. The orthodontist handles this fine-tuning after surgery, aiming for the biting force to be shared evenly across all the teeth. This stage takes six to eight months in most cases, and is carried out with fixed braces or, in suitable cases, with a <a href=\"/en/hizmet/seffaf-plakla-ortodonti/\">clear aligner system</a>. How consistently elastics are worn at this stage has a direct effect on how treatment progresses." },
    { q: "How does the overall timeline work from start to finish?", a: "The timeline is made up of three blocks: pre-surgical orthodontics, the surgery and recovery, then post-surgical orthodontics. Added together, these usually come to around two years in total; the size of the skeletal difference and the starting position of the teeth both affect how long it takes. Most of the swelling goes down within the first month, though it can take several months for the facial contours to settle completely. Returning to a desk job or to school is usually on the cards somewhere between two and four weeks, and the dentist times the return to driving around how much painkiller you still need. Physically demanding jobs and contact sports generally mean a longer wait, and these timeframes vary depending on how quickly the swelling goes down and how recovery is progressing. Bone healing makes clear progress within the first six weeks, and appointments come round more often during this early post-surgical period." },
    { q: "What are the risks and possible complications?", a: "Like any surgical procedure, orthognathic surgery carries its own specific risks. The most commonly discussed is a change in sensation: numbness in the lower lip, chin and gum area is an <em>expected</em> finding after surgery, not a complication in itself. In most cases this sensation returns within weeks or months, though in some patients it can be permanent. Swelling, bruising and difficulty swallowing are a normal part of the first few weeks. Mouth opening stays restricted for four to six weeks in most cases; during this period, patients keep up the opening exercises the dentist shows them, with physiotherapy support if needed. The surgeon usually leaves the fixation plates in place; if there's ongoing discomfort or infection in the area, they can be removed with a minor procedure once healing is complete. Infection, bleeding, and — rarely — the need for a second procedure are all possibilities. Any pre-existing jaw joint symptoms can change after surgery; they ease in some patients and become more noticeable in others. Some degree of relapse back towards the original position can occur, particularly with larger movements." },
    { q: "When is surgery not carried out, or postponed?", a: "Surgery isn't carried out before growth is complete, since a corrected relationship can be thrown off again while the jaws are still developing. The dentist confirms that growth has stopped using measures such as a hand-wrist X-ray and height tracking; this threshold falls at a different age in girls and boys. Uncontrolled diabetes, bleeding disorders, and severe heart or respiratory disease can all pose a barrier from an anaesthetic point of view, and the procedure isn't planned without input from the relevant specialist. Active gum inflammation and untreated decay are dealt with first, and patients are asked to stop smoking for the duration of the process. This surgery isn't appropriate for people whose bite has no underlying skeletal problem and whose only concern is appearance. In children who are still growing, <a href=\"/en/hizmet/cocuk-ortodontisi/\">children's orthodontics</a> approaches are used instead, to try to guide jaw development." },
    { q: "How are eating and speech affected after surgery?", a: "Eating is entirely liquid in the first few days — soup, milk, smooth blended mixtures, and drinks taken through a straw cover this period. From the second week, patients move on to soft foods, then gradually back towards a normal diet; hard or difficult-to-chew foods are usually left until around the eighth week. Weight loss is common in the first month, so a dietitian plans your protein and calorie intake accordingly. Speech can sound altered in the first few weeks because of swelling and changed sensation; clarity generally comes back over time for most people. A soft toothbrush and any mouthwash the dentist recommends make oral care easier during this period." },
    { q: "Can braces or clear aligners alone resolve this without surgery?", a: "For borderline skeletal differences, it can be possible to correct the bite by compensating for it through the position of the teeth on their bone base — an approach known as camouflage orthodontics. This is carried out with <a href=\"/en/hizmet/dis-teli/\">braces</a> or clear aligner systems, and in suitable cases it can keep surgery off the table altogether. As the underlying difference gets bigger, the limits of camouflage become clearer: tooth roots can be pushed outside the bone envelope, gums can recede, and the profile won't change in the direction you'd hope for. The orthodontist explains the likely outcome of both options, and the decision is made together, based on the patient's priorities." },
    { q: "Are jaw joint pain and chewing difficulty related to this picture?", a: "Pain, clicking and locking in the jaw joint don't always stem from a skeletal discrepancy; teeth clenching, muscle tension and a filling sitting slightly too high can all produce a similar picture. That's why a complaint of <a href=\"/en/hizmet/cene-agrisi-yasiyorum/\">jaw pain</a> is investigated as a separate issue in its own right first. Where the bite only makes contact on a few teeth, or food can't be broken down properly when chewing, that kind of <a href=\"/en/hizmet/rahat-cigneyemiyorum/\">difficulty chewing</a> can point towards a skeletal cause. Any jaw joint symptoms present before surgery are recorded at the outset, and pain levels and mouth opening are tracked against the same measures throughout the process." },
    { q: "What's needed to make the result last?", a: "The retention stage is the part of treatment that's easiest to neglect, yet it has a direct bearing on how well the result holds up. Once the braces come off, the orthodontist fits a fixed or removable retainer, planned to be worn over the long term. In patients who continue to clench their teeth, a night guard may be recommended, since excessive force puts strain on both the teeth and the fixation site. Check-ups are more frequent in the first year. Keeping up good oral care helps the bite you've achieved stay stable for the long term." }
  ],
  closing: "It's difficult to work out the source of a bite problem just by looking at how the teeth are positioned; if a skeletal difference is involved, the treatment plan needs to be built differently from the outset. A decision on orthognathic surgery shouldn't be rushed — it needs a full conversation about the options and the whole timeline involved. For any questions, you can reach us via our <a href=\"/en/contact/\">contact page</a>.",
  metaDescription: "Orthognathic (jaw) surgery: who needs it, and what pre- and post-surgical orthodontics involve. We cover the treatment timeline, recovery and risks."
};
